<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rechnungsadresse_billingAddressLine1</name>
   <tag></tag>
   <elementGuidId>47aaa8ca-0f7d-4487-ab20-6c3b1614639d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingAddressLine1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billingAddressLine1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a9b69bf-0eae-4724-bd4b-940fc353d040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CheckoutInput Input Input--empty</value>
      <webElementGuid>0bd4c6b9-90a1-49ab-a51e-e1578c5e95b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>e367c079-602e-40a6-97eb-2d155872e846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3726f1da-5364-4d54-bec7-10f66bc5ae1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>015895ab-24f3-4f8e-bc89-9203aafb8f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingAddressLine1</value>
      <webElementGuid>088d8c3b-9756-4dde-a61a-678d2f8e04ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingAddressLine1</value>
      <webElementGuid>804dc890-6bcc-4151-b06c-3b76be021ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b20bd551-463d-44d6-be0b-c2fbeb9c0a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Adresszeile 1</value>
      <webElementGuid>3570d2f8-a9db-47dc-8df6-8864d90abce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Adresszeile 1</value>
      <webElementGuid>41a67d98-aa22-439a-bad2-a6777fe5ca1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>62d9c197-21a4-4adb-a8ab-64d96ef8840b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-1p-ignore</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>26b70bed-0088-48dd-be27-317955a08a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lp-ignore</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac1656fa-54fb-47d8-8a0e-515a4cacbe79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingAddressLine1&quot;)</value>
      <webElementGuid>e2261869-0dc7-4d6b-854e-d88456303445</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingAddressLine1']</value>
      <webElementGuid>6821564a-3b64-4dba-abee-f9d277f36285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='billing-address-fieldset']/div/div[2]/div/div/span/input</value>
      <webElementGuid>60545770-7544-409d-bde2-8607b8536727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/fieldset/div/div[2]/div/div/span/input</value>
      <webElementGuid>3cf06de0-dbbe-4290-bc64-1912916218e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'billingAddressLine1' and @name = 'billingAddressLine1' and @type = 'text' and @placeholder = 'Adresszeile 1']</value>
      <webElementGuid>fe12c03f-3cd7-4d49-b097-0ffcf101d642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
