<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rechnungsadresse_billingLocality</name>
   <tag></tag>
   <elementGuidId>b9ea86b3-b27c-4eee-807c-f4cd92cdfbbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingLocality']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billingLocality</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06c6641f-da85-43b7-bd0e-68dda3633e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CheckoutInput Input Input--empty</value>
      <webElementGuid>3b97a9ee-c7c9-4667-9b36-89aaadfe44b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>billing address-level2</value>
      <webElementGuid>e556fd21-6f60-4a13-8599-527847a742cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4e088fbd-87b0-4bb7-8374-7b3e2ddaa11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3f663c97-03dc-4c8c-b389-acce7c4bd23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingLocality</value>
      <webElementGuid>903ae8c0-e8f9-450f-93b6-b12e3e55b71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingLocality</value>
      <webElementGuid>f491f18b-da51-416f-969c-e783493bec61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb0cc6cb-7430-4206-bef7-f0a1fd48294a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Ort</value>
      <webElementGuid>343a91e5-d6f2-4069-a4a6-37f644450fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ort</value>
      <webElementGuid>97b5d8be-47ae-480d-abaa-12384dacbfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f0280f2-4842-43da-806b-df9050c2799b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-1p-ignore</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1c113507-36f2-4625-bc6b-50a71c1200df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lp-ignore</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8395bf22-7a20-417b-bb20-a2fe065f3392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingLocality&quot;)</value>
      <webElementGuid>dfa06a2c-c30b-44f0-8c7e-1f233dc4e066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingLocality']</value>
      <webElementGuid>8e20f045-6188-46a8-b660-8baf1dd2ba02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='billing-address-fieldset']/div/div[5]/div/div/span/input</value>
      <webElementGuid>eef95839-d337-411b-8013-8ff91841339c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/span/input</value>
      <webElementGuid>5ad7af49-a2eb-42f6-94c2-89c3057be3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'billingLocality' and @name = 'billingLocality' and @type = 'text' and @placeholder = 'Ort']</value>
      <webElementGuid>3e5fd9b1-f103-4262-be18-9ba3c6c4799f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
