<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Application-name</name>
   <tag></tag>
   <elementGuidId>74a6e0b6-f324-4165-b1be-e7abd3e7bed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.AfwdI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz[2]/div/div/div/div/div/div/div/c-wiz/div[2]/div/div/div/div/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>47a1491d-5b54-49f8-be43-ff4b91a4cb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AfwdI</value>
      <webElementGuid>6c2fd722-4f30-43b5-8fc4-8ae419619b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>200174fa-2dc6-4b2a-a63c-f4f41896f615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PowerFolder</value>
      <webElementGuid>c7979429-b269-445f-ab93-bf38d9ffaffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;SSPGKf Czez9d&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;kFwPee&quot;]/div[1]/div[@class=&quot;tU8Y5c&quot;]/div[@class=&quot;P9KVBf&quot;]/div[@class=&quot;dzkqwc&quot;]/div[@class=&quot;wkMJlb YWi3ub&quot;]/c-wiz[1]/div[@class=&quot;hnnXjf XcNflb J1Igtd&quot;]/div[@class=&quot;qxNhq&quot;]/div[@class=&quot;RhBWnf&quot;]/div[1]/div[@class=&quot;Fd93Bb ynrBgc xwcR9d&quot;]/h1[1]/span[@class=&quot;AfwdI&quot;]</value>
      <webElementGuid>194cd492-0b69-4d06-a62f-8bbf97d85765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz[2]/div/div/div/div/div/div/div/c-wiz/div[2]/div/div/div/div/h1/span</value>
      <webElementGuid>8ebeb469-4ac8-48dd-b637-cb24ee02e977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enfants'])[3]/following::span[1]</value>
      <webElementGuid>f8084442-b51e-4559-b90d-8db29ba7330c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dal33t GmbH'])[1]/preceding::span[1]</value>
      <webElementGuid>4ebd22bc-4a7b-4c22-8be3-c092ac962cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Téléchargements'])[1]/preceding::span[2]</value>
      <webElementGuid>c31fbc9b-d6b3-410e-899d-3d1963822024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PowerFolder']/parent::*</value>
      <webElementGuid>6c79f5e9-6654-4f20-bfd1-585d9e18671d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>7468da1c-93d9-4896-aecf-e3f8b5330d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PowerFolder' or . = 'PowerFolder')]</value>
      <webElementGuid>f25337c8-16ad-430d-9b5f-c50bad0d6e15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
