<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Logger</name>
   <tag></tag>
   <elementGuidId>c896bf23-4084-4dd1-9bcd-4282dc4424d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='logs_table']/thead[2]/tr/th[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.pica-sortable-column.pica-small-column.hidden-sm.hidden-xs.pica-sortable-sorted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>c19dae40-051a-4d80-adb3-a15d51a79452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-sortable-column pica-small-column hidden-sm hidden-xs pica-sortable-sorted</value>
      <webElementGuid>46a5c817-81aa-4b17-9e5b-457224f612c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Logger
                </value>
      <webElementGuid>851ac29d-232f-4a71-9b59-f0b2f6dcce34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logs_table&quot;)/thead[2]/tr[1]/th[@class=&quot;pica-sortable-column pica-small-column hidden-sm hidden-xs pica-sortable-sorted&quot;]</value>
      <webElementGuid>993ace07-32ae-4db5-bb66-ed59a091992b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='logs_table']/thead[2]/tr/th[3]</value>
      <webElementGuid>0c4e712b-181e-404a-950c-5572a9fa0764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/following::th[1]</value>
      <webElementGuid>2bb40fb1-8fa0-43f8-8018-a38b31871c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[1]/following::th[3]</value>
      <webElementGuid>a90d52ef-83bf-4c7a-b85e-cb3b1176d815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/preceding::th[1]</value>
      <webElementGuid>7d2d54a9-3221-43c0-9628-2c0be4da371b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//thead[2]/tr/th[3]</value>
      <webElementGuid>7baea347-9186-408c-88ee-8dc0f7be9294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = '
                    Logger
                ' or . = '
                    Logger
                ')]</value>
      <webElementGuid>d1cb3c72-8e02-448f-a76a-0fb6b0a16bef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
