<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Message</name>
   <tag></tag>
   <elementGuidId>221ef33b-ad96-4e25-98e3-bffd2692032a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='logs_table']/thead[2]/tr/th[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.pica-sortable-column.pica-sortable-sorted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>9869f8a2-aa0d-4965-9b58-d4818f3b48c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-sortable-column pica-sortable-sorted</value>
      <webElementGuid>de253710-3527-438f-b6b8-b6bee7dcb3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Message
                </value>
      <webElementGuid>209392b3-ac90-4ab3-994a-8fb2698e72f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logs_table&quot;)/thead[2]/tr[1]/th[@class=&quot;pica-sortable-column pica-sortable-sorted&quot;]</value>
      <webElementGuid>4af73af3-9c4a-4178-998d-b286646023fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='logs_table']/thead[2]/tr/th[5]</value>
      <webElementGuid>a01ed4af-ab70-4662-a2e3-c5d8df477504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::th[1]</value>
      <webElementGuid>40b61843-64f6-46af-99cc-b4ec45757b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logger'])[1]/following::th[2]</value>
      <webElementGuid>dd5d3d6b-4c4f-44a3-97d2-634dddad5230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SecurityManagerServer'])[1]/preceding::th[2]</value>
      <webElementGuid>0a1cdec5-4ad3-46fb-97b9-2eda243809c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]</value>
      <webElementGuid>7ef5d9a3-103f-428e-84fc-c80f319fd231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = '
                    Message
                ' or . = '
                    Message
                ')]</value>
      <webElementGuid>518b892d-7f82-4167-87da-b60224f90422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
