<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>File</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bd6b8f2f-03bd-4354-8550-e3241a2d28d7</testSuiteGuid>
   <testCaseLink>
      <guid>cbe1b7dc-7028-4855-937f-7b19ec46816d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/File/TF01_Create directories</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dc3dd5f-0b53-46b2-b3c6-5351f35b68a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f13cd272-270e-4a5b-8d17-8cdb3a28d36c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4ea7038-9b95-4e72-96da-ee3abf3d0316</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e84f283-f24a-4945-9f63-1d44b4aeecd8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/File/TF02_Navigate directories</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a0cbb271-2261-4b42-a165-90ad37c08eb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/File/TF04_Rename Document</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13ac8b54-3bc8-4135-8c2d-f73532e39616</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8621f5d-0b18-48fd-93b4-32ecfeb70ef4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/File/TF03_Create Document</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cf4c8e8-a6c6-45be-b218-11f77ac530f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82ad6eee-10f5-4322-8dfe-c9465f1d4320</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/File/TF05_Delete Document</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>008d5f36-2840-47fc-997e-83b96a73e0bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa6227ef-d486-4479-923e-ae5ebe9bd52e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/File/TF06_Cat Document</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>546cc46a-041d-42eb-a849-10164a6cef54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/File/TF08_Download Document</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1e2e2b00-a7f0-4755-bc8c-8c5711328b37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/File/TF07_Copy Document</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e91abbc8-0ff2-4efd-90cd-6f04c4c6a4e8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
