<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ONLYOFFICE</name>
   <tag></tag>
   <elementGuidId>48317d32-9ac0-4121-8f69-477bd9d2874b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ONLYOFFICE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ONLYOFFICE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d95daf2b-9bd6-484e-b346-33f37bb7d506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ONLYOFFICE</value>
      <webElementGuid>71a05358-e56e-4a63-b171-26dca9bfa051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>267bbbfc-290f-4933-9c6f-4681e12717e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9639490-5f64-4319-9d92-7b49f818bec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>ONLYOFFICE</value>
      <webElementGuid>8d27f3fc-5bde-4196-9fe1-065e99623d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0831763f-ede6-492f-8ff8-99f04271eb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ONLYOFFICE</value>
      <webElementGuid>419c854a-0374-4b9c-8386-7d29454d216f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ONLYOFFICE&quot;)</value>
      <webElementGuid>b85744a4-d2fc-4f9d-81d9-c8aa665100ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ONLYOFFICE']</value>
      <webElementGuid>7c7bbd95-b533-4858-8bfc-a868048d0fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pref-content']/div[3]/div[3]/div/input</value>
      <webElementGuid>220f4b2b-d8fe-420b-b56f-f34b40cee8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OnlyOffice URL'])[1]/following::input[1]</value>
      <webElementGuid>c60907ee-f456-458d-856d-5606285e4ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MS_OFFICE'])[4]/following::input[1]</value>
      <webElementGuid>8fa41661-19bc-457e-a1d1-23d393bf7db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WOPI URL'])[1]/preceding::input[1]</value>
      <webElementGuid>229553a4-bb94-4ce8-893a-cb56ac3f6de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WOPI'])[5]/preceding::input[1]</value>
      <webElementGuid>a8404917-b456-4925-8165-d2b511c36ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>77371467-818c-4982-a7ce-f681a13b3508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ONLYOFFICE' and @type = 'text' and (text() = 'ONLYOFFICE' or . = 'ONLYOFFICE')]</value>
      <webElementGuid>05154f92-cae6-43d6-bab9-e1982b3a72f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
