<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Maximum validity (days)</name>
   <tag></tag>
   <elementGuidId>2ea812a2-98ba-4d98-a54c-f755eed16f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file_link.validity.maximum']/ancestor::div[contains(@class,'form-group')][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#file\.link\.validity\.maximum</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ea812a2-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
</WebElementEntity>
