<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Maximum validity (value)</name>
   <tag></tag>
   <elementGuidId>61f5615c-5419-4ff2-b3d6-16c5777a06b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file_link.validity.maximum']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#file\.link\.validity\.maximum</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61f5615c-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file_link.validity.maximum</value>
      <webElementGuid>61f5615c-0001-0001-0001-000000000002</webElementGuid>
   </webElementProperties>
</WebElementEntity>
