<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Security_Configuration</name>
   <tag></tag>
   <elementGuidId>91fc0756-e6aa-41c4-98e1-95a27edb6153</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button-security']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-security</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91fc0756-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-security</value>
      <webElementGuid>91fc0756-0001-0001-0001-000000000002</webElementGuid>
   </webElementProperties>
</WebElementEntity>
