<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Createlink</name>
   <tag></tag>
   <elementGuidId>c0ad62b2-49eb-4b50-acc8-8e8bf430ca73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#share_create_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a/span[@data-tooltip='tooltip_share'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e1816da-8452-4473-8948-11075c84b7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>share_create_link</value>
      <webElementGuid>95408aff-ea05-4bdf-a6c2-78a0a937de01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ecfba00f-04f8-4181-9200-127fa08177c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-left</value>
      <webElementGuid>6d648938-81a8-42d4-b8e1-7529b674ccaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Create link
                </value>
      <webElementGuid>7244482d-af90-4593-b916-1196889843ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share_create_link&quot;)</value>
      <webElementGuid>58895230-a0e4-49b3-8b5a-291115bac6a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
