<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delete</name>
   <tag></tag>
   <elementGuidId>407c997a-8a88-484c-bad6-faf66e55c902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//thead[@id='files_select_header']/tr/th[3]/div[2]/a[6]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pica-table-selection-multi.files-ui-delete > span.pica-glyph.glyphicons.glyphicons-bin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b42c123c-1f47-49c3-8c00-04cc6faa3511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-glyph glyphicons glyphicons-bin</value>
      <webElementGuid>d32785d3-8126-4e82-909a-ac481c43dee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;files_select_header&quot;)/tr[1]/th[@class=&quot;text-right&quot;]/div[@class=&quot;pica-table-selection-context pica-inline hidden-xs text-right&quot;]/a[@class=&quot;pica-table-selection-multi files-ui-delete&quot;]/span[@class=&quot;pica-glyph glyphicons glyphicons-bin&quot;]</value>
      <webElementGuid>615974be-bba2-476d-b520-cbcb6e1c07b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//thead[@id='files_select_header']/tr/th[3]/div[2]/a[6]/span</value>
      <webElementGuid>71874483-8c6f-40f5-9d78-95b6ec437fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/span</value>
      <webElementGuid>74da74ff-b55f-4ed9-842b-83cda491f420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
