<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delete</name>
   <tag></tag>
   <elementGuidId>407c997a-8a88-484c-bad6-faf66e55c902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div/div/main/div[1]/table/thead[1]/tr/th[3]/div[2]/a[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pica-table-selection-multi.files-ui-delete > span.pica-glyph.glyphicons.glyphicons-bin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd6866a5-7e9d-4a2e-adff-7a5860150207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-glyph glyphicons glyphicons-bin</value>
      <webElementGuid>34df8af3-3089-404a-9ced-133b2deb2849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;files_select_header&quot;)/tr[1]/th[@class=&quot;text-right&quot;]/div[@class=&quot;pica-table-selection-context pica-inline hidden-xs text-right&quot;]/a[@class=&quot;pica-table-selection-multi files-ui-delete&quot;]/span[@class=&quot;pica-glyph glyphicons glyphicons-bin&quot;]</value>
      <webElementGuid>f01740c0-ad63-4fca-84e6-1ee0e01eec5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//thead[@id='files_select_header']/tr/th[3]/div[2]/a[6]/span</value>
      <webElementGuid>35ab6236-705c-476f-8b9e-b0bb3d6948b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/span</value>
      <webElementGuid>ca1a8973-074f-4233-b6ac-ab16b4553802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
