<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>account_emal_forlinx</name>
   <tag></tag>
   <elementGuidId>9df52dd0-0199-4caf-9c92-0d45464cc415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pica-taginput-div.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[4]/div/div/div[2]/div[1]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>38afb793-b186-4ad2-8c69-acb5824d2884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-taginput-div form-control</value>
      <webElementGuid>74d38bcb-657b-497f-baa6-fb3161209b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share_taginput&quot;)/div[@class=&quot;pica-taginput-div form-control&quot;]</value>
      <webElementGuid>6af45074-1811-44b4-b28f-e9e5777838ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='share_taginput']/div</value>
      <webElementGuid>9ff90364-ee38-42f8-9e17-414320c7335b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite users and groups or create a link and share it:'])[1]/following::div[2]</value>
      <webElementGuid>e5bf225b-ccc7-4e4b-940e-8cd74b76f9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Members &amp; Share: Folder_10_déc._2024_07_44_19'])[1]/following::div[3]</value>
      <webElementGuid>0e2b5daf-157d-4561-8faa-6cf4b53d12ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Can read and write'])[1]/preceding::div[1]</value>
      <webElementGuid>38a4923c-f774-4ad3-9724-c51ca4073f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Can read'])[1]/preceding::div[1]</value>
      <webElementGuid>fce8b2ae-f192-4d94-ac84-14caebffa653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div</value>
      <webElementGuid>30a80830-72ac-43dd-b758-a8e73432cd56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
