<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Editing_button</name>
   <tag></tag>
   <elementGuidId>e19a91a3-9729-4838-b6de-4b92dead755d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div/div/div[1]/div/div[1]/div[2]/section/section[2]/div[3]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>9e060336-847f-4edb-9300-d5baafbc7b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1732459570737</value>
      <webElementGuid>75156f97-9b3b-49fb-8b03-c050b0a7cfbb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
