<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Disable Download (View only)</name>
   <tag></tag>
   <elementGuidId>b274ef2c-cc78-4cfa-8637-49ba7fe1fe44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[10]/div/div/div[2]/div[5]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pica_link_max_downloads</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f917e1a-82d0-4b3e-af2e-87f19b4b0623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_link_max_downloads</value>
      <webElementGuid>42478b16-a03d-4ebc-b96c-f5debbc57c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a2a1f429-08bc-4acf-8e2a-e961f9efe58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>313d4ef0-d898-4315-b8b7-1845de4e281e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>312c4e1b-5643-4b5d-8a75-eb75e98b932d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_maximum_downloads</value>
      <webElementGuid>9fda5d11-ae1f-47c2-bace-1a4ae883a749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Max allowed downloads</value>
      <webElementGuid>96028d0f-5733-4583-93d4-a82e978f2937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>424efe1c-c311-4433-a89c-32404ffdbf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_link_max_downloads&quot;)</value>
      <webElementGuid>4c47f769-63e0-4c94-bfeb-2e2aeb2250da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_link_max_downloads']</value>
      <webElementGuid>12075522-7755-4373-9d86-523560c0654b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_link_dialog']/div/div/div[2]/div[5]/input</value>
      <webElementGuid>3ce1124f-cd61-46e9-846f-c688cee3041f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>1fddd121-10f3-4951-9ade-e4d7b05d04fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_link_max_downloads' and @type = 'number' and @placeholder = 'Max allowed downloads']</value>
      <webElementGuid>150f5a94-21f4-4952-ab1c-d8bcee23073a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
