<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Disable Download (View only)</name>
   <tag></tag>
   <elementGuidId>047b1fae-2ae2-400d-9bf1-806ba51756bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_link_disable_download_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[10]/div/div/div[2]/div[4]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>52919870-6868-4b52-a80c-e9133df5f299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>pica_checkbox</value>
      <webElementGuid>d524985e-ca58-42ff-b55c-b3a782241d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6e5945e3-8bc7-47ef-bca6-427aee07da23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_link_disable_download_label</value>
      <webElementGuid>916b2f40-642c-4d90-9266-27922eeed437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Disable Download (View only)
                    </value>
      <webElementGuid>56eca537-cbbc-4c57-b3c9-26083038bc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_link_disable_download_label&quot;)</value>
      <webElementGuid>34991f3b-9b42-4a3c-9605-fdcde5c6054b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='pica_link_disable_download_label']</value>
      <webElementGuid>54109caf-0be4-4592-9d2a-e2c02cd1c519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_link_dialog']/div/div/div[2]/div[4]/label</value>
      <webElementGuid>f3a51672-5f7a-4ef4-9668-04c716e4782d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Can read and write'])[3]/following::label[1]</value>
      <webElementGuid>a7cbb9e1-d296-4ad5-903e-d863b715fa65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Can read'])[2]/following::label[2]</value>
      <webElementGuid>dee9f951-a4d0-44db-a9af-8b669150bdd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::label[1]</value>
      <webElementGuid>03a3e688-3ee5-41ae-9882-cbfdfc4e8cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label</value>
      <webElementGuid>717b6684-7127-434b-a579-2d73ff45ee3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'pica_link_disable_download_label' and (text() = '
                        Disable Download (View only)
                    ' or . = '
                        Disable Download (View only)
                    ')]</value>
      <webElementGuid>4d8bee0b-e072-4f0f-abd9-f202b5751ec4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
