<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_wpath</name>
   <tag></tag>
   <elementGuidId>dfc7b2a8-cb5b-47c7-995c-f10b3d33cfbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div/div/main/div[1]/div/div/section/article/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.filetypes.filetypes-docx.pica-glyph-color.text-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dd2ff1c2-0682-4d0e-a5ad-90ba7630bbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filetypes filetypes-docx pica-glyph-color text-info</value>
      <webElementGuid>aef3672c-ef5a-4497-95e0-e88dba8bb49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>tooltip_file</value>
      <webElementGuid>87c02b1c-5d24-4242-8cfe-242a22bb318a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>558c2285-ae79-40eb-a039-bebdc8d5f6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Doc_num_6882.docx (3.7 KB) modified by ogcgwblv@yoemail.com</value>
      <webElementGuid>269992d7-6a80-4ea0-8b22-bd77c4270963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip603898</value>
      <webElementGuid>73089f18-bc04-4820-9720-846b9b47881d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_content&quot;)/div[@class=&quot;pica-content-scroll-with-header&quot;]/ul[@class=&quot;pica-timeline pica-timeline-centered&quot;]/li[@class=&quot;pica-timeline-item&quot;]/div[@class=&quot;pica-timeline-content&quot;]/div[@class=&quot;pica-timeline-files&quot;]/span[@class=&quot;filetypes filetypes-docx pica-glyph-color text-info&quot;]</value>
      <webElementGuid>d4734b87-cec2-43f7-a61c-8882fd5eae29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div[2]/ul/li/div[3]/div/span</value>
      <webElementGuid>44f5c240-6fe8-4a85-92f6-e44ad2a2159e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>4d60dcee-847d-42d6-8554-9b58c76cb5bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
