<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_wpath</name>
   <tag></tag>
   <elementGuidId>dfc7b2a8-cb5b-47c7-995c-f10b3d33cfbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.filetypes.filetypes-docx.pica-glyph-color.text-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_content']/div[2]/ul/li/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5e8affd7-3f15-4a8a-a405-b7fe5982036e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filetypes filetypes-docx pica-glyph-color text-info</value>
      <webElementGuid>a526d0a8-a971-4e4b-8ec1-01788d58dd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>tooltip_file</value>
      <webElementGuid>b739d003-f532-45ed-b58f-898a99c35ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>7d78a3bd-c816-4139-bd1b-b8642e185257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Doc_num_6882.docx (3.7 KB) modified by ogcgwblv@yoemail.com</value>
      <webElementGuid>38b8c649-d9b8-40f5-ba3f-73c4a2aaa6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip603898</value>
      <webElementGuid>88d568e0-c6a0-44d3-9883-b98be5c858c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_content&quot;)/div[@class=&quot;pica-content-scroll-with-header&quot;]/ul[@class=&quot;pica-timeline pica-timeline-centered&quot;]/li[@class=&quot;pica-timeline-item&quot;]/div[@class=&quot;pica-timeline-content&quot;]/div[@class=&quot;pica-timeline-files&quot;]/span[@class=&quot;filetypes filetypes-docx pica-glyph-color text-info&quot;]</value>
      <webElementGuid>8575683c-2aeb-428c-9953-1ae8fd11dd90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div[2]/ul/li/div[3]/div/span</value>
      <webElementGuid>08e6e331-4931-4c7d-9cf5-536d2c93f114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>de74ee1e-cb97-4bfc-982f-b1cc63ca843f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
