<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Name_folder_in_news_part</name>
   <tag></tag>
   <elementGuidId>fde81c24-b5b7-4a09-aa5b-c3963ba90e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pica-action-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_content']/div[2]/ul/li/div[3]/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3587b9b-574f-4ea1-9a66-85b09a800935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-action-link</value>
      <webElementGuid>abb44221-08b4-414f-b8e8-0dcfdae96ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Folder_14_juin_2025_05_55_22</value>
      <webElementGuid>3d4f9a63-64e5-43af-9170-e46d9a55863a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_content&quot;)/div[@class=&quot;pica-content-scroll-with-header&quot;]/ul[@class=&quot;pica-timeline pica-timeline-centered&quot;]/li[@class=&quot;pica-timeline-item&quot;]/div[@class=&quot;pica-timeline-content&quot;]/h3[1]/a[@class=&quot;pica-action-link&quot;]</value>
      <webElementGuid>682df2ba-262c-4bcb-9941-007c45d2359e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div[2]/ul/li/div[3]/h3/a</value>
      <webElementGuid>fb24a3e1-f29f-4a5b-908a-111d6ca64124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Folder_14_juin_2025_05_55_22')]</value>
      <webElementGuid>b291e033-84ff-47ff-94fe-cb095b6b5b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deleted'])[1]/following::a[1]</value>
      <webElementGuid>5ef5dd7d-eeec-4e8e-9b08-50650d2b16cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updated'])[1]/following::a[1]</value>
      <webElementGuid>f454c7ad-cf3e-4f06-b338-0d8f2b093610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/preceding::a[1]</value>
      <webElementGuid>69579996-191e-4c5b-9694-53d80f238ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imprint'])[1]/preceding::a[2]</value>
      <webElementGuid>646b3eb6-242e-41fd-9378-6e470c3800dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Folder_14_juin_2025_05_55_22']/parent::*</value>
      <webElementGuid>ceee7252-d49b-4593-aba2-c3de7c585021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>fae6cc50-26e5-4c59-8fee-1dd1119402a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Folder_14_juin_2025_05_55_22' or . = 'Folder_14_juin_2025_05_55_22')]</value>
      <webElementGuid>ac988c6e-6bfb-4618-be0b-46da51c8fd6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
