<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>folders</name>
   <tag></tag>
   <elementGuidId>297abdf8-1ced-4d64-b941-215bd97b4056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='folders-menu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#folders-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>folders-menu</value>
      <webElementGuid>297abdf8-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
</WebElementEntity>
