<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create_uploadform_heading</name>
   <tag></tag>
   <elementGuidId>142b1bcc-95c8-46ed-90e6-e143841eb8df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_uploadform_heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[17]/div/div/div[2]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e28beb6-79d0-4f95-bb09-a9ffbaa12b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_uploadform_heading</value>
      <webElementGuid>bd25078b-7200-4987-8e92-d5ef3bc6e653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>155b627f-7726-4a8a-8b15-3769a03e9122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22920a19-44ee-42b1-862f-1023740c04d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_heading</value>
      <webElementGuid>e6ea446a-08e9-4950-af49-9b6207ff6e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Heading</value>
      <webElementGuid>f7eec68c-e15f-4e0a-9b64-199cc6828572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_uploadform_heading&quot;)</value>
      <webElementGuid>92cb7fe2-44d7-4995-aa76-5b2198505fc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_uploadform_heading']</value>
      <webElementGuid>7fe13914-d11e-4f1b-89c8-66df1b34cbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_uploadform_dialog']/div/div/div[2]/div/input</value>
      <webElementGuid>6e7c5e72-93e8-4daf-9ef5-7d04453351e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/div[2]/div/input</value>
      <webElementGuid>bc0b5955-8a93-4aee-a037-f61f501f86e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_uploadform_heading' and @type = 'text' and @placeholder = 'Heading']</value>
      <webElementGuid>92074a7d-f62d-44b0-a3a4-47b2599ba3c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
