<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GeneralLogging, licensing, accounts, fe_b8efaf</name>
   <tag></tag>
   <elementGuidId>6c76edae-7f31-43e3-a3ac-3d2f10dcac7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_content']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pica-flex.pica-content-scroll</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a0ed4cbb-d944-4319-9e3a-264a79dffd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-flex pica-content-scroll</value>
      <webElementGuid>b700d983-e004-4662-be4e-405742285d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GeneralLogging, licensing, accounts, federation ...ConfigureAuthenticationDatabase, LDAP, SAML ...ConfigureStorageStorage directories, encryption, recylce bin ...ConfigureCustomizationsDownload and information URLs ...ConfigureNetworkHostname, server name, network ID ...ConfigureSecurityFolder security, user security, organization security ...ConfigureMailSMTP server parameters, SMTP header ...ConfigureWebOpen files in web, web features ...Configure</value>
      <webElementGuid>b44a66b3-d4c2-4e68-905c-0362b0a1b817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_content&quot;)/div[@class=&quot;pica-flex pica-content-scroll&quot;]</value>
      <webElementGuid>4b473093-c552-4b0a-a3f9-794b3d70304a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div</value>
      <webElementGuid>5c0ee687-59e8-4311-9a58-63143f5fc962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div</value>
      <webElementGuid>c41fb8dc-789d-49ce-a3f5-7bc8c465a8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'GeneralLogging, licensing, accounts, federation ...ConfigureAuthenticationDatabase, LDAP, SAML ...ConfigureStorageStorage directories, encryption, recylce bin ...ConfigureCustomizationsDownload and information URLs ...ConfigureNetworkHostname, server name, network ID ...ConfigureSecurityFolder security, user security, organization security ...ConfigureMailSMTP server parameters, SMTP header ...ConfigureWebOpen files in web, web features ...Configure' or . = 'GeneralLogging, licensing, accounts, federation ...ConfigureAuthenticationDatabase, LDAP, SAML ...ConfigureStorageStorage directories, encryption, recylce bin ...ConfigureCustomizationsDownload and information URLs ...ConfigureNetworkHostname, server name, network ID ...ConfigureSecurityFolder security, user security, organization security ...ConfigureMailSMTP server parameters, SMTP header ...ConfigureWebOpen files in web, web features ...Configure')]</value>
      <webElementGuid>9e55b679-9098-4f40-8c27-2677f06bb3db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
