<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AwN1QCnmB</name>
   <tag></tag>
   <elementGuidId>dd6d8fdf-cefd-4f11-9389-211e11cd4b3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Object_552465618 > td.pica-overflow > a.pica-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='Object_552465618']/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6557a121-2000-4ffd-8f2d-62171545698d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-name</value>
      <webElementGuid>e5fbd78c-e27a-4f6b-8149-a3b5db7b12c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>download/MkNQekFFQlZMU3B0MTc2S3dRd0Vv</value>
      <webElementGuid>7cb2d27f-f3bb-4e24-9b9b-b632157720bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-serial</name>
      <type>Main</type>
      <value>{&quot;_flags&quot;:1,&quot;_oid&quot;:&quot;2CPzAEBVLSpt176KwQwEo&quot;,&quot;_name&quot;:&quot;AwN1QCnmB&quot;,&quot;_intName&quot;:&quot;AwN1QCnmB&quot;,&quot;_size&quot;:0,&quot;_archiveSize&quot;:0,&quot;_resUrl&quot;:&quot;/files/MkNQekFFQlZMU3B0MTc2S3dRd0Vv&quot;,&quot;_openUrl&quot;:null,&quot;_basePath&quot;:&quot;/Users/mac/PowerFolders/admin/AwN1QCnmB&quot;,&quot;_path&quot;:&quot;&quot;,&quot;_folderId&quot;:&quot;2CPzAEBVLSpt176KwQwEo&quot;,&quot;_accountsCount&quot;:0,&quot;_groupsCount&quot;:0,&quot;_versions&quot;:25,&quot;_ownerOid&quot;:0,&quot;_isBlocked&quot;:false,&quot;_modifiedDate&quot;:-1,&quot;_modifiedDateMS&quot;:-1,&quot;_modifiedOn&quot;:&quot;&quot;,&quot;_modifiedBy&quot;:null,&quot;_modifiedByAccount&quot;:null,&quot;_version&quot;:0,&quot;_publicUrl&quot;:&quot;/public?folderID=MkNQekFFQlZMU3B0MTc2S3dRd0Vv&quot;,&quot;_permission&quot;:8,&quot;_publicPermission&quot;:1,&quot;_folderIdEnc&quot;:&quot;MkNQekFFQlZMU3B0MTc2S3dRd0Vv&quot;,&quot;_url&quot;:&quot;MkNQekFFQlZMU3B0MTc2S3dRd0Vv&quot;}</value>
      <webElementGuid>507ed0b6-24d7-4fe0-9db8-30a2e3410d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AwN1QCnmB</value>
      <webElementGuid>ff3cc01a-252c-43bf-a56c-4c0af6a34573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_552465618&quot;)/td[@class=&quot;pica-overflow&quot;]/a[@class=&quot;pica-name&quot;]</value>
      <webElementGuid>9faf075f-dc3a-41eb-b31a-eb4285812c27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_552465618']/td[2]/a</value>
      <webElementGuid>d6380bff-076f-4710-a07a-b22a38647912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AwN1QCnmB')]</value>
      <webElementGuid>76dc2baa-7304-487a-a392-f35adfe201aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No members'])[4]/following::a[2]</value>
      <webElementGuid>ea148cdc-7502-434a-a561-7a8a4a47731f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[4]/following::a[3]</value>
      <webElementGuid>0ce6d4e5-6939-4aa4-961f-e5ff03d09686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[5]/preceding::a[1]</value>
      <webElementGuid>18ee978a-04b3-4a57-bd2b-a11007fc30d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No members'])[5]/preceding::a[1]</value>
      <webElementGuid>9f7ee2ca-7209-4c52-87ba-337225a730d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AwN1QCnmB']/parent::*</value>
      <webElementGuid>b53216c6-f4bc-474b-8cad-780cfc50d212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'download/MkNQekFFQlZMU3B0MTc2S3dRd0Vv')]</value>
      <webElementGuid>012d221c-9fdb-4d6d-87b6-5d15ea004204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/a</value>
      <webElementGuid>90b00196-ed38-4949-b6dd-828e7a9d5359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'download/MkNQekFFQlZMU3B0MTc2S3dRd0Vv' and (text() = 'AwN1QCnmB' or . = 'AwN1QCnmB')]</value>
      <webElementGuid>07a30aaa-30c6-4271-b0e9-e7d38eef415f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
