<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Avatar</name>
   <tag></tag>
   <elementGuidId>7e4c100d-9fe0-4443-b32f-411f2c0ed0c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.pica-hide-on-create.hidden-xs > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='pica_group_nav']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24653aae-90a6-4f35-8b4b-d0039de9df23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Avatar</value>
      <webElementGuid>2bdac4c6-601e-4953-ba21-9e36745df81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_group_nav&quot;)/li[@class=&quot;pica-hide-on-create hidden-xs&quot;]/a[1]</value>
      <webElementGuid>67705b4e-97d7-42cb-b77d-1f13ca71fa27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pica_group_nav']/li[2]/a</value>
      <webElementGuid>2f522995-d0a7-456d-9937-1604b2d71fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group'])[1]/following::a[1]</value>
      <webElementGuid>ef166473-7cbf-4656-a02c-8dccca8088df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Group'])[1]/following::a[2]</value>
      <webElementGuid>b8249f2e-8456-4d6a-a90d-a3003f5cafae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folders'])[3]/preceding::a[1]</value>
      <webElementGuid>82492332-f9f2-471c-8f46-7fe4c20f6c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>78e04781-de3e-4e19-be6b-f1ade8fa1d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Avatar' or . = 'Avatar')]</value>
      <webElementGuid>7404b52d-bf71-46a1-84f8-f78dbf01e53d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
