<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Organizations_pica-glyph-huge pica-bor_50d4f7</name>
   <tag></tag>
   <elementGuidId>59092657-52cb-48c5-943c-4e6703b899c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pica-glyph-huge.pica-border.glyphicons.glyphicons-group</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_group_dialog']/div/div/div[2]/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7731f7ef-f9df-4406-848e-4673f088c367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-glyph-huge pica-border glyphicons glyphicons-group</value>
      <webElementGuid>d7b5dae5-2491-4d19-b1cd-d1f437e1e62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_group_dialog&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;pica-nav-tab&quot;]/div[@class=&quot;form-group form-inline pica-table&quot;]/div[1]/span[@class=&quot;pica-glyph-huge pica-border glyphicons glyphicons-group&quot;]</value>
      <webElementGuid>dd0b3c5c-4fdf-4caf-8554-b24d03efd8f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_group_dialog']/div/div/div[2]/div[2]/div/div/span</value>
      <webElementGuid>a418f95c-21a6-459d-8e7e-fbbefd6ff56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span</value>
      <webElementGuid>e06eb97c-bf7f-4860-b720-41e00a339d37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
