<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Nothing to show</name>
   <tag></tag>
   <elementGuidId>37766e76-5104-494a-98f2-3d03a2361234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#upload_table > tbody > tr.pica-table-empty.warning > td.text-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='upload_table']/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c9884ab6-7014-44c5-9742-2eb9b949e87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>d6d30609-7206-4e39-a114-22730f54e682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2290c209-2d93-43b6-89a9-3d73405556f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nothing to show</value>
      <webElementGuid>01567896-da0f-4a5a-862e-e0642b633cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upload_table&quot;)/tbody[1]/tr[@class=&quot;pica-table-empty warning&quot;]/td[@class=&quot;text-center&quot;]</value>
      <webElementGuid>341ce504-4a2d-459d-859f-01a9dc49c87a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='upload_table']/tbody/tr/td</value>
      <webElementGuid>4a3b2d5e-ca7b-4d46-b1d4-008110f9de58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select avatar file for upload'])[1]/following::td[1]</value>
      <webElementGuid>1f2a24fc-1882-4f29-bf2d-a1c824b46937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avatar'])[3]/following::td[1]</value>
      <webElementGuid>09d70f6e-1205-49d0-b91b-d1563fed2c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add file'])[1]/preceding::td[1]</value>
      <webElementGuid>1162f658-4cc0-4aa0-b3f7-1788dc2c5092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/table/tbody/tr/td</value>
      <webElementGuid>d8d5d277-8135-4bb3-8d96-13a1eb1738f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Nothing to show' or . = 'Nothing to show')]</value>
      <webElementGuid>ad3956b9-2741-4f2c-b969-081313f3a85c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
