<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change</name>
   <tag></tag>
   <elementGuidId>70e3a3de-4541-460f-be13-6ec44379fa3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_organization_avatar_change</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pica_organization_avatar_change']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6cc8775-2a6f-481b-b53d-384ac01268bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_organization_avatar_change</value>
      <webElementGuid>68d05908-7115-447f-85cb-ae771747e113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block btn-default</value>
      <webElementGuid>0b6c8ffe-013c-4a12-934f-58c8210c0856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Change
                                </value>
      <webElementGuid>bc87fbbb-69b8-4017-b358-5cca16d12322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_organization_avatar_change&quot;)</value>
      <webElementGuid>9ab8de65-cb72-4f16-add3-7b09d7d404f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pica_organization_avatar_change']</value>
      <webElementGuid>97d1e6bc-a1db-4313-876f-6e4b8f8fda81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_organization_dialog']/div/div/div[2]/div[2]/div/div[2]/div/a</value>
      <webElementGuid>2ab2b53e-5ca1-4203-a1c4-2405e311efca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups'])[3]/following::a[1]</value>
      <webElementGuid>48e8460a-0cdc-41e7-a4d2-0e7c931f2a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Members'])[2]/following::a[2]</value>
      <webElementGuid>ae3f5ba7-bb90-4409-b752-ece4b67ed946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::a[1]</value>
      <webElementGuid>53d1e97b-9212-4db8-84bb-c4976f689dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/a</value>
      <webElementGuid>5a4ebd42-8d74-4e36-8c5e-95cb0d27dbdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pica_organization_avatar_change' and (text() = '
                                    Change
                                ' or . = '
                                    Change
                                ')]</value>
      <webElementGuid>54c88400-5df0-40ad-9bb0-b3233710a0b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
