<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonFolder</name>
   <tag></tag>
   <elementGuidId>e656486f-3ff4-4a22-a754-cbdc447e47af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a/LANG[@name='label_folders'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
