<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_folder</name>
   <tag></tag>
   <elementGuidId>50c03635-04bb-43b4-ab38-3c64c1b5a935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_account_folders']//a[contains(@class,'pica-inputlist-manage')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pica_account_folders a.pica-inputlist-manage</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>50c03635-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-inputlist-manage</value>
      <webElementGuid>50c03635-0001-0001-0001-000000000002</webElementGuid>
   </webElementProperties>
</WebElementEntity>
