<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SuccessAccountDeleteMessage</name>
   <tag></tag>
   <elementGuidId>9d6ed72a-36a6-42dc-8905-e891f0c412a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pica-notification-box.alert.alert-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notification_1205047558']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f39c1f9e-3d6d-4154-a2dd-8ee86788c607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-notification-box alert alert-info</value>
      <webElementGuid>970cc18b-26fb-4c99-99cc-829c01404272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>b5b06702-e577-4c84-acdd-6fd22393f29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account deleted×</value>
      <webElementGuid>dae97a9d-3021-4a24-8e63-f7ffbafbbfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification_1205047558&quot;)/div[@class=&quot;pica-notification-box alert alert-info&quot;]</value>
      <webElementGuid>5abc8421-2e27-4edb-bf50-2b4012163bb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notification_1205047558']/div</value>
      <webElementGuid>affc81d0-83b1-4122-91d6-607e122efb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[2]</value>
      <webElementGuid>1fbcce8b-f07b-4d20-87a9-8127c068a339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>b56340dc-c21d-4f3e-a61d-bd8e91d4e819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Account deleted×' or . = 'Account deleted×')]</value>
      <webElementGuid>cd0d4374-cc1d-401d-b041-b715f13e64cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
