<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyManagePage</name>
   <tag></tag>
   <elementGuidId>305cf6d8-d2bd-4dfe-b5e2-9353f9de194d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//h4[normalize-space()='Settings'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
