<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_recycle_bin</name>
   <tag></tag>
   <elementGuidId>478261a5-783e-4999-b450-0e4ff0cf69e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;label_recycle_bin&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='label_recycle_bin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>6d55f719-5668-445a-a4b9-f6f9d96270b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-hidden-on-small text-center</value>
      <webElementGuid>e146a7ef-3902-4156-98fb-468c322ed2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label_recycle_bin</value>
      <webElementGuid>766c1da7-9b62-438c-9721-c1cd4c91d038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-plural</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>599fa154-d3f1-4808-b414-ec30d2f0316b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recycle Bin</value>
      <webElementGuid>fdbe2fbd-3458-4903-ac9c-bf6cb863897d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_menu&quot;)/table[1]/tbody[1]/tr[4]/td[@class=&quot;text-center&quot;]/a[1]/lang[@class=&quot;pica-hidden-on-small text-center&quot;]</value>
      <webElementGuid>f2ff6b3f-6e10-4cad-845a-9f8ca161a4b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='label_recycle_bin']</value>
      <webElementGuid>bb84cdc1-7a35-497c-b395-4aa4ef40e628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_menu']/table/tbody/tr[4]/td/a/lang</value>
      <webElementGuid>2a6e0dd9-9db1-4d53-a55d-65b9df088dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folders'])[1]/following::lang[1]</value>
      <webElementGuid>65103fb9-608f-40de-babe-a4d58c3f93d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::lang[2]</value>
      <webElementGuid>8b9ce1de-3fe5-4dfa-aa04-793ab3611a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Links'])[1]/preceding::lang[1]</value>
      <webElementGuid>de252e39-0cb5-4620-a885-8b599fa49d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[1]/preceding::lang[2]</value>
      <webElementGuid>d6ddc2f0-efd7-498c-8de7-71eace0a833a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recycle Bin']/parent::*</value>
      <webElementGuid>40727950-eccd-41b3-a33c-296a5077be3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/a/lang</value>
      <webElementGuid>63ae1e7a-2ffb-4362-a4f2-9751e386b3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'label_recycle_bin' and (text() = 'Recycle Bin' or . = 'Recycle Bin')]</value>
      <webElementGuid>2ecbe367-d7af-480e-9d8b-3020211d6ed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
