<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>change_group</name>
   <tag></tag>
   <elementGuidId>3dada896-995c-414a-8ff8-1e1cff9d6197</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.text-center.pica-icon-column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b96e62ae-3a2e-4a31-a987-f2db48559c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center pica-icon-column</value>
      <webElementGuid>3cae175d-277a-46fc-842f-7ec79f183625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_1342206080&quot;)/td[@class=&quot;text-center pica-icon-column&quot;]</value>
      <webElementGuid>4dddc455-22f6-41a7-9939-df06dc8caa14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_1342206080']/td</value>
      <webElementGuid>f37acb49-3840-4ba9-9e7b-736d68eeec96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[1]/following::td[1]</value>
      <webElementGuid>d9965d9e-eb5e-4aba-ad43-7627f0b20f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permissions'])[1]/following::td[1]</value>
      <webElementGuid>39bed7cc-6a12-4cf5-83a7-06d73d47851e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group_test0769'])[2]/preceding::td[1]</value>
      <webElementGuid>125adbe2-edb9-4c18-b119-c4af0f60e193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::td[4]</value>
      <webElementGuid>9de31b70-9dfb-4e40-b995-1bba111f66fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td</value>
      <webElementGuid>8287cfe1-bc68-4cff-9c47-aecfc4c03208</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
