<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search the group name</name>
   <tag></tag>
   <elementGuidId>73dc91b0-f8cf-4872-88a6-3da96ff290ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_action_search']/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pica_action_search_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acf233ba-cd70-4e97-a729-cb61d5c19619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_action_search_input</value>
      <webElementGuid>faf504b9-2e69-43b3-a3c2-fc668b9c68a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e95743d0-5026-41ed-8f17-99b19d4fbb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_search</value>
      <webElementGuid>2b7eca17-80af-40d3-b035-e0d451bf0ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>search input</value>
      <webElementGuid>61e1be98-ecba-4d30-a0cf-55a87d25d292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter search term</value>
      <webElementGuid>060546c3-3da2-4a9c-a3f3-4e655b454289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_action_search_input&quot;)</value>
      <webElementGuid>1ae93b61-5130-4a6d-a424-35c56e2610c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_action_search_input']</value>
      <webElementGuid>ffe0d9b5-9069-4f8b-a6a0-ff0a4e669b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_action_search']/input</value>
      <webElementGuid>0818e1de-7603-42d8-a15b-4c2775e847aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6e632db8-8f68-4621-87d7-5b4f3ad04ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_action_search_input' and @type = 'text' and @placeholder = 'Enter search term']</value>
      <webElementGuid>164df774-a67d-4c4b-bb32-ce502caa22b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
