<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Organization_text-center pica-icon-column</name>
   <tag></tag>
   <elementGuidId>8bd65e6f-2508-4e70-8550-c4f9c11ee582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.text-center.pica-icon-column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='Object_1342206080']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1a476c13-6021-4cd1-87e3-38d64a5c15af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center pica-icon-column</value>
      <webElementGuid>ebd48023-2a54-418a-9aa3-c79e01778fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_1342206080&quot;)/td[@class=&quot;text-center pica-icon-column&quot;]</value>
      <webElementGuid>6405cb2a-ea39-4d76-9428-8fc0a3b5ce3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_1342206080']/td</value>
      <webElementGuid>d74dcc04-3be2-4224-8777-85dc06eb49a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[1]/following::td[1]</value>
      <webElementGuid>4abff0b9-f092-420a-a864-cdbbed004b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permissions'])[1]/following::td[1]</value>
      <webElementGuid>d7364bf4-e803-4acc-9efc-eba03dfc3795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group_test0769'])[2]/preceding::td[1]</value>
      <webElementGuid>eca4be9d-de65-4aa2-97be-28c484722327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::td[4]</value>
      <webElementGuid>1c395343-f46e-41cc-9ceb-acc5f8da7d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td</value>
      <webElementGuid>4405a43a-0ed8-4379-8b35-1e84f2b09b91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
