<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CSS ng</name>
   <tag></tag>
   <elementGuidId>f19bee24-9eac-47d2-80f7-09ca7ff18188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pica-icon.pica-glyph.glyphicons.glyphicons-plus-sign</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='groups_create']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>17de38c2-aa41-4c69-8aea-e373081b90c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-icon pica-glyph glyphicons glyphicons-plus-sign</value>
      <webElementGuid>0dccef21-5dd8-4213-9f70-b91e55bd2c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groups_create&quot;)/span[@class=&quot;pica-icon pica-glyph glyphicons glyphicons-plus-sign&quot;]</value>
      <webElementGuid>06910151-8192-4d96-8c95-78bcc892288e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='groups_create']/span</value>
      <webElementGuid>bad8ac1c-fbbc-4504-9750-4c0b9f3dfd74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/a/span</value>
      <webElementGuid>b8e070b8-e283-41df-b471-5dc3fb12c2e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
