<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nothing to show_pica-taginput-input f_7978a7</name>
   <tag></tag>
   <elementGuidId>ed7da1c4-5be0-4051-82f3-04402538da29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_group_accounts > div.pica-inputlist-taginput.pica-taginput.form-group.input-group > div.pica-taginput-div.form-control > input.pica-taginput-input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa45864f-945f-4406-b979-e4c39c1ceb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>48c0ee18-297a-4d16-b495-2d4d3249fc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-taginput-input form-control</value>
      <webElementGuid>e7b995c5-c377-485c-b9b3-381db0341c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_add_account_by_name</value>
      <webElementGuid>6ee2e3e5-bd8d-4fe0-bcb2-3e62f41140ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>should-validate</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>76926f15-64c8-4494-bd16-adb5b93e8348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add an account by name</value>
      <webElementGuid>0d2a6edb-96ae-49fd-9643-e262b43d8bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_group_accounts&quot;)/div[@class=&quot;pica-inputlist-taginput pica-taginput form-group input-group&quot;]/div[@class=&quot;pica-taginput-div form-control&quot;]/input[@class=&quot;pica-taginput-input form-control&quot;]</value>
      <webElementGuid>ed93f9aa-b0e4-4411-adff-9f732c0e825d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='email']</value>
      <webElementGuid>0d65cfa8-7fb3-4c7f-9f9f-988ded03f4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_group_accounts']/div/div/input</value>
      <webElementGuid>2d58df91-aee4-4658-b924-11d19735effc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>e08d8fe2-b206-4e1f-b118-8ab5e9f39873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Add an account by name']</value>
      <webElementGuid>58a337cc-0fb8-4dc0-8fef-644c5e0d7da6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
