<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Accessibility Information</name>
   <tag></tag>
   <elementGuidId>5c5f8e54-c9cc-4e84-8ba6-a1a142197e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='heading-title-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#heading-title-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b9ce54f5-927b-4efb-ae12-81f14dd18858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>heading-title-text</value>
      <webElementGuid>dcd9bbea-6466-40c4-aba5-ce6cefaef370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_11c81c04 _k48pi7a9 _1e0c1nu9</value>
      <webElementGuid>461da343-1d39-4e79-92c4-2528b60dcef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accessibility Information</value>
      <webElementGuid>0dfa8e0f-7a3e-4f80-97cf-cc5fa4ff3443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heading-title-text&quot;)</value>
      <webElementGuid>feef4348-033d-48b5-8ec9-0546afa79291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='heading-title-text']</value>
      <webElementGuid>ebaaf6e9-d267-4ea1-b50a-fa0fc15fb393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='content-title-id']/h1</value>
      <webElementGuid>048e5464-3065-4db4-89d7-4c131013ca6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More actions'])[2]/following::h1[1]</value>
      <webElementGuid>28a1699a-347e-4a61-9b4c-2556bff33b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anonymous Boar'])[1]/following::h1[1]</value>
      <webElementGuid>da9071eb-12b9-4953-9c5a-dd6aa018f114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Ahmad Abdullah'])[1]/preceding::h1[1]</value>
      <webElementGuid>70eec5b7-c8d4-4c24-8fbf-1a6c80356877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a reaction'])[1]/preceding::h1[1]</value>
      <webElementGuid>91aa9f8a-8a5e-4442-ae93-2ecff99bfed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>629cd09f-cbf9-4eb3-b784-70fe88d873ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'heading-title-text' and (text() = 'Accessibility Information' or . = 'Accessibility Information')]</value>
      <webElementGuid>549d324c-1a23-4c7c-8ef0-0f040bd9b104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
