<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Secondary ("No") button of the generic confirmation dialog (#pica_confirmation_dialog). Dismisses the dialog without applying the pending interrupt/restore inheritance action.</description>
   <name>confirmation_dialog_cancel</name>
   <tag></tag>
   <elementGuidId>29b82566-b0c7-44d2-a36c-ef89d7ee5a4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_confirmation_dialog']//div[contains(@class,'modal-footer')]/button[contains(@class,'btn-secondary')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pica_confirmation_dialog .modal-footer button.btn-secondary</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29b82566-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-secondary</value>
      <webElementGuid>29b82566-0001-0001-0001-000000000002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>29b82566-0001-0001-0001-000000000003</webElementGuid>
   </webElementProperties>
</WebElementEntity>
