<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Body/description of the dedicated inheritance interrupt/restore dialog (#pica_inheritance_dialog, PFC-3613). Lang keys: dialog_body_interrupt_inheritance / dialog_body_restore_inheritance. Scoped to the first match ([1]) because the "affected holders" section title (#pica_inheritance_affected_title) further down in the same dialog also carries the pica-dialog-description class.</description>
   <name>inheritance_dialog_body</name>
   <tag></tag>
   <elementGuidId>7a1e2c40-3b5d-4e6a-9c8f-1a2b3c4d5e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='pica_inheritance_dialog']//h5[contains(@class,'pica-dialog-description')])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>7a1e2c40-0001-0001-0001-000000000003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-dialog-description</value>
      <webElementGuid>7a1e2c40-0001-0001-0001-000000000004</webElementGuid>
   </webElementProperties>
</WebElementEntity>
