<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create CSV File</name>
   <tag></tag>
   <elementGuidId>70b8d2ef-322d-43a9-9f77-7bd3a1333476</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//thead[3]/tr/th/div/ul/li[6]/a/lang</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>61df48ad-8b74-4988-9ed0-58a0f6b02032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>string_create</value>
      <webElementGuid>85da3a65-d537-438a-aa51-751fddc0860f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create CSV File</value>
      <webElementGuid>8a04155f-1d81-4d4d-9474-39c5d077fb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica-files-create-dropdown&quot;)/ul[@class=&quot;pica-arrow-left dropdown-menu&quot;]/li[@class=&quot;files-visible-only-other files-ui-create-doc&quot;]/a[1]/lang[1]</value>
      <webElementGuid>5d4ffd3b-9543-4099-8997-0d68fe49a479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//lang[@name='string_create'])[6]</value>
      <webElementGuid>3a0505cb-6f40-46ff-abea-aeb79d2f0ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica-files-create-dropdown']/ul/li[6]/a/lang</value>
      <webElementGuid>f0f6c744-9a44-4f51-9536-687299188da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Spreadsheet'])[1]/following::lang[1]</value>
      <webElementGuid>6181b51e-d880-417a-917a-10d87e6c2e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Text File'])[1]/following::lang[2]</value>
      <webElementGuid>5e0e666b-eaf4-4fd7-a095-ca15a60c5a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Presentation'])[1]/preceding::lang[1]</value>
      <webElementGuid>cc299fba-5cab-4661-a5b9-72a52943cf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload File'])[1]/preceding::lang[2]</value>
      <webElementGuid>231c2bde-4891-4bca-b070-b3ded5a1efd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create CSV File']/parent::*</value>
      <webElementGuid>7636f7a0-b538-427f-9cd0-37220634b8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//thead[3]/tr/th/div/ul/li[6]/a/lang</value>
      <webElementGuid>87259c10-4f55-45d9-b621-be5a25b9a458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'string_create' and (text() = 'Create CSV File' or . = 'Create CSV File')]</value>
      <webElementGuid>2979904b-eb5d-439f-9c10-870457446937</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
