<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Restore</name>
   <tag></tag>
   <elementGuidId>3718e7de-1f54-4c98-84e6-bee84b280eb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[3]/div/a/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;versions_restore&quot;)/span[@class=&quot;pica-glyph glyphicons glyphicons-restart&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pica-glyph.glyphicons.glyphicons-restart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>04019e1b-acf1-43d1-8e0a-2785ec54804e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-glyph glyphicons glyphicons-restart</value>
      <webElementGuid>e54c560e-f194-4ab9-8530-feb7a199d746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;versions_restore&quot;)/span[@class=&quot;pica-glyph glyphicons glyphicons-restart&quot;]</value>
      <webElementGuid>b0111f93-436e-40af-a7fe-2120c4d18c62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='versions_restore']/span</value>
      <webElementGuid>12c340a4-dac0-4e58-828c-6c59418b2936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div/a/span</value>
      <webElementGuid>368fa4fb-3d2e-4b9c-8d16-27d120569662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
