<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept</name>
   <tag></tag>
   <elementGuidId>393ed58d-7978-4eb7-9195-c2026f66943f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.wpgdprc-button.wpgdprc-button--accept.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div/div/div/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5549fcba-efee-401c-8556-3a49b7201d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6c5dd6b-ca40-445e-b50b-88a1baa92679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpgdprc-button wpgdprc-button--accept lazyloaded</value>
      <webElementGuid>3aec98fb-3d88-4b68-8de1-08cdacfc3710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Accept </value>
      <webElementGuid>e5b5128c-bacd-41d4-bc2e-d4289843f8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;avada-html-layout-Wide avada-html-header-position-Top avada-is-100-percent-template js csstransforms csstransforms3d csstransitions ua-windows_nt ua-windows_nt-10 ua-windows_nt-10-0 ua-chrome ua-chrome-146 ua-chrome-146-0 ua-chrome-146-0-0 ua-chrome-146-0-0-0 ua-desktop ua-desktop-windows ua-webkit ua-webkit-537 ua-webkit-537-36 js no-applicationcache geolocation history postmessage websockets localstorage sessionstorage no-websqldatabase webworkers hashchange audio canvas canvastext video webgl cssgradients multiplebgs opacity rgba inlinesvg hsla supports svgclippaths smil no-touchevents fontface generatedcontent textshadow cssanimations backgroundsize borderimage borderradius boxshadow flexbox cssreflections csstransforms csstransforms3d csstransitions&quot;]/body[@class=&quot;home wp-singular page-template page-template-100-width page-template-100-width-php page page-id-293 wp-theme-Avada sfsi_actvite_theme_default metaslider-plugin fusion-image-hovers fusion-pagination-sizing fusion-button_size-large fusion-button_type-flat fusion-button_span-no avada-image-rollover-circle-yes avada-image-rollover-no fusion-has-button-gradient fusion-body ltr fusion-sticky-header no-mobile-sticky-header no-mobile-totop avada-has-rev-slider-styles fusion-disable-outline fusion-sub-menu-fade mobile-logo-pos-left layout-wide-mode avada-has-boxed-modal-shadow-None layout-scroll-offset-full avada-has-zero-margin-offset-top fusion-top-header menu-text-align-left mobile-menu-design-classic fusion-show-pagination-text fusion-header-layout-v3 avada-responsive avada-footer-fx-none avada-menu-highlight-style-bar fusion-search-form-classic fusion-main-menu-search-dropdown fusion-avatar-square avada-dropdown-styles avada-blog-layout-Large avada-blog-archive-layout-Large avada-header-shadow-yes avada-menu-icon-position-left avada-has-megamenu-shadow avada-has-mainmenu-dropdown-divider avada-has-header-100-width avada-has-mobile-menu-search avada-has-breadcrumb-mobile-hidden avada-has-titlebar-hide avada-has-pagination-width_height avada-flyout-menu-direction-fade avada-ec-views-v1 rs-safari sfsi_2.77 do-animate fusion-no-touch&quot;]/div[@class=&quot;wpgdprc-consent-bar wpgdprc-consent-bar--position-bottom&quot;]/div[@class=&quot;wpgdprc-consent-bar__inner&quot;]/div[@class=&quot;wpgdprc-consent-bar__container&quot;]/div[@class=&quot;wpgdprc-consent-bar__content&quot;]/div[@class=&quot;wpgdprc-consent-bar__column wpgdprc-consent-bar__column--accept&quot;]/button[@class=&quot;wpgdprc-button wpgdprc-button--accept lazyloaded&quot;]</value>
      <webElementGuid>b4883f7b-0b3c-4d61-95ef-e1b93f9884cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>6b2fee40-c981-417e-837b-15404b3e3818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More information'])[1]/following::button[1]</value>
      <webElementGuid>26bdcfaa-7a30-45da-8276-239ef24018de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to content'])[1]/preceding::button[1]</value>
      <webElementGuid>79d67a9b-035e-43ac-99c8-e15711ce1d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Übersicht'])[1]/preceding::button[1]</value>
      <webElementGuid>d5566bb2-86e1-4189-9dde-642bcdfd7d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept']/parent::*</value>
      <webElementGuid>adf11c11-ad79-40bc-8134-0f09b40b80e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>a203bdc5-8b34-4e33-a6b3-093e34f72d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Accept ' or . = ' Accept ')]</value>
      <webElementGuid>0f184cb5-5f99-482a-985c-62aebb6af15d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
