<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Skip to content_NzQxOjMxOA-1</name>
   <tag></tag>
   <elementGuidId>092641ce-ea58-4745-b8b8-58efdf26f263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='NzQxOjMxOA==-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1dc743f5-6bc0-4d08-9698-7ed838483337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>873b8e8b-2c64-44d9-9970-45a88013eb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>69</value>
      <webElementGuid>6a1664ba-4d27-44ab-b41f-112ca6794199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>PowerFolder Logo</value>
      <webElementGuid>cfebb3f7-6633-4c27-a312-13f59e6eda16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nitro-lazy-srcset</name>
      <type>Main</type>
      <value>https://cdn-jaldf.nitrocdn.com/YKHeZXZqwqgqxnLsUtOKLaltDITIteKe/assets/images/optimized/rev-32c9489/www.powerfolder.com/wp-content/uploads/2020/02/PowerFolder_sync_and-_dark-300x69-3.png 1x</value>
      <webElementGuid>70df958b-433c-44cb-ac3a-58534478a3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nitro-lazy-src</name>
      <type>Main</type>
      <value>https://cdn-jaldf.nitrocdn.com/YKHeZXZqwqgqxnLsUtOKLaltDITIteKe/assets/images/optimized/rev-32c9489/www.powerfolder.com/wp-content/uploads/2020/02/PowerFolder_sync_and-_dark-300x69-3.png</value>
      <webElementGuid>8b2bdf61-76b1-444a-8b09-6c38e7dabead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fusion-standard-logo lazyloaded</value>
      <webElementGuid>681f96d7-1ba3-4b96-80c8-17aac94a6ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>25e80d69-01dd-4b78-8807-b15c69e108e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NzQxOjMxOA==-1</value>
      <webElementGuid>fb6fbe36-f285-41e4-bfc6-ac5a8799f8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-jaldf.nitrocdn.com/YKHeZXZqwqgqxnLsUtOKLaltDITIteKe/assets/images/optimized/rev-32c9489/www.powerfolder.com/wp-content/uploads/2020/02/PowerFolder_sync_and-_dark-300x69-3.png</value>
      <webElementGuid>86ef4732-c37b-499c-80f5-e1a5babf3720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://cdn-jaldf.nitrocdn.com/YKHeZXZqwqgqxnLsUtOKLaltDITIteKe/assets/images/optimized/rev-32c9489/www.powerfolder.com/wp-content/uploads/2020/02/PowerFolder_sync_and-_dark-300x69-3.png 1x</value>
      <webElementGuid>dc0971f8-832e-455e-973a-49e961913c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NzQxOjMxOA==-1&quot;)</value>
      <webElementGuid>d851dc6e-c76f-4fdb-8f1d-174aa6a737ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='NzQxOjMxOA==-1']</value>
      <webElementGuid>3b2b39e9-72bb-46f1-8a48-3976aea36692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/header/div/div[3]/div/div/a/img</value>
      <webElementGuid>06c5beab-0e4d-448f-bbc6-a3502d091744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='PowerFolder Logo']</value>
      <webElementGuid>52e3c3f6-37cd-4f68-b4f9-633aa6185cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>c6abc354-69d4-4b44-b240-56e406c3d5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'PowerFolder Logo' and @id = 'NzQxOjMxOA==-1' and @src = 'https://cdn-jaldf.nitrocdn.com/YKHeZXZqwqgqxnLsUtOKLaltDITIteKe/assets/images/optimized/rev-32c9489/www.powerfolder.com/wp-content/uploads/2020/02/PowerFolder_sync_and-_dark-300x69-3.png']</value>
      <webElementGuid>086dd986-35e2-4dee-8200-ec00c58952db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
