<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No_Links</name>
   <tag></tag>
   <elementGuidId>49a8e969-1ccf-4806-a4ed-f24b4b5c939d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='links_table']//tr[contains(@class,'pica-table-empty')]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#links_table tr.pica-table-empty > td</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>49a8e969-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
</WebElementEntity>
