<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_manage</name>
   <tag></tag>
   <elementGuidId>1d47977a-1715-4af3-aba6-e0d24e0d1688</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='files_files_table']//ul[contains(@class,'conext-dropdown-menu')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#files_files_table ul.conext-dropdown-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>1d47977a-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>conext-dropdown-menu</value>
      <webElementGuid>1d47977a-0001-0001-0001-000000000002</webElementGuid>
   </webElementProperties>
</WebElementEntity>
