<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Change_org_avatar</name>
   <tag></tag>
   <elementGuidId>a3575f27-41a5-4e41-87d9-0090514fd80c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_organization_avatar_change</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[3]/div/div/div[2]/div[2]/div[1]/div[2]/div/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e768ac7-b8cd-4847-a599-2969d40ded8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_organization_avatar_change</value>
      <webElementGuid>3d70eba7-b354-4ed9-b4ca-0838ddb6f0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block btn-default</value>
      <webElementGuid>dbb9d4ec-c3aa-442d-93a3-13a5a6a8f4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Change
                                </value>
      <webElementGuid>6fb74dfb-b058-4361-9072-bd54dc608ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_organization_avatar_change&quot;)</value>
      <webElementGuid>62ff9a12-2753-4f87-8242-67e5f6ad587a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pica_organization_avatar_change']</value>
      <webElementGuid>74b1e436-4274-498e-bcc9-41830ed6dd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_organization_dialog']/div/div/div[2]/div[2]/div/div[2]/div/a</value>
      <webElementGuid>86dc35e2-b64c-48d5-83d0-849f13ea5d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups'])[3]/following::a[1]</value>
      <webElementGuid>420a7364-a507-4660-bebc-6b13c8eec537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Members'])[2]/following::a[2]</value>
      <webElementGuid>ad4cfd2e-9af2-4ee1-838d-854a1e434c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::a[1]</value>
      <webElementGuid>8156d391-056d-423b-996c-0a4748d418e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/a</value>
      <webElementGuid>c1738b0d-4432-4ee0-a569-244e3c62392e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pica_organization_avatar_change' and (text() = '
                                    Change
                                ' or . = '
                                    Change
                                ')]</value>
      <webElementGuid>f011b0ef-d098-43b9-811d-e539397a5ca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
