<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>organization_avatar</name>
   <tag></tag>
   <elementGuidId>8ea00a49-7578-4202-97a3-492b9b9710e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_organization_avatar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[3]/div/div/div[2]/div[2]/div[1]/div[1]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b3d0f9ac-b9c6-4caa-bf7a-5d8985e9fc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_organization_avatar</value>
      <webElementGuid>81e7d071-5fee-4886-b4db-03f4492e332a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-avatar pica-border</value>
      <webElementGuid>0a742a1f-d4c1-49a8-bb5e-de04fb6033bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/avatars/ZDg0NjVmMDktN2JiYy01</value>
      <webElementGuid>74a89700-d273-490a-bce6-94ede8194f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_organization_avatar&quot;)</value>
      <webElementGuid>c456b43e-da31-45e2-a7a5-465b6219bf16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pica_organization_avatar']</value>
      <webElementGuid>9abd9eb5-f9e5-4fb3-a216-3a2b230556cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_organization_dialog']/div/div/div[2]/div[2]/div/div/img</value>
      <webElementGuid>007dcfc2-b4ae-423c-a4f0-c8420a9292ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>6514817e-4c80-4bdf-b4a4-f943e03f07f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'pica_organization_avatar' and @src = '/avatars/ZDg0NjVmMDktN2JiYy01']</value>
      <webElementGuid>d6b6ff03-95c4-41cc-9236-1419819e7070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
