<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>organization_storage</name>
   <tag></tag>
   <elementGuidId>2eada206-c1af-4c80-9555-b986630f718d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[3]/div/div/div[2]/div[1]/div[2]/div[2]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pica_organization_storage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e1485f3-467b-4ef6-ad80-f6cc656d0be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_organization_storage</value>
      <webElementGuid>e9ed4d39-6a87-4b22-b4dd-ef281ed3dc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fb8007fe-3625-4269-bcc6-a6bca0288d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4d21c01e-f2b4-452f-b24b-6de7b09a8aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6229488-201a-4215-9470-57005636b0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_storage</value>
      <webElementGuid>24e7cfe5-4b73-4cd2-ba6c-a08d95cbee64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Storage (GB)</value>
      <webElementGuid>28947101-f4c2-47d6-af8c-676670fdc2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_organization_storage&quot;)</value>
      <webElementGuid>4eb9d576-11b5-4fbc-8a17-43eb45cdd9b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_organization_storage']</value>
      <webElementGuid>854e96a5-5633-41eb-b632-705c1bb3ad9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_organization_dialog']/div/div/div[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>553fe219-5d7f-4759-bafb-c78911097e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>3c87d212-1b50-40e4-bd19-46acda591cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_organization_storage' and @type = 'number' and @placeholder = 'Storage (GB)']</value>
      <webElementGuid>4d2f51da-2679-4b87-a498-b4e4ede69a00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
