<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lschen_pica-glyph glyphicons glyphicon_aee676</name>
   <tag></tag>
   <elementGuidId>68b57745-fdb6-4ead-ae94-cfc8a0c29748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pica-glyph.glyphicons.glyphicons-plus-sign</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='accounts_table']/thead[2]/tr/th/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-glyph glyphicons glyphicons-plus-sign</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accounts_table&quot;)/thead[2]/tr[1]/th[@class=&quot;pica-icon-column text-center&quot;]/div[@class=&quot;pica-inline dropdown&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;pica-glyph glyphicons glyphicons-plus-sign&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='accounts_table']/thead[2]/tr/th/div/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//thead[2]/tr/th/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
