<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_13h9tdCse</name>
   <tag></tag>
   <elementGuidId>e0c82462-c65f-4eec-8e56-2ca0180d9e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Object_1526379198 > td.pica-overflow > a.pica-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='Object_1526379198']/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b047e553-9dde-42ce-9789-b3c20f071f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-name</value>
      <webElementGuid>b0bbc88a-c619-4d4b-bd2e-4716f373576b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>download/MlFDUlVSdFFXaXQydEhtVDFFaTh4</value>
      <webElementGuid>26f4ffc2-0908-40fa-87e1-002180706540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-serial</name>
      <type>Main</type>
      <value>{&quot;_flags&quot;:1,&quot;_oid&quot;:&quot;2QCRURtQWit2tHmT1Ei8x&quot;,&quot;_name&quot;:&quot;13h9tdCse&quot;,&quot;_intName&quot;:&quot;13h9tdCse&quot;,&quot;_size&quot;:3741,&quot;_archiveSize&quot;:0,&quot;_resUrl&quot;:&quot;/files/MlFDUlVSdFFXaXQydEhtVDFFaTh4&quot;,&quot;_openUrl&quot;:null,&quot;_basePath&quot;:&quot;/Users/mac/PowerFolders/admin/13h9tdCse&quot;,&quot;_path&quot;:&quot;&quot;,&quot;_folderId&quot;:&quot;2QCRURtQWit2tHmT1Ei8x&quot;,&quot;_accountsCount&quot;:0,&quot;_groupsCount&quot;:0,&quot;_versions&quot;:25,&quot;_ownerOid&quot;:0,&quot;_isBlocked&quot;:false,&quot;_modifiedDate&quot;:-1,&quot;_modifiedDateMS&quot;:-1,&quot;_modifiedOn&quot;:&quot;&quot;,&quot;_modifiedBy&quot;:null,&quot;_modifiedByAccount&quot;:null,&quot;_version&quot;:0,&quot;_publicUrl&quot;:&quot;/public?folderID=MlFDUlVSdFFXaXQydEhtVDFFaTh4&quot;,&quot;_permission&quot;:8,&quot;_publicPermission&quot;:1,&quot;_folderIdEnc&quot;:&quot;MlFDUlVSdFFXaXQydEhtVDFFaTh4&quot;,&quot;_url&quot;:&quot;MlFDUlVSdFFXaXQydEhtVDFFaTh4&quot;}</value>
      <webElementGuid>34f4bd96-6cc4-46ae-8f40-3651bec787d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13h9tdCse</value>
      <webElementGuid>11a1498c-a301-4ba4-b75f-7552bd6053ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_1526379198&quot;)/td[@class=&quot;pica-overflow&quot;]/a[@class=&quot;pica-name&quot;]</value>
      <webElementGuid>ae8cfb25-831f-4cc5-b517-4d96286097ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_1526379198']/td[2]/a</value>
      <webElementGuid>323131b2-d4fc-46b6-ae2d-0144f501f631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'13h9tdCse')]</value>
      <webElementGuid>b5f23f02-0a29-4ff4-ba75-b6e6a34f4757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No members'])[2]/following::a[2]</value>
      <webElementGuid>202fe20a-dbd2-4f98-be15-c38a4b059f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[2]/following::a[3]</value>
      <webElementGuid>ff961430-1b22-4190-a582-4b5226b41157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[3]/preceding::a[1]</value>
      <webElementGuid>f39c49ab-3bf8-4ffb-8f41-606c57b4448d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No members'])[3]/preceding::a[1]</value>
      <webElementGuid>b034092a-6b2b-44d5-a426-7e499ce34b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='13h9tdCse']/parent::*</value>
      <webElementGuid>12dcb790-0119-467b-a2bc-3f1628870146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'download/MlFDUlVSdFFXaXQydEhtVDFFaTh4')]</value>
      <webElementGuid>69d1e397-e8d1-413b-9657-36159c5ccc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/a</value>
      <webElementGuid>be13208e-e2e4-4dba-8cce-4356797d6c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'download/MlFDUlVSdFFXaXQydEhtVDFFaTh4' and (text() = '13h9tdCse' or . = '13h9tdCse')]</value>
      <webElementGuid>e60edf5f-a7b3-45b6-8067-d8ad13bacd2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
