<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_dir1</name>
   <tag></tag>
   <elementGuidId>b65a7687-6673-48dd-9d3a-41d375ba7b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pica-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='Object_3083588']/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8cbadb78-ebbd-4fd6-8b0b-03f324d0e34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-name</value>
      <webElementGuid>8cf7d029-41e5-4cfc-bc68-cdcaa3ef9e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>download/MkNQekFFQlZMU3B0MTc2S3dRd0Vv/dir1</value>
      <webElementGuid>209b615f-470a-4e40-9536-f695a2f2b477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-serial</name>
      <type>Main</type>
      <value>{&quot;_flags&quot;:2,&quot;_oid&quot;:&quot;&quot;,&quot;_name&quot;:&quot;dir1&quot;,&quot;_intName&quot;:&quot;&quot;,&quot;_size&quot;:0,&quot;_archiveSize&quot;:0,&quot;_resUrl&quot;:&quot;/filestable/MkNQekFFQlZMU3B0MTc2S3dRd0Vv/dir1&quot;,&quot;_openUrl&quot;:null,&quot;_basePath&quot;:null,&quot;_path&quot;:&quot;dir1&quot;,&quot;_folderId&quot;:null,&quot;_accountsCount&quot;:0,&quot;_groupsCount&quot;:0,&quot;_versions&quot;:0,&quot;_ownerOid&quot;:0,&quot;_isBlocked&quot;:false,&quot;_modifiedDate&quot;:&quot;22 Jul 2022 19:9&quot;,&quot;_modifiedDateMS&quot;:1658513392077,&quot;_modifiedOn&quot;:&quot;&quot;,&quot;_modifiedBy&quot;:null,&quot;_modifiedByAccount&quot;:&quot;admin&quot;,&quot;_version&quot;:0,&quot;_publicUrl&quot;:&quot;&quot;,&quot;_permission&quot;:null,&quot;_publicPermission&quot;:null,&quot;_folderIdEnc&quot;:&quot;MkNQekFFQlZMU3B0MTc2S3dRd0Vv&quot;,&quot;_url&quot;:&quot;MkNQekFFQlZMU3B0MTc2S3dRd0Vv/dir1&quot;}</value>
      <webElementGuid>4c569b6f-0ebf-4a99-964a-685e6e7f7639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dir1</value>
      <webElementGuid>be7b09f5-e6f6-4a51-98db-55d2d89c35bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_3083588&quot;)/td[@class=&quot;pica-overflow&quot;]/a[@class=&quot;pica-name&quot;]</value>
      <webElementGuid>83a011cc-f73e-42de-8710-8319f6895b48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_3083588']/td[2]/a</value>
      <webElementGuid>41b69eeb-27ef-40c0-a5cd-7eeba164f25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'dir1')]</value>
      <webElementGuid>dd30749d-a911-41fb-8743-8a1857f0a49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gallery'])[1]/following::a[1]</value>
      <webElementGuid>b6cfed0b-05b5-49b9-a0c1-7a4f91ffdf48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grid'])[1]/following::a[2]</value>
      <webElementGuid>b440b6f8-3040-4361-a8d3-984ae288c28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[3]/preceding::a[1]</value>
      <webElementGuid>196c132d-0587-476a-82ee-bb945acd6c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yesterday'])[1]/preceding::a[1]</value>
      <webElementGuid>bac729e7-bb90-4951-9b3a-1f3ff5800674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='dir1']/parent::*</value>
      <webElementGuid>5a78b7e4-6a8d-4af2-8c88-eb1f249cfa8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'download/MkNQekFFQlZMU3B0MTc2S3dRd0Vv/dir1')]</value>
      <webElementGuid>f89fd851-db24-4131-9fb3-34cfa384357d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>9a94e471-9a7f-4664-8013-3d7813bae6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'download/MkNQekFFQlZMU3B0MTc2S3dRd0Vv/dir1' and (text() = 'dir1' or . = 'dir1')]</value>
      <webElementGuid>fb89b8f3-4988-4e1d-9811-2561b16ddd38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
