<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Check_date_links_file</name>
   <tag></tag>
   <elementGuidId>d099383b-4e35-470d-bcdc-8961292ad32d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='share_table']//tr[starts-with(@id,'share_')]//span[contains(@class,'pica-in-brackets')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#share_table tr[id^='share_'] span.pica-in-brackets</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d099383b-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-in-brackets</value>
      <webElementGuid>d099383b-0001-0001-0001-000000000002</webElementGuid>
   </webElementProperties>
</WebElementEntity>
