<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Link created</name>
   <tag></tag>
   <elementGuidId>04168b0e-91b4-41e0-aeaf-993b346012c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notification_2077784862']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pica-notification-box.alert.alert-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c702389b-d499-43a1-a9f3-78594994e046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-notification-box alert alert-info</value>
      <webElementGuid>abc20759-d758-4707-8bf5-50b07fa8f660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>c83787ee-c220-4884-85ef-947e8a9b63f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link created</value>
      <webElementGuid>be7917d2-5a7e-40e7-881d-c665e15b384e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification_2077784862&quot;)/div[@class=&quot;pica-notification-box alert alert-info&quot;]</value>
      <webElementGuid>f1887177-84fb-439f-84e8-e20e8ae75d3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notification_2077784862']/div</value>
      <webElementGuid>636ccd4f-c9d0-49ae-9515-578d13688b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Accessibility Problem'])[1]/following::div[3]</value>
      <webElementGuid>3309808f-7ed4-4ed8-8ffb-6d0aaa8a147b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/following::div[3]</value>
      <webElementGuid>eaf582da-d23d-4307-9d44-02c992227d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>f0c6478b-860b-439f-939e-60658ca4c589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Link created' or . = 'Link created')]</value>
      <webElementGuid>90af9b2c-b841-4540-8991-aa2fd401a771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
