<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon-copy</name>
   <tag></tag>
   <elementGuidId>cce84e90-49d5-43f9-a7d8-fcd3f8fabac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[data-tooltip='tooltip_copy_to_clip'] > i.glyphicons-copy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@data-tooltip='tooltip_copy_to_clip']/i[contains(@class,'glyphicons-copy')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c30c3fcc-bf55-4a1d-bb5a-c5839ab56630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons-copy</value>
      <webElementGuid>98474c16-9d97-4982-8811-b5ac976277b4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
