<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputValidTill</name>
   <tag></tag>
   <elementGuidId>84196b0f-c969-42ec-a792-bf219281d2dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_link_valid_till</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pica_link_valid_till']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f7345ce-6243-4deb-966b-551cb33327c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>490e234d-82c9-4f63-b257-e2636e4b65c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0596ea45-e361-48f4-8d88-c94212ece2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_valid_till</value>
      <webElementGuid>71400318-c662-4fb1-9727-ffc7ac329f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_link_valid_till</value>
      <webElementGuid>2d346b7d-6927-49ba-822e-8dc079f4d549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Valid till</value>
      <webElementGuid>db57807e-e421-4067-a828-361f069ec37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_link_valid_till&quot;)</value>
      <webElementGuid>632fd10a-1574-4d4f-93e6-53a6d1fe8449</webElementGuid>
   </webElementProperties>
</WebElementEntity>
