<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Span_Create_folder_in_folder</name>
   <tag></tag>
   <elementGuidId>bb6a4c23-33b1-4d51-a11e-bfa244805d92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//thead[@id='files_select_header']/tr/th[3]/div[2]/a[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pica-table-selection-multi.files-ui-cut > span.pica-glyph.glyphicons.glyphicons-scissors-alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6ae5260f-0af6-4c61-b085-263b089d659d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-glyph glyphicons glyphicons-scissors-alt</value>
      <webElementGuid>80f4eb74-3f47-45dd-8cf6-c41bd8af3704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;files_select_header&quot;)/tr[1]/th[@class=&quot;text-right&quot;]/div[@class=&quot;pica-table-selection-context pica-inline hidden-xs text-right&quot;]/a[@class=&quot;pica-table-selection-multi files-ui-cut&quot;]/span[@class=&quot;pica-glyph glyphicons glyphicons-scissors-alt&quot;]</value>
      <webElementGuid>79301a62-c2b8-49aa-8c91-9ff3d92cece3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//thead[@id='files_select_header']/tr/th[3]/div[2]/a[4]/span</value>
      <webElementGuid>6c98abed-f251-4473-bfb0-6ba5bbe763d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[4]/span</value>
      <webElementGuid>b9b1c6fc-9d89-43ce-9307-c2dd700b9d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica-files-create-dropdown']/ul/li/a/span</value>
      <webElementGuid>e00097ad-4cd6-4c40-bbf8-9c23b7f8a672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//thead[3]/tr/th/div/ul/li/a/span</value>
      <webElementGuid>22e22807-0469-4853-bd34-9a43478d4235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
