<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyAuthenticationButton</name>
   <tag></tag>
   <elementGuidId>b566a420-6bd6-46af-8dde-c4e615ee529d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_content']/div/div[2]/div/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>3a387778-9fd9-4e0a-ad8b-52dba1e655d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-card-title</value>
      <webElementGuid>c3d01977-053e-404f-b874-d8cff21c701a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authentication</value>
      <webElementGuid>f80d5a15-eade-452b-9682-2b1e55bbd7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_content&quot;)/div[@class=&quot;pica-flex pica-content-scroll&quot;]/div[@class=&quot;pica-card card&quot;]/div[@class=&quot;pica-card-body&quot;]/h5[@class=&quot;pica-card-title&quot;]</value>
      <webElementGuid>89d98231-4dec-47c9-b094-0bdde31cd1f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div/div[2]/div/h5</value>
      <webElementGuid>0fb2421e-23f9-42f7-9c75-844f73e3d187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure'])[1]/following::h5[1]</value>
      <webElementGuid>21e50dbd-006c-44d8-8f24-8c9207fdf410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[1]/following::h5[1]</value>
      <webElementGuid>446bf620-87bc-4dd4-a2ac-b8be7ec6e271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure'])[2]/preceding::h5[1]</value>
      <webElementGuid>6a428741-53b8-4c92-a9e8-58bd38801376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Storage'])[2]/preceding::h5[1]</value>
      <webElementGuid>74f2a264-cdaa-4274-8171-264dc4ac739e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Authentication']/parent::*</value>
      <webElementGuid>86c0a955-93b9-4b63-8a64-6bf33bf50fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h5</value>
      <webElementGuid>5d326ab7-4806-44ba-b5b6-8f571c21dd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Authentication' or . = 'Authentication')]</value>
      <webElementGuid>6e5dfba8-e9b6-4821-9460-9d757a3d4a3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
