<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyConfigureButton</name>
   <tag></tag>
   <elementGuidId>4c2f7248-bd75-4bf1-ae4e-b5ff41c58708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pica-card-glyph.pica-glyph.show.glyphicons.glyphicons-hdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_content']/div/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>28ca363e-0aa1-4051-af42-361033bf5576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-card-glyph pica-glyph show glyphicons glyphicons-hdd</value>
      <webElementGuid>11716747-4d30-40ee-9456-0af982c6650e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>8c469701-3b96-4453-a887-b04a296333f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_content&quot;)/div[@class=&quot;pica-flex pica-content-scroll&quot;]/div[@class=&quot;pica-card card&quot;]/span[@class=&quot;pica-card-glyph pica-glyph show glyphicons glyphicons-hdd&quot;]</value>
      <webElementGuid>8d6b588b-3a76-4c72-98ed-aa4fe9358933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div/div[3]/span</value>
      <webElementGuid>07d83101-5c6c-4c72-a64e-1f56298e2235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>23755b35-006c-43cb-932e-0855f01022c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div/div[2]/span</value>
      <webElementGuid>2e4392ba-8929-42dc-b210-dd52755e2fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>6b2c6111-4db4-40de-806c-ded79fe85ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
