<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Google Play</name>
   <tag></tag>
   <elementGuidId>6441a8cf-6328-4845-9f97-94e3cefcf356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div[2]/div/div/div/div[5]/div[1]/div[2]/a/lang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>77d3fb68-7546-472a-b31f-1558f681e7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-space-top pica-hidden-on-small btn btn-success</value>
      <webElementGuid>d83bd4ac-d208-4a84-9d19-be2130ad7106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://market.android.com/details?id=de.goddchen.android.powerfolder.A</value>
      <webElementGuid>47a80a54-5eaa-4c21-a932-2cb4d8cdfb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e8696d9e-aec4-4eff-9a9a-c8edb656e364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Visiter
                    </value>
      <webElementGuid>db47752d-50ea-44d5-9463-e7bc0d7cdf31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;wallpaper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-8 col-md-6 col-lg-6 pica-relative&quot;]/div[@class=&quot;pica-dialog&quot;]/div[1]/div[1]/div[@class=&quot;pica-boxes&quot;]/div[@class=&quot;pica-box pica-block-on-small&quot;]/div[@class=&quot;pica-box-body&quot;]/a[@class=&quot;pica-space-top pica-hidden-on-small btn btn-success&quot;]</value>
      <webElementGuid>8815d006-c4af-4360-bbef-fcd725f385b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visiter'])[1]/following::a[1]</value>
      <webElementGuid>556f75a0-c554-4d56-bb39-588cf0b00a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Android'])[1]/following::a[2]</value>
      <webElementGuid>94a356a7-586a-4118-8938-afad4f111e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iOS'])[1]/preceding::a[1]</value>
      <webElementGuid>adfc1273-bf91-4522-a5ec-4ae14ff014d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://market.android.com/details?id=de.goddchen.android.powerfolder.A')])[2]</value>
      <webElementGuid>7acaae7c-b864-4fd0-9c67-0b13253f7ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/a</value>
      <webElementGuid>5714b728-dd77-4d16-a167-3bef0b6707d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://market.android.com/details?id=de.goddchen.android.powerfolder.A' and (text() = '
                        Visiter
                    ' or . = '
                        Visiter
                    ')]</value>
      <webElementGuid>dfc641ed-d9d9-4249-bb71-ca8c9097d8fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
