<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete</name>
   <tag></tag>
   <elementGuidId>8ceeb06b-4ebc-4a61-9fa8-70a06952f4c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#device_delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[3]/table[4]/thead[1]/tr/th[3]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>03c9b8f7-9037-4adc-ad2b-8a5f1b48c03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>device_delete</value>
      <webElementGuid>ffe3ae2d-9386-410d-93ea-fe9da160f3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-table-selection-multi</value>
      <webElementGuid>a4781fd0-4bcc-4d0a-8695-9369ea0dd82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        
                        Delete
                    </value>
      <webElementGuid>8092faf6-657a-4f97-8bf6-b10f6f9ddd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;device_delete&quot;)</value>
      <webElementGuid>5db4f618-2509-4fef-a2de-f0472ef4e46f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='device_delete']</value>
      <webElementGuid>4c32ebee-44d7-4241-b38d-659bf5332a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='profile_devices_table']/thead/tr/th[3]/div/a</value>
      <webElementGuid>9554cb58-b436-4774-8106-70bbdd7d2d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect'])[1]/following::a[1]</value>
      <webElementGuid>5b9f90c8-6744-4ae5-a096-28db0db50d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permission'])[1]/following::a[2]</value>
      <webElementGuid>f20e088c-3adc-42e2-bceb-09400b2b3a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Device'])[1]/preceding::a[1]</value>
      <webElementGuid>b6c9c02f-1949-4d8c-9698-f95306df9318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div/a</value>
      <webElementGuid>7f2fb7ca-7d84-49a7-9f4d-995e448b7c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'device_delete' and (text() = '
                        
                        Delete
                    ' or . = '
                        
                        Delete
                    ')]</value>
      <webElementGuid>0b3b7b7f-735d-442c-8bc0-0c2bc0ddf76a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
