<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Groups</name>
   <tag></tag>
   <elementGuidId>1250db5c-12f0-45e1-8fb0-17e269d5ebf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='label_groups']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;label_groups&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>5a69a920-eba3-4a18-8b8e-c5e6e8322484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-hidden-on-small text-center</value>
      <webElementGuid>f97cece9-0cfd-45db-b944-cd6cbb1987bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label_groups</value>
      <webElementGuid>a463fe89-47b2-4fa0-bd3f-f74c26511a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-plural</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d89f2db9-cc63-41ca-8103-8ad8cf7f9d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Groups</value>
      <webElementGuid>2e7e2fd2-c7dc-4a39-af97-c9d8751950dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_menu&quot;)/table[1]/tbody[1]/tr[6]/td[@class=&quot;text-center&quot;]/a[1]/lang[@class=&quot;pica-hidden-on-small text-center&quot;]</value>
      <webElementGuid>fbaa78d1-20a5-417a-9bb7-6a46ff51c465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='label_groups']</value>
      <webElementGuid>0463f970-d0b9-4907-9585-9a1408b2866b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_menu']/table/tbody/tr[6]/td/a/lang</value>
      <webElementGuid>71507903-d8e0-4a15-a12f-fdb91161c19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[1]/following::lang[1]</value>
      <webElementGuid>d7175dc9-b0ae-42e7-8f3c-1caeeb054711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Links'])[1]/following::lang[2]</value>
      <webElementGuid>547ace52-a22c-48dc-af3e-dd12f718b465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organizations'])[1]/preceding::lang[1]</value>
      <webElementGuid>7479a815-1f6b-44df-bcf0-33abff924342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Devices'])[1]/preceding::lang[2]</value>
      <webElementGuid>3ee653cf-2051-462d-8e87-0cf5fd0db578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Groups']/parent::*</value>
      <webElementGuid>21d5608e-f5ea-454a-a35e-ef8c810efe3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/a/lang</value>
      <webElementGuid>28763f63-0a7a-4ab1-ac17-4fc75ddbd4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'label_groups' and (text() = 'Groups' or . = 'Groups')]</value>
      <webElementGuid>35dda702-7e10-4168-bf00-c7260688996a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
