<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change</name>
   <tag></tag>
   <elementGuidId>aad96add-5d53-4500-a75e-d5ea346eda32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_account_avatar_change</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pica_account_avatar_change']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1005e87b-c892-4549-9ccf-ae7b987dc576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_account_avatar_change</value>
      <webElementGuid>e0b1cef7-2e10-4b6f-8a23-6cd397c34715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block btn-default</value>
      <webElementGuid>d3b2fdfb-dcd4-4cd3-923b-e6178b4c7100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Change
                                </value>
      <webElementGuid>0d086edc-88c3-4ae8-92d0-35d041a2f42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_avatar_change&quot;)</value>
      <webElementGuid>9da5c58b-6637-4d68-a49b-77ca4c1b924b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pica_account_avatar_change']</value>
      <webElementGuid>860c1712-134c-4e13-829d-88c9ca2754e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_account_dialog']/div/div/div[2]/div[2]/div/div[2]/div/a</value>
      <webElementGuid>03e7834c-8b33-4c46-bba6-cee2432766cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/a</value>
      <webElementGuid>7191fe93-c9e7-4f33-a424-a3d039fa454d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pica_account_avatar_change' and (text() = '
                                    Change
                                ' or . = '
                                    Change
                                ')]</value>
      <webElementGuid>4dd31676-c306-483e-93b8-506380bcf5dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
