<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_modal-backdrop fade</name>
   <tag></tag>
   <elementGuidId>1a31ad01-6549-4fa7-9ffc-9cf1f7281f11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-backdrop.fade</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e8482ca4-2230-4d58-8429-c3915bdcf606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-backdrop fade</value>
      <webElementGuid>ea7135a2-1bd3-4e53-98c3-b28771a8f9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal-backdrop fade&quot;]</value>
      <webElementGuid>eafe2570-4a2e-49bd-9338-fb497c278ea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>a47a5e21-6c7b-4d9a-b268-164c76319f08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
