<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputpica_account_last_name</name>
   <tag></tag>
   <elementGuidId>fc1ba2ba-6506-44bc-aa7c-85b79387165f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_account_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pica_account_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86db4aa6-f700-4939-a1ad-af9d2aeedfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_account_last_name</value>
      <webElementGuid>d60518f0-31f8-4ad7-af48-6550377b14f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0500856c-37df-4fb4-9957-8ae53917504e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e0159d1-d0f6-44fa-9193-9fbe2799d4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_last_name</value>
      <webElementGuid>97b63f0a-4a3f-4f4f-a5e3-380dad10cdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>3e278d68-2b2d-44d0-8bb3-bbbb30c819fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_last_name&quot;)</value>
      <webElementGuid>eb987b54-5517-4522-8c39-c98d52a01cd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_account_last_name']</value>
      <webElementGuid>8a07eb07-0968-4c52-9006-8bd4115191f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_account_dialog']/div/div/div[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>d3d44d37-bb4a-4da4-8d4a-4b2a9d690478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>0ce24c54-14f6-4dbe-b0bb-fdd0823178ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_account_last_name' and @type = 'text' and @placeholder = 'Last Name']</value>
      <webElementGuid>9f47833f-ce78-44c3-b542-f6a0aea7aa57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
