<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Delete</name>
   <tag></tag>
   <elementGuidId>e9f2c02f-1952-4f6c-a411-08a5988b8b42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_account_avatar_delete > lang[name=&quot;action_delete&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//lang[@name='action_delete'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>a1e0bb28-acc4-488e-b68d-ed41e6684216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action_delete</value>
      <webElementGuid>53b2dc68-ede9-44e7-affa-9b5b1b997aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>4d55b3d7-6145-438e-94cd-40916c568e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_avatar_delete&quot;)/lang[1]</value>
      <webElementGuid>dfb7e37f-7b20-4009-98d4-c653707b0c54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//lang[@name='action_delete'])[2]</value>
      <webElementGuid>07093dae-7658-4220-8d8b-fd4f9c509bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='pica_account_avatar_delete']/lang</value>
      <webElementGuid>8d205269-f3ed-4469-bb1c-f7a6531e80a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/a[2]/lang</value>
      <webElementGuid>3e7f461d-bca0-4b09-8fba-c4d2bfbeae8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'action_delete' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>e882efd6-edab-4c8b-8a1e-65d0ec6cd563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
