<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Save</name>
   <tag></tag>
   <elementGuidId>8b9f1197-1893-46eb-88d0-8350566878c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;button_save&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='button_save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>09f77179-ba11-400f-b9a5-2638e158632e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button_save</value>
      <webElementGuid>f08f2aa9-f0c9-4dab-8ab0-19b069b7836a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>ad9607f4-1fb4-40cf-bcd2-4384a05f6b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica-account-edit-save&quot;)/lang[1]</value>
      <webElementGuid>1614a595-20db-4e46-9a68-4923bed08d82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='button_save']</value>
      <webElementGuid>6e2f50f3-9280-4e80-a4cb-ac45023a0420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='pica-account-edit-save']/lang</value>
      <webElementGuid>88b51bcd-0f19-49d1-aac6-7e3fb7ebce6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/lang</value>
      <webElementGuid>e4a0a952-5fd6-4266-a497-751501abb5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'button_save' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>ac38b91a-826c-4287-9f19-587a6fdf525e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
