<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Avatar</name>
   <tag></tag>
   <elementGuidId>1eda45e6-850c-4078-b72a-37d168eb08ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;label_avatar&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='label_avatar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>aec9c7e3-5e8b-418c-83e1-5fef26ca2237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label_avatar</value>
      <webElementGuid>30e7b883-d1b9-4a33-a108-a86e496273e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Avatar</value>
      <webElementGuid>68434bbe-efc2-4917-87a4-af86f92e620f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_dialog&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/ul[@class=&quot;pica-space pica-nav-tabs nav nav-tabs&quot;]/li[@class=&quot;pica-hide-on-create hidden-xs&quot;]/a[1]/lang[1]</value>
      <webElementGuid>95b78af7-ceaa-47db-817e-96838ff4a193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='label_avatar']</value>
      <webElementGuid>9c1bbc68-08bd-4c35-846e-8c377890bf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_account_dialog']/div/div/div[2]/ul/li[2]/a/lang</value>
      <webElementGuid>154a8f73-c6ea-491d-9646-825fc1a4d579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a/lang</value>
      <webElementGuid>8dc8a675-266f-40fc-9263-915611e5281f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'label_avatar' and (text() = 'Avatar' or . = 'Avatar')]</value>
      <webElementGuid>6e97aac5-687b-4e4f-b121-6f00efe86f92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
