<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_My account</name>
   <tag></tag>
   <elementGuidId>6c2f74c1-24ed-4280-b61b-45007fce2f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.pica-arrow-right.dropdown-menu.dropdown-menu-right > li > div.media > div.media-body > a > lang[name=&quot;label_my_account&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//lang[@name='label_my_account'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>294f915c-6733-4d82-a1e4-6ee3963bd903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label_my_account</value>
      <webElementGuid>b45a03ef-3dd0-430b-a2ef-52d178f8696b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My account</value>
      <webElementGuid>8e6deab8-c5b3-4c15-958e-291b86ca6ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_action_normal&quot;)/div[@class=&quot;pica-inline dropdown open&quot;]/ul[@class=&quot;pica-arrow-right dropdown-menu dropdown-menu-right&quot;]/li[1]/div[@class=&quot;media&quot;]/div[@class=&quot;media-body&quot;]/a[1]/lang[1]</value>
      <webElementGuid>95891053-bfdf-442e-8b13-b6ad74acbc4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//lang[@name='label_my_account'])[2]</value>
      <webElementGuid>ac071410-be2f-4929-8fed-c7948324551b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_action_normal']/div[2]/ul/li/div/div[2]/a/lang</value>
      <webElementGuid>5a6ee342-6f1d-40f3-9195-134c2460d04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/div/div[2]/a/lang</value>
      <webElementGuid>da439574-8675-428c-95a7-de21880eeaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'label_my_account' and (text() = 'My account' or . = 'My account')]</value>
      <webElementGuid>3475bfcb-1f9b-4abd-bda4-bf55e6a4eb4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
