<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_glyphicons glyphicons-user pica-glyph</name>
   <tag></tag>
   <elementGuidId>7005def7-63f1-4d2c-b022-be36c0c210d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.text-center.pica-icon-column > span.glyphicons.glyphicons-user.pica-glyph</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='Object_1669211262']/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>637b310b-81db-4a32-888e-200f7cd32a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-user pica-glyph</value>
      <webElementGuid>27d31605-8498-4c0e-b4f1-8620e0511967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_1669211262&quot;)/td[@class=&quot;text-center pica-icon-column&quot;]/span[@class=&quot;glyphicons glyphicons-user pica-glyph&quot;]</value>
      <webElementGuid>5a5ecc72-b4ca-4eb1-a42b-a5ccc45a28b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_1669211262']/td/span</value>
      <webElementGuid>0d74a688-25e6-400e-be16-096302b3287f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>95e93214-79a1-4a47-a3ff-496498bdbb07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
