<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_a_fd27_jan_2024_04_07_03a.com (Deactivated)</name>
   <tag></tag>
   <elementGuidId>11a96313-cb78-45f0-a35a-a96df4e30411</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.pica-overflow.pica-serial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='Object_1669211262']/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>857ad54d-3e92-42e2-a4aa-e79d567547eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-overflow pica-serial</value>
      <webElementGuid>b311acb7-ede6-41c5-a361-d9d79df03381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>a_fd27_jan_2024_04_07_03@a.com (Deactivated)</value>
      <webElementGuid>5ab74606-65fc-409e-89c1-c4ded786d9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_1669211262&quot;)/td[@class=&quot;pica-overflow pica-serial&quot;]</value>
      <webElementGuid>076bb587-d038-47af-983e-15b123a68a17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_1669211262']/td[2]</value>
      <webElementGuid>9242e39c-99f2-4255-aa2e-b4f07b2655c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>0be2b830-c14b-4f6a-90c0-1d28ff3bd3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'a_fd27_jan_2024_04_07_03@a.com (Deactivated)' or . = 'a_fd27_jan_2024_04_07_03@a.com (Deactivated)')]</value>
      <webElementGuid>3fab9ddd-a939-46cb-86e9-548613476376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
