<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Details</name>
   <tag></tag>
   <elementGuidId>93df5f22-315d-4f37-9c36-03d3c5e73122</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.hidden-xs > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='profile_nav']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43585304-7950-4983-89bf-8d7503e869b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>details</value>
      <webElementGuid>92438b3d-f6a7-415e-894b-ebb0dbfae232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Details
            </value>
      <webElementGuid>fb3edb53-4a67-4e38-8283-da6baf0b9dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_nav&quot;)/li[@class=&quot;hidden-xs&quot;]/a[1]</value>
      <webElementGuid>64667d4d-5ae3-4d68-a36c-e00050fb7a4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='profile_nav']/li[2]/a</value>
      <webElementGuid>3d4afc01-ae37-40c4-85cb-5c38f7d12b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::a[1]</value>
      <webElementGuid>b46cab9b-dcff-4044-a423-1485e9ae7c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::a[2]</value>
      <webElementGuid>7cc47fcd-4fd2-4e48-9b69-fc6989330ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organizations'])[2]/preceding::a[1]</value>
      <webElementGuid>0af4b18c-3679-4dea-93ae-62faceff384d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>0da3f5fa-2572-4cf1-832f-2c2e43089dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
                Details
            ' or . = '
                Details
            ')]</value>
      <webElementGuid>035048da-1dca-413b-bc73-4474caac06fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
