<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit E-Mails</name>
   <tag></tag>
   <elementGuidId>7c4139df-458b-4a25-aab1-e6d9a1da7aa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[4]/div/div/div[2]/div/div[1]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.pica-taginput-button.btn.btn-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd11b6f5-dcdb-4537-8819-214801b930e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-taginput-button btn btn-default</value>
      <webElementGuid>bbcf03fe-e2e0-4bdd-a2f1-a83192dfb59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_mails_inputlist&quot;)/div[@class=&quot;pica-inputlist-taginput pica-taginput form-group input-group&quot;]/div[@class=&quot;input-group-btn&quot;]/button[@class=&quot;pica-taginput-button btn btn-default&quot;]</value>
      <webElementGuid>e1db3033-bcb1-4702-b40a-bceef9f1dd1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile_mails_inputlist']/div/div[2]/button</value>
      <webElementGuid>4486220c-797f-4e85-9f81-3a6cc28c838d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit E-Mails'])[1]/following::button[2]</value>
      <webElementGuid>20af2fce-459d-4202-8522-ae8e6f0e1fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::button[2]</value>
      <webElementGuid>d2eb7f2e-361c-4cd2-83e6-fabd7e61317a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::button[1]</value>
      <webElementGuid>86d1b71b-83dc-44c4-bfe3-1b62feeb2814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nothing to show'])[1]/preceding::button[1]</value>
      <webElementGuid>900ae6c2-157c-4d1c-8c78-390dd9f2dcbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>a6a3bb49-64d1-4e42-9b58-435b6952e907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
