<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Details_first_name_Change</name>
   <tag></tag>
   <elementGuidId>4213a36d-7cc5-4caf-bd3b-457cffd4fbba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_change_first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91bc3fa4-b329-4b66-8f8b-95c9d759bf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_change_first_name</value>
      <webElementGuid>07f69697-6cc7-4b37-86c6-2b709020362c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>0e907a89-3831-4559-b7ab-8d99f215d9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Change
                </value>
      <webElementGuid>1fa75f7a-5e65-4c77-bf71-fbef7426b82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_change_first_name&quot;)</value>
      <webElementGuid>94fc4c0d-2e13-45c4-9233-82491fe779c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='profile_change_first_name']</value>
      <webElementGuid>00af3185-b352-4d8a-ba5f-cea3c0fe8cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/table[2]/tbody/tr[3]/td[3]/a</value>
      <webElementGuid>783a9932-f2e5-46ee-8570-74463c6253e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My_Name_4977'])[1]/following::a[1]</value>
      <webElementGuid>e61ed7a1-5f60-41d7-b6f1-5d028a9a3d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::a[1]</value>
      <webElementGuid>bf09f67e-0b6c-4020-99b0-9259e100d39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::a[1]</value>
      <webElementGuid>55864cd1-76eb-4812-b1fe-11aa312666d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/a</value>
      <webElementGuid>4beb7cb8-ddc5-4394-a81c-58407a5befe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'profile_change_first_name' and (text() = '
                    Change
                ' or . = '
                    Change
                ')]</value>
      <webElementGuid>11e1dae6-82e7-4be5-b7b0-6c8104152c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
