<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Details_Manage_E-mail</name>
   <tag></tag>
   <elementGuidId>d51d7c88-1273-43e5-b4b0-626ab83cad22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[2]/tbody/tr[6]/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profile_manage_emails</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c308de99-0a6b-416b-8a7a-90e06484162f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_manage_emails</value>
      <webElementGuid>2394d4b3-140a-4839-a94b-67ef0fddb47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>48730e1c-af30-4084-9374-0a70f5d518ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Manage
                </value>
      <webElementGuid>a5d787de-8c5c-4843-b5eb-656fb3b1f9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_manage_emails&quot;)</value>
      <webElementGuid>9bb46db1-948d-4654-98e8-e99ffd1e4049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='profile_manage_emails']</value>
      <webElementGuid>b77a1e38-3454-451c-ab5a-441fd2655c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/table[2]/tbody/tr[6]/td[3]/a</value>
      <webElementGuid>a1caa22e-fff9-414a-aced-f22606627079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Mail'])[1]/following::a[1]</value>
      <webElementGuid>b114e634-49e9-4112-99c9-937646c0fed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[9]/following::a[1]</value>
      <webElementGuid>80e93db7-264f-44b2-9f2a-48bf7065eb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation Date'])[1]/preceding::a[1]</value>
      <webElementGuid>9a35073a-41b6-4703-9afa-b80e77c42865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[6]/td[3]/a</value>
      <webElementGuid>1d439bfb-f2ae-4a51-95f5-dfe3c299cb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'profile_manage_emails' and (text() = '
                    Manage
                ' or . = '
                    Manage
                ')]</value>
      <webElementGuid>20219499-f9f2-4068-844c-acfc4393558d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
