<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>New_Title_Verification</name>
   <tag></tag>
   <elementGuidId>43479cfe-5783-4e24-9577-048ae7deaea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[2]/tbody/tr[2]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>682279f2-c0f5-4332-8fb5-9541ed5be765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_title</value>
      <webElementGuid>524f7ad9-4f30-4f5c-9201-d5023d6d0727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-static</value>
      <webElementGuid>848622f1-1617-40d2-91c2-e6ad013b1ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I&amp;amp;#39;m testing the details tab</value>
      <webElementGuid>f9c14a2c-ca80-462e-b62c-19cf595c0c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_title&quot;)</value>
      <webElementGuid>a116dfdc-dae9-4d77-8f55-b69020799512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='profile_title']</value>
      <webElementGuid>5aea9998-a57c-470e-8d35-e02cc118cf6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/table[2]/tbody/tr[2]/td[2]</value>
      <webElementGuid>45fac050-77bf-4d99-a91d-7c4ce101de8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::td[1]</value>
      <webElementGuid>322a8941-253f-4f49-9b8a-5b3ce39ab346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade'])[2]/following::td[3]</value>
      <webElementGuid>3c439a38-f043-453d-b0a7-8c960bc1ff83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[6]/preceding::td[1]</value>
      <webElementGuid>54aa3f32-414c-4e69-bdb2-2e719aec28fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::td[2]</value>
      <webElementGuid>5974173d-0199-4823-be58-53c048a8149e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I&amp;amp;#39;m testing the details tab']/parent::*</value>
      <webElementGuid>6e191300-69dc-4683-81ce-3fa572a5faa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[2]/td[2]</value>
      <webElementGuid>b70f1ad3-049e-4c7b-b757-30c00bd41f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'profile_title' and (text() = 'I&amp;amp;#39;m testing the details tab' or . = 'I&amp;amp;#39;m testing the details tab')]</value>
      <webElementGuid>773f3656-f1cd-465b-8dfa-50553a713761</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
