<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_new_name</name>
   <tag></tag>
   <elementGuidId>9bcf8b4c-7910-4873-b998-654b5ec637b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[2]/tbody/tr[3]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7bb7ea8b-4cdb-4378-9b41-7812563bfbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_first_name</value>
      <webElementGuid>8ff23a50-f0bc-453f-ba55-7c145ef07fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-static</value>
      <webElementGuid>07d21454-a8a3-4869-9423-beb9f674fc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New_Name_6384</value>
      <webElementGuid>5df99cd2-cccb-4855-9e52-c6800faac92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_first_name&quot;)</value>
      <webElementGuid>6f7ee63b-2823-4c66-ace0-2518bb4c56af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='profile_first_name']</value>
      <webElementGuid>469b86a8-ec4d-4771-893e-491d805269b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/table[2]/tbody/tr[3]/td[2]</value>
      <webElementGuid>a35bf623-8f3f-4068-a46d-9248475a9284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::td[1]</value>
      <webElementGuid>f9127f40-f510-432c-9a81-66ae7818916e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[6]/following::td[2]</value>
      <webElementGuid>45b47a8a-b77d-4820-ad4a-149691027376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[7]/preceding::td[1]</value>
      <webElementGuid>6f69cbd8-00b7-40e5-9f22-6936c1d0a219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::td[2]</value>
      <webElementGuid>b3fbabfa-aa69-45d4-a055-dff47c59da12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New_Name_6384']/parent::*</value>
      <webElementGuid>9c8eb520-b807-4508-9820-8796c49b3e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[3]/td[2]</value>
      <webElementGuid>ccd1424f-d4ae-4de0-a1b8-92508ea78d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'profile_first_name' and (text() = 'New_Name_6384' or . = 'New_Name_6384')]</value>
      <webElementGuid>8dd504c2-7e40-433d-8e26-9e8606820a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
