<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verification_Web</name>
   <tag></tag>
   <elementGuidId>c62e5a56-4687-4597-ad37-9c7fc18f07e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.pica-overflow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id='profile_devices_table']/tbody/tr[@id])[1]/td[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>62d4bbd3-2205-4541-af92-6132421f2bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-overflow</value>
      <webElementGuid>c9d04c0b-4a79-4c8c-9d75-2c0ce0c7f3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Web</value>
      <webElementGuid>e0b5bc2b-1e6e-4f02-9962-0c1ec5d5ec0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_377053204&quot;)/td[@class=&quot;pica-overflow&quot;]</value>
      <webElementGuid>92ff4dbd-0bcf-41f5-85db-258d9a7f2889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_377053204']/td[2]</value>
      <webElementGuid>3d2fc345-892f-4510-9b72-6254ff7bfeeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/following::td[2]</value>
      <webElementGuid>5c494bb7-947b-4d69-a820-3b10e080e0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::td[2]</value>
      <webElementGuid>6a3f882f-e5b2-44ad-9b5e-94557d89c2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[3]/preceding::td[1]</value>
      <webElementGuid>08b24692-855c-4802-be23-31247f2ea2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send to E-mail'])[1]/preceding::td[4]</value>
      <webElementGuid>40f62b6b-6b25-49ad-90be-8b51d7270f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Web']/parent::*</value>
      <webElementGuid>9636bb33-048d-44c6-adba-5385e49fddbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr/td[2]</value>
      <webElementGuid>2ab00dcb-0a0d-4e9b-89e7-778889b541c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Web' or . = 'Web')]</value>
      <webElementGuid>5f0526f9-b393-4d50-a67d-ff35e7c55c09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
