<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shareLink</name>
   <tag></tag>
   <elementGuidId>c0ad62b2-49eb-4b50-acc8-8e8bf430ca73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#share_create_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button/lang[text()='Create link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88de0d0e-c08b-4ece-8c4e-7e7e833e707c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>share_create_link</value>
      <webElementGuid>9a04a677-cab4-434c-9e00-28d4729e9122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b99346ba-f286-4402-90f7-44b285a40034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-left</value>
      <webElementGuid>4e431dbb-8533-4ad8-9dcc-6fdc19a9b65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Create link
                </value>
      <webElementGuid>50730ee5-326f-4d7f-b781-b59128c51168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share_create_link&quot;)</value>
      <webElementGuid>2d35e1f5-4948-4def-bdeb-810dc7bfeaed</webElementGuid>
   </webElementProperties>
</WebElementEntity>
