<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Details_Enter a new First Name</name>
   <tag></tag>
   <elementGuidId>bbdb66da-f3b4-4c77-bfd7-c185ff408de9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_input_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[11]/div/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8afde5ea-2055-43f0-9871-53c888aa9191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_input_text</value>
      <webElementGuid>14f0dbb4-4315-42aa-a1be-268bd6c69482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c08f5d01-c6e4-462f-befc-637476338e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pencil</value>
      <webElementGuid>edd9399d-a3aa-4c0b-b7e0-fd01093ca7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>157e68e6-36d7-4328-9473-d57e0615c486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_input</value>
      <webElementGuid>4cf24022-f15f-41ba-a2ef-1477d815fe6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert here</value>
      <webElementGuid>77fd576a-4506-462c-a3b2-f4a26aa28ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_input_text&quot;)</value>
      <webElementGuid>698fdcb8-c4b3-4716-9155-7366459ba376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_input_text']</value>
      <webElementGuid>6ade1afb-5b95-4850-999a-2b306a4d2a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_input_dialog']/div/div/div[2]/div/input</value>
      <webElementGuid>d0cb69d1-f9f8-46b0-846c-bdd1a857b299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/input</value>
      <webElementGuid>979986f0-a388-49cf-9103-1c868d0ee9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_input_text' and @name = 'pencil' and @type = 'text' and @placeholder = 'Insert here']</value>
      <webElementGuid>45dbbb79-2eb9-4917-b571-f3cb191c7cc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
