<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept</name>
   <tag></tag>
   <elementGuidId>47a10f63-9d3b-4874-9372-719f6e67cee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.pf-cc-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@class,'pf-cc-no')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
