<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Serverstandort</name>
   <tag></tag>
   <elementGuidId>10f25af2-725d-45fb-b36c-415b69a3ccbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='post-7084']/div/div/div/div/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.fusion-responsive-typography-calculated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>d9b2aca2-e16a-461d-8b18-d000e2f9fb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fontsize</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>16e8c9ed-5721-4c4f-a4f8-a66d094646eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lineheight</name>
      <type>Main</type>
      <value>23.94px</value>
      <webElementGuid>1595b55d-e5e5-4a7e-9f0c-9a074540ee2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fusion-responsive-typography-calculated</value>
      <webElementGuid>701d2af8-dc92-427b-9bf0-69bd2dcf8128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Serverstandort:</value>
      <webElementGuid>c863987a-e99e-4bb6-b2e6-f889a58fcd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-7084&quot;)/div[@class=&quot;post-content&quot;]/div[@class=&quot;fusion-fullwidth fullwidth-box fusion-builder-row-1 hundred-percent-fullwidth non-hundred-percent-height-scrolling&quot;]/div[@class=&quot;fusion-builder-row fusion-row&quot;]/div[@class=&quot;fusion-layout-column fusion_builder_column fusion-builder-column-0 fusion_builder_column_2_3 2_3 fusion-two-third fusion-column-first&quot;]/div[@class=&quot;fusion-column-wrapper fusion-flex-column-wrapper-legacy&quot;]/div[@class=&quot;fusion-text fusion-text-1&quot;]/h3[@class=&quot;fusion-responsive-typography-calculated&quot;]</value>
      <webElementGuid>83b54e75-96cb-4031-8262-455cd7c93693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-7084']/div/div/div/div/div/div/h3</value>
      <webElementGuid>2506acbc-7f90-4f82-8e7a-6332719269d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='adminpf'])[1]/following::h3[1]</value>
      <webElementGuid>23901a5e-5f30-4405-afbb-9d9ed17a606a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datenschutzerklärung'])[2]/following::h3[1]</value>
      <webElementGuid>4fcd14ed-df9f-4eba-8f4f-25290659e76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datenschutzerklärung'])[3]/preceding::h3[1]</value>
      <webElementGuid>4975a5b8-afec-49a8-9348-a22fd3f3dd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Erfassung allgemeiner Informationen'])[1]/preceding::h3[1]</value>
      <webElementGuid>997fef05-f3bb-4511-85bd-2dd1ba05da4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Serverstandort:']/parent::*</value>
      <webElementGuid>753cfd9b-9ca9-4d1f-84eb-e2fba0bfa64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>10826303-ef9b-4222-af7c-7887793742f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Serverstandort:' or . = 'Serverstandort:')]</value>
      <webElementGuid>f0fcf365-e290-4bc6-9d2f-311abe5245a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
