<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_recycle</name>
   <tag></tag>
   <elementGuidId>5f861b32-65cb-42e2-a73b-753d678f257e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[4]/td/a/lang</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pica-glyph.show.glyphicons.glyphicons-recycle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0e924b6-46c4-4da9-be7a-81e822d1671f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-glyph show glyphicons glyphicons-recycle</value>
      <webElementGuid>299a8a0e-39f7-4487-9f05-74c86f8e0adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_menu&quot;)/table[1]/tbody[1]/tr[3]/td[@class=&quot;text-center&quot;]/a[1]/span[@class=&quot;pica-glyph show glyphicons glyphicons-recycle&quot;]</value>
      <webElementGuid>52590e2c-89ca-45a4-a780-a7e1aef8e9ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_menu']/table/tbody/tr[3]/td/a/span</value>
      <webElementGuid>7761f11b-b5cc-416c-a93e-f07979d06190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/a/span</value>
      <webElementGuid>aa0d7de3-9f52-4d94-b615-233d1f22003a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
