<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Grid_pica-icon pica-glyph glyphicon gl_10dee2</name>
   <tag></tag>
   <elementGuidId>5191916c-d66e-4d3c-8b33-a82430c97eab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='storage_59869090']/td/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pica-icon.pica-glyph.glyphicon.glyphicon-ok-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>96c43468-eaaf-469c-a754-31bc23fc5509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-icon pica-glyph glyphicon glyphicon-ok-circle</value>
      <webElementGuid>026de517-f4a9-4864-9884-4ec9213d00ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;storage_59869090&quot;)/td[@class=&quot;text-center pica-icon-column&quot;]/span[@class=&quot;pica-icon pica-glyph glyphicon glyphicon-ok-circle&quot;]</value>
      <webElementGuid>0c48b589-abfe-4b5c-baa5-8e1ce9c93dd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='storage_59869090']/td/span</value>
      <webElementGuid>55a5a248-5e7d-4dce-b1bd-f1855dec73f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>ade23b2d-bc5c-48a2-8f70-b312cb226d40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
