<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Notes_glyphicons glyphicons-show-thumb_16a0e8</name>
   <tag></tag>
   <elementGuidId>66b6a698-d1b9-4b26-8fe4-1c1d974a9b2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pica-vmtable-toggle-list > span.glyphicons.glyphicons-show-thumbnails-with-lines.pica-glyph</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='storages_table']/thead[2]/tr/th[7]/div/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>980b4448-1cd5-432f-9183-fdc77c04c2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-show-thumbnails-with-lines pica-glyph</value>
      <webElementGuid>29506d88-6661-41b8-ac9b-7642e2f971fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;storages_table&quot;)/thead[2]/tr[1]/th[@class=&quot;pica-icon-column&quot;]/div[@class=&quot;pica-vmtable-toggle pica-inline pica-table-selection-hide dropdown open&quot;]/ul[@class=&quot;pica-arrow-right dropdown-menu dropdown-menu-right&quot;]/li[1]/a[@class=&quot;pica-vmtable-toggle-list&quot;]/span[@class=&quot;glyphicons glyphicons-show-thumbnails-with-lines pica-glyph&quot;]</value>
      <webElementGuid>2b5a0beb-02ac-40f2-bb00-d99e0401f41b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='storages_table']/thead[2]/tr/th[7]/div/ul/li/a/span</value>
      <webElementGuid>2fb62b8f-4d85-4527-ba0c-1dfebe136df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/div/ul/li/a/span</value>
      <webElementGuid>069b7fd0-3364-449b-8bb8-5a848a3158ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
