<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Storage_menu</name>
   <tag></tag>
   <elementGuidId>74414e6a-36cc-49dd-b389-8aa056192a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.glyphicons.glyphicons-show-thumbnails-with-lines.pica-vmtable-toggle-list.pica-glyph</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[7]/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ebc0ab24-78a1-4ed8-bee6-1758a8525c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-show-thumbnails-with-lines pica-vmtable-toggle-list pica-glyph</value>
      <webElementGuid>362c71bc-caa1-4470-9541-9a1386082fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;storages_table&quot;)/thead[2]/tr[1]/th[@class=&quot;pica-icon-column&quot;]/div[@class=&quot;pica-vmtable-toggle pica-inline pica-table-selection-hide dropdown open&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;glyphicons glyphicons-show-thumbnails-with-lines pica-vmtable-toggle-list pica-glyph&quot;]</value>
      <webElementGuid>3fd12518-1ca2-4866-a6c3-810b8cf19fc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='storages_table']/thead[2]/tr/th[7]/div/a/span</value>
      <webElementGuid>9e9c3828-b525-49e2-8087-c83c6454f7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/div/a/span</value>
      <webElementGuid>65540d52-8d4a-4407-a55b-4855b998fe5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
