<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Grid_text-center pica-icon-column</name>
   <tag></tag>
   <elementGuidId>afbfda46-75ff-48d2-a91f-6af793a04aaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.text-center.pica-icon-column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='storage_59869090']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>18cafc10-485b-42bb-b0b1-6606b534d383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center pica-icon-column</value>
      <webElementGuid>3664baa9-5499-4a48-b725-f6e68d87b4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;storage_59869090&quot;)/td[@class=&quot;text-center pica-icon-column&quot;]</value>
      <webElementGuid>75396882-ca7a-45b6-8f39-a5e8a4d93fae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='storage_59869090']/td</value>
      <webElementGuid>9a13c542-b151-4512-9850-8afb79aae6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grid'])[1]/following::td[1]</value>
      <webElementGuid>1db71dfc-a633-4113-af30-efaee6fc7d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List'])[1]/following::td[1]</value>
      <webElementGuid>86201bb9-6d91-4144-9821-ce7987a1568d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/home/adama/storage1'])[1]/preceding::td[1]</value>
      <webElementGuid>27bbce7e-20f4-41f3-aa55-d46c96f8fdbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/preceding::td[7]</value>
      <webElementGuid>904783fe-cb06-457c-b70e-56665004f0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td</value>
      <webElementGuid>63c5e991-3e3f-460b-bd57-ebc1b779c03c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
