<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change</name>
   <tag></tag>
   <elementGuidId>c59e0046-6655-4b26-b5ed-2ac6b988a89c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_change_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='profile_change_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e2d1bb27-eaa2-4fd2-907e-f1cb5fd1ca39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_change_password</value>
      <webElementGuid>7b984777-995a-4d58-b98e-bad4e2d8ea92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>0a6f486c-d3c1-44aa-b98a-ab23723c1ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Change
                    </value>
      <webElementGuid>b4aea903-9e63-4e0b-9f37-a86447dba09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_change_password&quot;)</value>
      <webElementGuid>ef1ccb53-934a-440c-bc84-94599345ebb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='profile_change_password']</value>
      <webElementGuid>84246c79-23f6-44e2-a90e-e0fce11c1da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/table/tbody/tr[7]/td[2]/a</value>
      <webElementGuid>bf72f020-625e-4dc9-95ab-3cfb4e21377b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>c25e652a-b135-4b4f-ae30-7ba7a7666931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'profile_change_password' and (text() = '
                        Change
                    ' or . = '
                        Change
                    ')]</value>
      <webElementGuid>cca5362a-8da4-4de8-9c4c-88e337ae3720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
