<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manage</name>
   <tag></tag>
   <elementGuidId>8866b6b1-5fd2-4816-ab23-7dccf0683239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_manage_emails</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='profile_manage_emails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8aecbe2-1b08-4ffa-b6ff-d9ac5223fd66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_manage_emails</value>
      <webElementGuid>4b04746d-c40c-41fe-abcb-7870492527c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>f828d9d1-9358-401a-be2e-95b43a2f7b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Manage
                    </value>
      <webElementGuid>f7a52d3f-c78c-4384-8860-380a4d1c9793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_manage_emails&quot;)</value>
      <webElementGuid>d03e8c31-4836-416d-9c0f-581d055fa35f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='profile_manage_emails']</value>
      <webElementGuid>e82bc9b7-00dd-4b0d-83dc-47d4da2a9670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/table/tbody/tr[8]/td[3]/a</value>
      <webElementGuid>872f66e5-df94-47df-8d3a-65bbedc0df5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[3]/a</value>
      <webElementGuid>53f59b63-0e9f-42d0-b102-088203976578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'profile_manage_emails' and (text() = '
                        Manage
                    ' or . = '
                        Manage
                    ')]</value>
      <webElementGuid>44911d27-76d6-40a2-8061-783ced010205</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
