<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pencil</name>
   <tag></tag>
   <elementGuidId>8d99ff3c-ce05-4832-b8ce-2513434495e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_input_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pica_input_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23bb439e-608c-49c9-b53e-cdaa1520e7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_input_text</value>
      <webElementGuid>57c2f7ea-272a-4ff0-9a44-3d48aae833a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d0a885cd-ef50-417e-8b0e-2812a181e9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pencil</value>
      <webElementGuid>377c325a-c0be-452c-88cc-c0d8750ab0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d0eb07f-a125-46bd-b999-61b9929a740f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_input</value>
      <webElementGuid>d0dfcc51-7433-47b0-bc98-3cba4b8b4ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert here</value>
      <webElementGuid>d88c7c1f-b50d-4db5-9d49-a80040730aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_input_text&quot;)</value>
      <webElementGuid>6b9a58a1-7f62-4a3b-848e-8beb3eb46133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_input_text']</value>
      <webElementGuid>9af6ce01-6345-4736-a211-14cd134a43e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_input_dialog']/div/div/div[2]/div/input</value>
      <webElementGuid>2ccda9a2-09c2-4128-a3dc-ffea9da43db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/input</value>
      <webElementGuid>756dd719-a402-447e-94cf-983cd3c07286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_input_text' and @name = 'pencil' and @type = 'text' and @placeholder = 'Insert here']</value>
      <webElementGuid>a510d404-de67-4f8a-9f9a-1029b64b7b08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
