<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Configure</name>
   <tag></tag>
   <elementGuidId>ab56c0b8-b61e-4fdd-b6ec-ed24db6abcde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button-customization']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-customization</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70a1777d-d4e4-4379-8b27-ccfe4231581b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-customization</value>
      <webElementGuid>896562b1-7043-4b06-a0b1-f808f8de58fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pica-card-button</value>
      <webElementGuid>d92a0ae1-01d2-4904-b59d-0855ffb99f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Configure</value>
      <webElementGuid>3b149502-6bd3-42b0-a1e3-2adc29118b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-customization&quot;)</value>
      <webElementGuid>64da1734-2ac0-459c-8746-e83d0a433494</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='button-customization']</value>
      <webElementGuid>4cabd0e7-e318-48c6-9e0c-8a1e2df2e898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div/div[4]/div/a</value>
      <webElementGuid>cf5ba524-8fed-40a2-bc50-0f1952ae7f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Configure')])[4]</value>
      <webElementGuid>82a6ddef-6ff2-4332-b507-a33951cb7075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>eb17882a-580b-43fb-a1f1-8b8090190673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'button-customization' and (text() = 'Configure' or . = 'Configure')]</value>
      <webElementGuid>649d94a3-7eef-49d4-9720-2a09d8137993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
