<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Cancel</name>
   <tag></tag>
   <elementGuidId>3de8da28-811f-4655-9b09-62df739d0f0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='button_cancel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;button_cancel&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>f7e041e1-4460-473c-8d47-6891026ec0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button_cancel</value>
      <webElementGuid>830ad54e-ad1d-4704-b34b-8923832b95f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>d37cda64-f305-47d8-9909-c6e698c376a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_preference_dialog&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/button[@class=&quot;btn btn-default btn-cancel&quot;]/lang[1]</value>
      <webElementGuid>c4ad5504-2352-4e7f-b0e5-2bd8f6d95e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='button_cancel']</value>
      <webElementGuid>cf14196f-c6bd-4339-b1cf-f6d9c8d18b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_preference_dialog']/div/div/div[3]/div/div/button[2]/lang</value>
      <webElementGuid>39d806ac-151f-43ea-99ba-4f7166edeb4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/lang</value>
      <webElementGuid>af4c6389-d695-4b09-8215-66f3cd4ac55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'button_cancel' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>cb19cc2f-5274-4531-b18f-180d3802ac97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
