<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>accept_invitation</name>
   <tag></tag>
   <elementGuidId>9b9a9fa9-ce65-4392-9c1e-2f8836ddbfcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='button_accept']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;button_accept&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>b4063ca1-fdca-4b80-9f37-71acbedd1970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button_accept</value>
      <webElementGuid>0929816f-45ae-4e2f-9ed7-f192a5a99739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akzeptieren</value>
      <webElementGuid>44000e40-3b33-4fcc-8b67-eec54b4cd05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invitation_accept&quot;)/lang[1]</value>
      <webElementGuid>09da660e-aaa0-44b1-952e-7fd12944d26f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='button_accept']</value>
      <webElementGuid>529ad897-f09e-4c82-ad76-de00c2f6f6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='invitation_accept']/lang</value>
      <webElementGuid>bd805263-7e3b-4067-9ac5-fdfef3a08f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Um diesen gemeinsamen Ordner zu sehen, nehmen Sie bitte zuerst die Einladung an.'])[1]/following::lang[1]</value>
      <webElementGuid>7ac72933-a881-45f3-a1ed-5b5384307cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Einladung'])[1]/following::lang[1]</value>
      <webElementGuid>796cce57-a8a4-4a93-b76c-fb3df123a499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ablehnen'])[2]/preceding::lang[1]</value>
      <webElementGuid>322c8a1e-760e-4436-b2ef-9b2274d67da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[7]/preceding::lang[2]</value>
      <webElementGuid>81dbf609-6d2a-42d5-a9bb-a9df66a537a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[3]/button/lang</value>
      <webElementGuid>23ea9aa8-1eb4-4bee-b5a0-a093d3a83147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'button_accept' and (text() = 'Akzeptieren' or . = 'Akzeptieren')]</value>
      <webElementGuid>2ffbf9d7-f682-4b73-bbc7-2499442e4096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
