<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonAddEmail</name>
   <tag></tag>
   <elementGuidId>c0e47c6e-73ad-4941-b119-1fcc4ca12195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='share_buttons']//button[contains(@class,'pica-taginput-button')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56670d6d-2693-4227-ba5e-d4722b9a5f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-taginput-button btn btn-secondary</value>
      <webElementGuid>33c04313-7225-45e5-8457-fe980a79f94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;share_buttons&quot;)/button[@class=&quot;pica-taginput-button btn btn-secondary&quot;]</value>
      <webElementGuid>20ea6f9b-fcb1-4143-a0b5-0553db836b68</webElementGuid>
   </webElementProperties>
</WebElementEntity>
