<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_accpet_decline_invitation</name>
   <tag></tag>
   <elementGuidId>10777198-9b23-4bdf-b016-4c630e83b3f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='Object_1057709570']/td[7]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.glyphicons.glyphicons-directions.pica-glyph</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cae47e03-7bf1-4fa4-b431-b06e3453cdff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-directions pica-glyph</value>
      <webElementGuid>9cd54068-a6e5-434f-88da-bf99dfc4d78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_1057709570&quot;)/td[@class=&quot;pica-icon-column&quot;]/div[@class=&quot;pica-inline dropdown&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;glyphicons glyphicons-directions pica-glyph&quot;]</value>
      <webElementGuid>dd1ac8b2-b85e-4e83-93e7-160cc96aca34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_1057709570']/td[7]/div/a/span</value>
      <webElementGuid>755cdde9-7d19-416e-9e43-8c9e09f0ec8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/a/span</value>
      <webElementGuid>e8ad7378-6f1d-4405-b5f9-265603f90c08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
