<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_invitation_Accept</name>
   <tag></tag>
   <elementGuidId>52c0988a-d429-4a1f-b2e4-04809cb75583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#invitation_accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='invitation_accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72332a4d-caf7-42f3-a273-d5a9c3028f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invitation_accept</value>
      <webElementGuid>25391688-267c-4b84-bc7b-85aee48ea4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9daeeca2-0f40-4dfb-8dae-82d4d05594c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>60f44638-b3b9-4ba7-ae11-b4c30fa0fb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>8497d5bf-e30f-40ed-863b-b6dd75c19460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Accept
                </value>
      <webElementGuid>70d50931-caf1-47ba-87d7-f9b529076fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invitation_accept&quot;)</value>
      <webElementGuid>7cc4cd21-4b91-44fc-bfc8-84076ae1a40b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='invitation_accept']</value>
      <webElementGuid>db106bb2-7462-4280-8746-477fb1ed9eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_invitation_dialog']/div/div/div[3]/button</value>
      <webElementGuid>c75719de-0b3e-476c-b1c5-967be190f04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To view this shared folder please accept the invitation first.'])[1]/following::button[1]</value>
      <webElementGuid>389d9c0a-e649-401b-ad65-265e76ba752a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invitation'])[1]/following::button[1]</value>
      <webElementGuid>a5008753-eb58-4453-9d63-935dd28d9efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[2]/preceding::button[1]</value>
      <webElementGuid>a02937e8-8138-4061-ace1-761c6d99fac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[3]/button</value>
      <webElementGuid>42d098ce-2b79-4d0e-bf8a-2c1fa2a69d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'invitation_accept' and @type = 'button' and (text() = '
                    Accept
                ' or . = '
                    Accept
                ')]</value>
      <webElementGuid>9cb27b65-673f-49f5-b9c3-3aeafa83df30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
