<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close_upload_file</name>
   <tag></tag>
   <elementGuidId>354c4ba0-f4df-412b-9461-d3650ba4dcf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#upload_stop_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='upload_stop_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95ac002e-e3d0-4b4e-84c1-3d961464e452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>upload_stop_button</value>
      <webElementGuid>4c8e25ec-e920-4164-a8d1-f5e0ab403d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36e45a1b-52ee-4354-a426-469b5ed8dfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>3832806b-b0d6-4f60-8aa2-e8e554a6e6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Close
                        </value>
      <webElementGuid>f10708ef-1ed8-446f-9919-9c9515ea61f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upload_stop_button&quot;)</value>
      <webElementGuid>e782a412-e6af-4a98-a078-5d789d7adda1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='upload_stop_button']</value>
      <webElementGuid>3ff77e9c-8a6f-477a-aaea-57f398cccfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_upload_dialog']/div/div/div[3]/div/div[2]/button[2]</value>
      <webElementGuid>fe5d7ecc-c9e4-4916-a881-1800a9b813ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[2]/following::button[1]</value>
      <webElementGuid>17b21b24-9d23-4cb3-bbfc-c562fee93b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add directory'])[1]/following::button[2]</value>
      <webElementGuid>7c8404c2-5250-48c8-b1cc-af6fd43f7e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[6]/preceding::button[1]</value>
      <webElementGuid>67d3f03f-8ca3-4298-9ac5-f11da40a970e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/button[2]</value>
      <webElementGuid>509846de-244f-4b6f-9c21-35dc61bd6408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'upload_stop_button' and @type = 'button' and (text() = '
                            Close
                        ' or . = '
                            Close
                        ')]</value>
      <webElementGuid>64916e38-9905-4966-8f51-5708fa94b2f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
