<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>manage_invitation</name>
   <tag></tag>
   <elementGuidId>dc509807-2734-46a6-8d6e-18158edcc616</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.glyphicons.glyphicons-directions.pica-glyph</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id='files_files_table']//tr[contains(@class,'pica-table-selection-disabled')]//a[contains(@class,'dropdown-toggle')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2c401de9-152d-41ee-9900-b47400e7575d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-directions pica-glyph</value>
      <webElementGuid>47d8deb8-0255-461b-ab4a-e172e052670b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_1203562674&quot;)/td[@class=&quot;pica-icon-column&quot;]/div[@class=&quot;pica-inline dropdown&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;glyphicons glyphicons-directions pica-glyph&quot;]</value>
      <webElementGuid>ed0b904c-b7d2-4aa2-a2ea-12a7dec4195c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_1203562674']/td[7]/div/a/span</value>
      <webElementGuid>6079064f-82b9-4da3-8db0-0585f39a6d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/a/span</value>
      <webElementGuid>7e41fa3a-33e9-4a26-976f-7ae8cfbdb37e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
