<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rename</name>
   <tag></tag>
   <elementGuidId>3fe28c11-736f-4edd-97fd-47ad511e382d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/a[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pica-table-selection-single.files-ui-rename > span.pica-glyph.glyphicons.glyphicons-edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>abef8c82-1421-4d07-b779-359836be1f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-glyph glyphicons glyphicons-edit</value>
      <webElementGuid>c0bb1fc7-9dc0-4c8f-acad-27ed59b043f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;files_select_header&quot;)/tr[1]/th[@class=&quot;text-right&quot;]/div[@class=&quot;pica-table-selection-context pica-inline hidden-xs text-right&quot;]/a[@class=&quot;pica-table-selection-single files-ui-rename&quot;]/span[@class=&quot;pica-glyph glyphicons glyphicons-edit&quot;]</value>
      <webElementGuid>88b749b4-5e6b-4ff3-b8ad-4b20b97561c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//thead[@id='files_select_header']/tr/th[3]/div[2]/a[2]/span</value>
      <webElementGuid>d43c54cf-d0e7-4a85-a48e-8c597608d4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]/span</value>
      <webElementGuid>cefefb5c-a0f3-4414-b5da-e264e8c3f2ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
