<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Change_Password</name>
   <tag></tag>
   <elementGuidId>8b20d874-103d-4f14-b217-7372d2422dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_change_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[3]/table[1]/tbody/tr[4]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5941b2e2-33e4-4c75-8e32-cfcf0934e888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_change_password</value>
      <webElementGuid>ee762875-0ec8-47da-8eb2-634839f5c445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>b87f73a2-a8d3-490c-82c2-e226b6e940f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Change
                    </value>
      <webElementGuid>366353f6-540d-4937-b91e-5addd278f331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_change_password&quot;)</value>
      <webElementGuid>e1587d22-a23a-4fd2-b0c9-1340ab6cd750</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='profile_change_password']</value>
      <webElementGuid>2773250f-1fbe-48f4-8f22-f2d5f1098158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/table/tbody/tr[4]/td[2]/a</value>
      <webElementGuid>1556c239-efb8-4414-bf42-13193db81d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>9ad04f82-bd67-4ef0-a708-ab1f9e3bc4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[3]/following::a[1]</value>
      <webElementGuid>68a823be-181c-471d-ab60-7cbc0a26d3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/preceding::a[1]</value>
      <webElementGuid>95fd3aad-774e-4da8-93bd-6e74d1d36961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>b15f03e5-34e8-4055-95f6-09c25bda597d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'profile_change_password' and (text() = '
                        Change
                    ' or . = '
                        Change
                    ')]</value>
      <webElementGuid>0c4cd3c6-5d45-4ced-8b41-032147ff5884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
