<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Langue</name>
   <tag></tag>
   <elementGuidId>4535b58b-51fb-4979-a6e0-11d752b34687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_language</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[6]/div/div/div[2]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>818ca0e7-5b64-42a8-ae39-a595324a76b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>languge</value>
      <webElementGuid>04a205a2-806c-4401-9ef0-373fc9ae2631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_language</value>
      <webElementGuid>a343d304-709c-442e-834b-9b8b45f0fc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e762d340-751b-43b8-a583-141e675379fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    English
                                                    Deutsch
                                            </value>
      <webElementGuid>fd1dbb61-9602-44ed-b599-7c0031c1655a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_language&quot;)</value>
      <webElementGuid>019eba1a-34df-40dc-b978-fe8d295e921c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='profile_language']</value>
      <webElementGuid>cf8ee25e-2a68-4f7b-8c5e-0b23b70349e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile_language_dialog']/div/div/div[2]/div/select</value>
      <webElementGuid>8bbbbbef-e67b-455a-bc15-743d558ed507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a new Language'])[1]/following::select[1]</value>
      <webElementGuid>a5064d00-a015-459f-90d5-a1acc3b9d012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[20]/following::select[1]</value>
      <webElementGuid>675cee1f-ff4a-4351-910d-179f6d307707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[21]/preceding::select[1]</value>
      <webElementGuid>618c297e-6867-48a9-8585-7ff58f51917e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/preceding::select[1]</value>
      <webElementGuid>00fecfda-9d1b-4967-b10c-df6014e73cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4a4b0877-09a2-48ec-b1e8-4741edd35044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'languge' and @id = 'profile_language' and (text() = '
                                                    English
                                                    Deutsch
                                            ' or . = '
                                                    English
                                                    Deutsch
                                            ')]</value>
      <webElementGuid>50aa5462-02fd-4054-8de3-e043654b11dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
