<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Set_New_Password</name>
   <tag></tag>
   <elementGuidId>cf7c2e74-3cad-4ff9-942b-5d8b82004107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_password_new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[5]/div/div/div[2]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6cd9f1e-5d4f-42c8-aefd-9f0206151ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_password_new</value>
      <webElementGuid>fb3125ff-e59f-462c-a5b1-3d897d416e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-password form-control</value>
      <webElementGuid>0499a962-0a34-4536-ac09-7c7bf397dc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9557357e-8489-480e-837c-6f59b1e5aaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_password_new</value>
      <webElementGuid>09a9979d-dff0-4308-99f0-4bbad43cad94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e8c784dc-3cf2-48ed-b431-26b7dc78765f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New password</value>
      <webElementGuid>66dcec99-a047-4892-b0b1-8528a2f452e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>popover</value>
      <webElementGuid>c70031e5-fe63-496c-92c3-8bc4d17610f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>db936a8c-1940-429a-a398-61c7bebd7d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>96baa8e0-fe00-45b6-a4a0-138bc0739bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trigger</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>19e44e55-9860-4610-9a95-2c66aa622160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a6e668ef-dac5-4aff-beea-878dd850ed63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-content</name>
      <type>Main</type>
      <value>&lt;h5>&lt;lang name=&quot;password_policy_uppercase&quot; class=&quot;profile_password_policy_uppercase pica-space-right-small label label-danger&quot;>At least one upper case letter&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_lowercase&quot; class=&quot;profile_password_policy_lowercase pica-space-right-small label label-danger&quot;>At least one lower case letter&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_digit&quot; class=&quot;profile_password_policy_digit pica-space-right-small label label-danger&quot;>At least one number&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_special&quot; class=&quot;profile_password_policy_special pica-space-right-small label label-danger&quot;>At least one special character&lt;/lang>&lt;/h5>&lt;h5>&lt;lang name=&quot;password_policy_count&quot; class=&quot;profile_password_policy_count pica-space-right-small label label-danger&quot;>At least 8 characters&lt;/lang>&lt;/h5></value>
      <webElementGuid>99b57b49-b636-4694-8b64-bbd437b45194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Password policy</value>
      <webElementGuid>9038f3ab-7b20-4f99-8bed-a255c7bded61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>popover213580</value>
      <webElementGuid>3f851bd6-023e-489c-9fc0-179c0a46d7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_password_new&quot;)</value>
      <webElementGuid>a4229fd8-4012-4b01-ab27-56ac73587438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_password_new']</value>
      <webElementGuid>a9128e45-42e5-4519-b652-e3b54ab5198c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile_password_dialog']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>f68cbdf9-3772-431b-93ca-abc9725b1608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>fd44aa7c-24e6-4266-94cd-31444905cb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_password_new' and @type = 'text' and @placeholder = 'New password']</value>
      <webElementGuid>e3eaa6a9-7060-4a54-9f2e-412d27cd2b27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
