<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Set_Old_Password</name>
   <tag></tag>
   <elementGuidId>d3eb4b78-8cd1-4d90-817f-74cf47b585a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_password_old</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[5]/div/div/div[2]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0329acc0-6cbd-440e-9fcd-2f344d3919db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_password_old</value>
      <webElementGuid>20f2dc88-4dee-4718-a019-87faa93b14d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-password form-control</value>
      <webElementGuid>1b08e006-bb84-4047-b2cf-716bf50a7c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00940df6-e338-4ef1-97d7-55872b64717d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_password_old</value>
      <webElementGuid>d24f3210-e5a4-4b01-b1ee-189009be2d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3a632793-fe5f-41c7-90ea-ed3ca2592225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Old password</value>
      <webElementGuid>8d82e9b7-4410-4e86-ad77-6dc2a1d3f549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_password_old&quot;)</value>
      <webElementGuid>04843d48-7323-4e6f-ace7-b2f09cf56258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_password_old']</value>
      <webElementGuid>25f98638-bd05-4c36-a56f-d9de3cc8df19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile_password_dialog']/div/div/div[2]/div/input</value>
      <webElementGuid>82422fc1-bc57-4ce1-a3c9-6499b6b4abac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/input</value>
      <webElementGuid>a023c0c9-6862-4ee5-91d7-c14ef2cc6e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_password_old' and @type = 'text' and @placeholder = 'Old password']</value>
      <webElementGuid>16109d0b-7150-48b8-80ce-95755a81e98e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
