<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upgrade_Button_validation_date</name>
   <tag></tag>
   <elementGuidId>c6357535-d1e8-4738-bba1-506f0ead9481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_upgrade_validity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[1]/div[2]/div[3]/table[1]/tbody/tr[6]/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aebdb571-3c48-492d-a946-08d5c3bfa634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_upgrade_validity</value>
      <webElementGuid>1ab722f7-807b-4bd2-81de-ae81c08acce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default katalonDeHighlight</value>
      <webElementGuid>20acc4a9-85b4-489b-8f52-174d79ed6197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.powerfolder.com/pricing</value>
      <webElementGuid>b95aa9d2-9c40-4042-9949-30eb517e1e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f2a5cb86-265f-4076-9ce8-35056fc769bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Upgrade
                        </value>
      <webElementGuid>b72337d3-1ce4-4a61-b9b7-b26b138d3e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_upgrade_validity&quot;)</value>
      <webElementGuid>3df65e11-2be2-47ba-b679-09713fdc5884</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='profile_upgrade_validity']</value>
      <webElementGuid>4c1ef3a6-3ab9-444b-8cd0-f87a52d9932a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/table/tbody/tr[6]/td[3]/a</value>
      <webElementGuid>87058822-8cc2-46b6-a74c-d0dff698e401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valid till'])[1]/following::a[1]</value>
      <webElementGuid>e0bbe5d2-8ac1-4eca-b14f-4d1529266f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[5]/following::a[1]</value>
      <webElementGuid>41a9b67d-5a24-4155-b12a-0fe3d0234595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/preceding::a[1]</value>
      <webElementGuid>700ef18b-64d4-49d8-bd42-15219aafd56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.powerfolder.com/pricing')])[2]</value>
      <webElementGuid>67676952-3834-48c5-b9c0-758feca97af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[3]/a</value>
      <webElementGuid>ee8c0671-7c21-4c99-9cfc-d45ed54789c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'profile_upgrade_validity' and @href = 'https://www.powerfolder.com/pricing' and (text() = '
                            Upgrade
                        ' or . = '
                            Upgrade
                        ')]</value>
      <webElementGuid>2d486352-144f-4d6e-94f9-4ffb23e53485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
