<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upgrade_button</name>
   <tag></tag>
   <elementGuidId>c323612c-f991-4baa-b539-c70b3406e143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_upgrade_quota</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[3]/table[1]/tbody/tr[2]/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aed7747e-9dca-4902-aeea-8e87996049d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_upgrade_quota</value>
      <webElementGuid>92fda326-3193-4b3e-8fef-e5723cc44310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>8a012f69-8b41-4064-af12-486a58627121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.powerfolder.com/pricing</value>
      <webElementGuid>4d28a16e-d846-40ee-887a-57d2a6ce6d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c122bda5-70b4-439d-9d8a-b8e834bfe28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Upgrade
                        </value>
      <webElementGuid>8314db91-7839-4ea4-be1c-2655585f74bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_upgrade_quota&quot;)</value>
      <webElementGuid>db3b8cb7-933a-4bc2-adaf-f07ce8a7997b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='profile_upgrade_quota']</value>
      <webElementGuid>eb63d474-8de5-4cf1-be84-b4805fa622f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/table/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>18941c12-58e6-47f1-b766-6b508ad3704b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quota'])[1]/following::a[1]</value>
      <webElementGuid>81a81d16-035c-4f23-94bf-7215e766499a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[3]/following::a[1]</value>
      <webElementGuid>10c4db88-eb1e-4bab-a8a9-2f8a40685442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::a[1]</value>
      <webElementGuid>f3c57ba1-eb31-403b-b3f9-d1bc61185985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.powerfolder.com/pricing')]</value>
      <webElementGuid>6736b05b-16f6-45fc-9ec0-6891bd8fd029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>2622102a-c47d-4f1a-a9e1-41a40c7664c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'profile_upgrade_quota' and @href = 'https://www.powerfolder.com/pricing' and (text() = '
                            Upgrade
                        ' or . = '
                            Upgrade
                        ')]</value>
      <webElementGuid>9da9160c-99bf-464c-9dd5-eb85b385069c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
