<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete</name>
   <tag></tag>
   <elementGuidId>5736c809-bfe7-46a3-b0fb-e920080752ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pica_group_avatar_delete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pica_group_avatar_delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51adaa3b-ae94-4aa8-b3e6-dd46ae60c414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_group_avatar_delete</value>
      <webElementGuid>b8aa7de4-d7e0-481a-819a-953989d35945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block btn-danger</value>
      <webElementGuid>f160e89c-ae2d-48e5-8d0c-8523e0775ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Delete
                                </value>
      <webElementGuid>9800ddd0-4502-42ae-8878-87e711fcda6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_group_avatar_delete&quot;)</value>
      <webElementGuid>7a4c3ac1-9bb3-4b78-9c17-850a674bf4ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pica_group_avatar_delete']</value>
      <webElementGuid>22a7ffff-f961-4286-a548-c85d91d1f623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_group_dialog']/div/div/div[2]/div[2]/div/div[2]/div/a[2]</value>
      <webElementGuid>29f4dc96-a7c1-44f4-8a0b-52d1da041013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>6468ec5d-45ad-4e19-99e5-de3adc312b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pica_group_avatar_delete' and (text() = '
                                    Delete
                                ' or . = '
                                    Delete
                                ')]</value>
      <webElementGuid>2b6cbcdc-f159-4bb0-983b-63881e835059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
