<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_folder_members</name>
   <tag></tag>
   <elementGuidId>6f3d5474-5495-4933-b957-5d0aae4e01e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.pica-taginput-dropdown.dropdown-menu > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_group_folders']/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9716c3a6-d47a-4d6f-8a7c-abf9dec7746f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>folder_1029No members</value>
      <webElementGuid>0214a722-3259-4fce-b1c8-dcc9fe5c6442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_group_folders&quot;)/div[@class=&quot;pica-inputlist-taginput pica-taginput form-group input-group&quot;]/div[@class=&quot;pica-taginput-div form-control open&quot;]/ul[@class=&quot;pica-taginput-dropdown dropdown-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>92671006-d48e-4b17-b596-d6ff2d269a3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_group_folders']/div/div/ul/li/a</value>
      <webElementGuid>49735a3b-5e13-4816-bdb0-807d6bd23b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/following::a[1]</value>
      <webElementGuid>4d5770d9-3691-49a7-b184-b8b3e311150a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[1]/following::a[2]</value>
      <webElementGuid>c5bd43b2-74bf-45e2-a248-bf89b6148606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create new'])[1]/preceding::a[1]</value>
      <webElementGuid>cf7d5b41-27ab-4a74-9553-ebe720e958e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li/a</value>
      <webElementGuid>b067a7c5-1484-41a3-836b-0c9c45e6277c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'folder_1029No members' or . = 'folder_1029No members')]</value>
      <webElementGuid>1da78d0d-0eaa-4472-a40e-84400ba68869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
