<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Group_27_Jan_2024_02_11_02</name>
   <tag></tag>
   <elementGuidId>dd6c368e-c1ea-4ed2-a928-af384b2c7a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='Object_1302037304']/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Object_1302037304 > td.pica-overflow.pica-serial > a.pica-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>20c5dc09-fe16-4967-bfeb-c3e62832a1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-name</value>
      <webElementGuid>fcb47e74-5c72-497e-b7d1-925d2ece67eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group_27_Jan_2024_02_11_02</value>
      <webElementGuid>7def6365-1b30-4101-b8af-0dfb9b0c9dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_1302037304&quot;)/td[@class=&quot;pica-overflow pica-serial&quot;]/a[@class=&quot;pica-name&quot;]</value>
      <webElementGuid>1144f6a0-f335-4f57-b2f9-d305b8942165</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_1302037304']/td[2]/a</value>
      <webElementGuid>b9963f24-42cb-4eed-84bc-007701c17ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Group_27_Jan_2024_02_11_02')]</value>
      <webElementGuid>0959bb4d-a0da-4e63-95bc-64f55d3042c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a</value>
      <webElementGuid>dda3b947-aec2-44b0-9510-272c4b65d275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Group_27_Jan_2024_02_11_02' or . = 'Group_27_Jan_2024_02_11_02')]</value>
      <webElementGuid>9c180972-d98f-4388-952b-cc3c35e1c01e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
