<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Members</name>
   <tag></tag>
   <elementGuidId>76cfe370-3573-4d45-ad04-ba0a36688408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.hidden-xs.active > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='pica_group_nav']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1a78b34-157b-42d5-88d9-6f5a9db6d70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Members</value>
      <webElementGuid>1d0ef5e5-47c0-401a-95b1-a959ffd64ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_group_nav&quot;)/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>7c5d048c-cb6d-4f98-9cb2-6b28d32150db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pica_group_nav']/li[4]/a</value>
      <webElementGuid>d001ec4c-186a-412d-aedc-3a645aff2afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folders'])[3]/following::a[1]</value>
      <webElementGuid>c94b2cf8-c43c-4349-bfde-b108b827569a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avatar'])[1]/following::a[2]</value>
      <webElementGuid>8b527f7f-d757-451d-82bf-2914d208aeb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organizations'])[2]/preceding::a[1]</value>
      <webElementGuid>61b57e24-50c7-4a36-9c7d-cd776ad24f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>8d8f914e-057d-41f4-aa85-29daab589b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Members' or . = 'Members')]</value>
      <webElementGuid>d175381d-77af-4988-a935-0c8324281f98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
