<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Group updated</name>
   <tag></tag>
   <elementGuidId>a637cb36-bb05-4b6b-9738-3070aa90bd1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pica-notification-box.alert.alert-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9037e249-6b3b-4396-a5b4-ce625ac279fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-notification-box alert alert-info</value>
      <webElementGuid>f987ef56-271d-41d9-9928-9aba217d174e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>c0593e99-eca4-43ea-9cd7-b81579ff67c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group updated×</value>
      <webElementGuid>8e97dcb8-956c-415c-afd8-6976aa932ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification_1807109126&quot;)/div[@class=&quot;pica-notification-box alert alert-info&quot;]</value>
      <webElementGuid>e7fce7b9-1332-4ef0-a4b0-3de552eeafad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notification_1807109126']/div</value>
      <webElementGuid>5772c33a-0263-4d91-983e-1f09e7446454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'groups_table', '&quot;', ')/tbody[1]')])[1]/following::div[2]</value>
      <webElementGuid>59d8e842-cd8c-4762-9202-743af29a9b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[3]</value>
      <webElementGuid>df5c9e28-97c1-49d5-bf99-b5403adad142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>02c948e9-b03a-41a6-b41c-a4c10ec768ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Group updated×' or . = 'Group updated×')]</value>
      <webElementGuid>afa2fb23-9a22-4600-9ebe-ae4c235e1603</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
