<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>group_avatar</name>
   <tag></tag>
   <elementGuidId>8ff02a97-8993-4be5-8a55-924cc89324a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_group_avatar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pica_group_avatar']&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6cafa2c8-8f79-4964-ad76-6f4278902cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_group_avatar</value>
      <webElementGuid>0c36c894-10b6-42bb-8f90-26d8467c7579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-avatar pica-border</value>
      <webElementGuid>68cbe49a-4696-44f8-97c4-48435631f329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/avatars/NmI2MmRjNjEtMDdkOC0y</value>
      <webElementGuid>ab318d29-38ec-4a6a-ab7c-b873f357bdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_group_avatar&quot;)</value>
      <webElementGuid>76b8b6bc-7137-470d-adfc-0e93b3179788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pica_group_avatar']</value>
      <webElementGuid>3dad4256-484c-486d-a740-9412a7f930dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_group_dialog']/div/div/div[2]/div[2]/div/div/img</value>
      <webElementGuid>0b1799a4-a3f1-4fcb-a72e-7763fe623edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>c43107a9-f7c2-46ff-9044-0cefde4f24b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'pica_group_avatar' and @src = '/avatars/NmI2MmRjNjEtMDdkOC0y']</value>
      <webElementGuid>c7746474-fb66-46f0-9a91-2e6cf0035b3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
