<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_glyphicons glyphicons-group</name>
   <tag></tag>
   <elementGuidId>7135e351-8449-4063-b2ce-ef88d41d5137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_group_dialog']/div/div/div[2]/div/div/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.glyphicons.glyphicons-group</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1de46142-b47d-42c0-99af-fa75502778d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-group</value>
      <webElementGuid>9082badd-b569-419a-8180-6979a72705c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_group_dialog&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;pica-nav-tab&quot;]/div[@class=&quot;form-group input-group&quot;]/span[@class=&quot;input-group-addon&quot;]/i[@class=&quot;glyphicons glyphicons-group&quot;]</value>
      <webElementGuid>b4248c87-8ddd-4634-b531-0cf63aab8a24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_group_dialog']/div/div/div[2]/div/div/span/i</value>
      <webElementGuid>1f99cfaf-782f-43a3-9de4-ab0598411c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>e7a3785d-3068-43a0-9d6b-2f933406de97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
