<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Close</name>
   <tag></tag>
   <elementGuidId>03057901-cd44-47dc-b3b5-f67b66401a27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//lang[@name='button_cancel'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#upload_stop_button > lang[name=&quot;button_cancel&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>50a4592e-2d66-4af6-a4bf-9469a8e94b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button_cancel</value>
      <webElementGuid>66b9fd2d-92ea-4ce4-bfad-8adfb04c45e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>ed977b3b-aea1-46fc-8c7f-24c557ff486f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upload_stop_button&quot;)/lang[1]</value>
      <webElementGuid>715d4c21-ddf7-4875-a699-ef053eab15e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//lang[@name='button_cancel'])[2]</value>
      <webElementGuid>6b440e5d-cbd3-452e-bd5e-c9415dba9d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='upload_stop_button']/lang</value>
      <webElementGuid>06b9e528-2f56-4cf1-8513-21aa2a954e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]/lang</value>
      <webElementGuid>58771305-0722-4bf1-9bed-547cbdb6db2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'button_cancel' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>ad26a7d2-65f1-45f6-920d-bdf0a0806f85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
