<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Folders</name>
   <tag></tag>
   <elementGuidId>fe9bdb0e-0142-46ce-aea4-b4ce302606bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//lang[@name='label_folders'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.hidden-xs > a > lang[name=&quot;label_folders&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>ad60199c-88c7-44a1-88e7-ee45082aa168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label_folders</value>
      <webElementGuid>7a7553fc-06a5-410c-af00-cf28d71a2923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-plural</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>73223d7f-1e9a-418c-b350-73722de95fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Folders</value>
      <webElementGuid>c967ac24-410e-44b8-9b92-9f51565b5952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_group_nav&quot;)/li[@class=&quot;hidden-xs&quot;]/a[1]/lang[1]</value>
      <webElementGuid>275cda08-3615-440c-bd77-56ee7f514b69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//lang[@name='label_folders'])[3]</value>
      <webElementGuid>7c8a49ff-99da-4c31-8f23-51f1177b50fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pica_group_nav']/li[3]/a/lang</value>
      <webElementGuid>18aae4b3-1a23-484d-a496-5b68f7a6492d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/ul/li[3]/a/lang</value>
      <webElementGuid>cc6a9bd8-826d-4ec1-a142-3c174041de92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'label_folders' and (text() = 'Folders' or . = 'Folders')]</value>
      <webElementGuid>a9f8dbe1-06d8-4116-837b-231b4cd40413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
