<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Save</name>
   <tag></tag>
   <elementGuidId>9098194c-19f0-42ce-8cc1-139e3e922a15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;button_save&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='button_save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>227d39c8-d660-44d2-bd78-17b27ceeab21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button_save</value>
      <webElementGuid>e8fcb486-0395-430a-8bba-6b5d9264a0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>837bd2ac-8528-46b9-87e2-6bc8afae2e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica-group-edit-save&quot;)/lang[1]</value>
      <webElementGuid>5e9d1ca4-7cce-4939-9801-73b285864903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='button_save']</value>
      <webElementGuid>e8b06c2d-7000-463f-a2cd-b80299477d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='pica-group-edit-save']/lang</value>
      <webElementGuid>2c427a3e-3d6d-4597-80df-ccedf97051ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/button/lang</value>
      <webElementGuid>d3bc87c3-2e65-4376-b1af-2887db831be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'button_save' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>78e4f209-bff4-47e8-9aff-e30ead7afc53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
