<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Group_27_Jan_2024_02_11_02</name>
   <tag></tag>
   <elementGuidId>47aae403-3b7a-4b33-9267-e7ea548058c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='Object_1302037304']/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Object_1302037304 > td.pica-overflow.pica-serial</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>53843237-72ec-47c3-953c-9f0a96addac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-overflow pica-serial</value>
      <webElementGuid>81471c32-8966-42e9-9817-1bfe35648e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group_27_Jan_2024_02_11_02</value>
      <webElementGuid>210ae0f1-31a9-46b4-9082-ba549638fc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_1302037304&quot;)/td[@class=&quot;pica-overflow pica-serial&quot;]</value>
      <webElementGuid>7632f1e9-2584-4a3a-b28f-bff55affbb2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_1302037304']/td[2]</value>
      <webElementGuid>17681e59-ffa8-4ca1-8a7b-aa9c1cced635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>ba03ffdd-f20b-4881-b6c9-62e36bc11c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Group_27_Jan_2024_02_11_02' or . = 'Group_27_Jan_2024_02_11_02')]</value>
      <webElementGuid>de6c5b73-d22a-4ce5-b872-783e17659631</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
