<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Organizations_pica_group_notes</name>
   <tag></tag>
   <elementGuidId>938cbf77-1afd-4a40-9d32-e39309cd0998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_group_notes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='pica_group_notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>50abd5a6-bbe9-4e80-aa36-c0ec363367e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_group_notes</value>
      <webElementGuid>df8455bc-6b7a-4ed8-9181-8e359e214776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>06577987-5eb5-47e2-9cce-73c67441fc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8e46c10b-ea7b-411a-9af0-e3e4ea466a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_notes</value>
      <webElementGuid>921f39f8-1947-4674-87c4-db38a1926c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>440a0843-a381-4875-ab5c-303cb7c2b69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_group_notes&quot;)</value>
      <webElementGuid>6586f6be-ce5c-42f3-9fd9-4dc05cfbdc95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pica_group_notes']</value>
      <webElementGuid>84895ce2-b729-4755-8042-8c8fdde1bb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_group_dialog']/div/div/div[2]/div/div[2]/textarea</value>
      <webElementGuid>c1810ae9-ef5c-4598-8954-b4590e5e4eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a6ce2d09-d0b9-4eb4-8dbf-9b2916f3f874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'pica_group_notes' and @placeholder = 'Notes']</value>
      <webElementGuid>446291d6-73b1-404c-bcc1-1cce9ec15119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
