<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Create newCreate new and automatically assign</name>
   <tag></tag>
   <elementGuidId>75b94c8d-ec26-4bfd-857d-4d272b67f999</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.pica-taginput-dropdown.dropdown-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_group_folders']/div/div/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>afda8e7a-b45e-46dc-8d6c-356032559dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-taginput-dropdown dropdown-menu</value>
      <webElementGuid>d5d37f9a-df3a-4a29-adc4-b01605626281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>18d7bb95-f908-4864-ba2d-e35312259e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create newCreate new and automatically assign</value>
      <webElementGuid>cdb1a3a6-db50-4551-a3e2-393ea17d5ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_group_folders&quot;)/div[@class=&quot;pica-inputlist-taginput pica-taginput form-group input-group&quot;]/div[@class=&quot;pica-taginput-div form-control open&quot;]/ul[@class=&quot;pica-taginput-dropdown dropdown-menu&quot;]</value>
      <webElementGuid>7f56205d-fbea-4af8-8650-97eb8d978fed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_group_folders']/div/div/ul</value>
      <webElementGuid>a605db44-99d6-4a5e-8571-69f146d130c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/following::ul[1]</value>
      <webElementGuid>cb01ed12-4ee2-4204-8491-2c4f56ae75dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[1]/following::ul[1]</value>
      <webElementGuid>9a2986d8-b9cc-4c2b-9398-1eae70f4a3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::ul[1]</value>
      <webElementGuid>6a0da362-6f9c-4c95-9be7-17beb24a1cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul</value>
      <webElementGuid>1aefd4d4-987e-4868-814d-13c62768c1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'Create newCreate new and automatically assign' or . = 'Create newCreate new and automatically assign')]</value>
      <webElementGuid>94e52f5f-86a8-44c2-b63f-7adb358a3481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
