<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verifier_folder</name>
   <tag></tag>
   <elementGuidId>a0f5c828-1ef4-4894-9c41-d5c8bc4776aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/table/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.pica-name.pica-overflow.pica-vertical-middle.text-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5873151a-d26d-4298-8649-7eff5e504b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-name pica-overflow pica-vertical-middle text-left</value>
      <webElementGuid>964076ca-e796-405a-91d8-b8ae4563b823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>4c8b296e-9d98-4cd5-b823-4089974344e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>07f19c22-eec0-4501-a03a-2b19627239b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>folder_3637</value>
      <webElementGuid>8c0c7869-1061-4022-b98c-1fa09d1b2b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_1216551370&quot;)/td[@class=&quot;pica-name pica-overflow pica-vertical-middle text-left&quot;]</value>
      <webElementGuid>f804d021-e0c9-4f6c-b8ba-17f6487eaffe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='item_1216551370']/td[2]</value>
      <webElementGuid>ca613d95-daa8-40fb-bcc3-5425e61840cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/following::td[2]</value>
      <webElementGuid>8ca1a2ea-77c2-425d-8f30-2c6095bccefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create new'])[1]/following::td[2]</value>
      <webElementGuid>76051187-2b11-45fe-9518-e1f2215acc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Can read'])[1]/preceding::td[1]</value>
      <webElementGuid>2572528f-1354-4e68-8d26-9886e3e7569d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Can read'])[2]/preceding::td[1]</value>
      <webElementGuid>bd666430-3b5e-4674-87ca-b0c3dc1d3adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='folder_3637']/parent::*</value>
      <webElementGuid>6ed44698-72b0-42fa-a98e-ef98161cb69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>22c6cde7-a759-4747-a061-61c1fe5552da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'folder_3637' or . = 'folder_3637')]</value>
      <webElementGuid>aba9d159-3463-45ae-9568-cc650a37592d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
