<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cloud 1 TB_yearly</name>
   <tag></tag>
   <elementGuidId>78909344-cf2f-43ee-9043-e8186681b0e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yearlyPlans']//div[contains(@class,'plan-card')][.//div[contains(@class,'plan-title') and normalize-space(text())='Cloud 1 TB']]//a[contains(@class,'plan-cta')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yearlyPlans > div.plan-card > a.plan-cta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0928cdba-918b-4ed3-95fb-1ce79c9297bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4163c389-81d4-48fd-bc06-a943840722c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plan-cta</value>
      <webElementGuid>e2d87b8a-2fad-4a7f-8730-f5516434c078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choisir Cloud 1 TB</value>
      <webElementGuid>1c1cb360-00fd-4bdc-a505-5f7470c17c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yearlyPlans&quot;)/div[@class=&quot;plan-card&quot;]/a[@class=&quot;plan-cta&quot;]</value>
      <webElementGuid>358bc4ef-9061-4e42-b0e1-f319c72ec5a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yearlyPlans']/div[2]/a</value>
      <webElementGuid>1f935e33-76b8-4326-85ac-c350faac1d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Choisir Cloud 1 TB')])[2]</value>
      <webElementGuid>02a39d1d-525a-4bf6-b731-6c05c2477415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annuel'])[3]/following::a[1]</value>
      <webElementGuid>c49b2587-d320-4a69-a178-87ea107524b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud 1 TB'])[2]/following::a[1]</value>
      <webElementGuid>f2e75f36-59fc-4f0d-8773-ca0613fc51ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Cloud 6 TB'])[2]/preceding::a[1]</value>
      <webElementGuid>872219a4-7a2c-416a-a81e-7a247a875aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annuel'])[4]/preceding::a[1]</value>
      <webElementGuid>461d508c-4fc9-44af-9255-9916562a8ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>0391abd1-8595-491f-b36f-75afa584e22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>e8528e5a-ab55-49ab-ac65-d7a9d8518cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Choisir Cloud 1 TB' or . = 'Choisir Cloud 1 TB')]</value>
      <webElementGuid>45d37b72-a68e-48f8-a36b-d6c8f1561eb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
