<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Annuel</name>
   <tag></tag>
   <elementGuidId>c440bcbe-fd67-4f9d-9f84-f5f6ac75c648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[2]/div/div[2]/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.toggle-label.toggle-label-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f2b56c08-ed92-4a35-9123-89625ff52a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>yearlyRadio</value>
      <webElementGuid>542b4a2b-da76-45c9-a231-950881a9dde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toggle-label toggle-label-right</value>
      <webElementGuid>96f711b0-fca6-4cca-9e4c-ef1b3a9200df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Annuel
                </value>
      <webElementGuid>bbcb0679-d40a-4064-876e-6cb3170bfdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_content&quot;)/div[@class=&quot;pricing-wrapper&quot;]/div[@class=&quot;toggle-container&quot;]/label[@class=&quot;toggle-label toggle-label-right&quot;]</value>
      <webElementGuid>47e5f6a4-2fa0-4887-b3a4-e4c594a23b58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div/div/label[2]</value>
      <webElementGuid>cc7d20e8-d9cb-425e-8ebb-fd94f4556850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensuel'])[1]/following::label[1]</value>
      <webElementGuid>0e02bfe4-68ff-4439-b64d-f39352e1f939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nos offres flexibles'])[1]/following::label[2]</value>
      <webElementGuid>2c01b12d-d55a-49c0-ad46-cfd1cd614226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kostenlos 5 GB'])[1]/preceding::label[1]</value>
      <webElementGuid>c93f0a9d-7687-4145-93f8-9477e3f791e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>7b413760-a8cf-48bc-a2fc-cbab9e068600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '
                    Annuel
                ' or . = '
                    Annuel
                ')]</value>
      <webElementGuid>a74eb396-0c18-426f-b7ae-4e6c6ebda58a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
