<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keep Me Logged In_Login</name>
   <tag></tag>
   <elementGuidId>79c1e008-68a4-48db-bc9e-6d13e5ef77b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69ca7d84-e588-4b57-91fa-93a704ee4671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_submit</value>
      <webElementGuid>38b47118-5f28-44a1-a24c-e14ddac4c3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>55b8fb4f-3ecc-4d48-a805-919bf80f0727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ffdfda19-ac9a-40b0-967f-92d9cb6cfbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>fdc3efc2-39f4-4515-896b-2d2fb7c6713b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>5d4bcfea-be06-4a06-bf2d-dc7d2b44c6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_submit&quot;)</value>
      <webElementGuid>ab71309a-ebdb-42ac-963b-d7e9dfbeb614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_submit']</value>
      <webElementGuid>7e2e9bf6-9a5e-4e50-87bc-cb39d2ff8be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div[4]/input</value>
      <webElementGuid>8f0f892f-a971-4884-a4fd-4813e2d5df71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>a1bf0e91-4dc0-4d9a-9c59-1224553a67dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login_submit' and @type = 'submit' and @name = 'Login']</value>
      <webElementGuid>243d21d3-203d-4004-96fe-b23337e82179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
