<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload_2</name>
   <tag></tag>
   <elementGuidId>05d103c1-4e25-487a-962a-b7dfe98859dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#upload_start_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='upload_start_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1cf858ac-380f-42d8-897b-4a0f14d06458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>upload_start_button</value>
      <webElementGuid>2c0d33ba-4b12-4f3d-b85a-4f8530c5a71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba437b0f-58a4-42b3-9329-8778e8aede5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>b30a09a3-5e3c-4867-82a8-ad67eb7e1c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>9f8e3bbc-5a68-4ed5-8f1a-a592cb67e587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Upload
                        </value>
      <webElementGuid>3431a21f-3b91-4893-bdfd-45f26233518c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upload_start_button&quot;)</value>
      <webElementGuid>f67f6e13-b3a5-444f-964f-4ee06a6ec853</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='upload_start_button']</value>
      <webElementGuid>7d9d4f94-bef9-47d8-bdf7-ffa1ea6ff8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_upload_dialog']/div/div/div[3]/div/div[2]/button</value>
      <webElementGuid>43e4a16c-7853-47e0-9056-c9fbfb237714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add directory'])[1]/following::button[1]</value>
      <webElementGuid>9150a333-9319-4003-bbd1-cb388ca2dc78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add file'])[1]/following::button[1]</value>
      <webElementGuid>c6b37746-6e59-495d-8753-9180af774a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::button[1]</value>
      <webElementGuid>5bdd2d75-7001-435a-b92c-92688b9487a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>5c46d543-2dbe-4405-9093-04b6b8f31cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'upload_start_button' and @type = 'button' and (text() = '
                            Upload
                        ' or . = '
                            Upload
                        ')]</value>
      <webElementGuid>48e91750-0165-4f01-b242-8c7dfcb17650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
