<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload</name>
   <tag></tag>
   <elementGuidId>d5bf4dc8-1b7b-429b-8230-e8d5d0940e4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#preparelink_upload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='preparelink_upload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b837f29-1952-49fc-b3f0-f0f08fc6c202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preparelink_upload</value>
      <webElementGuid>66f8db4a-8735-49df-9c85-3b3a0bc611d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf7087ac-c55d-41de-b0d0-b5d4dfea07c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>082cbf18-47f1-48f1-89e5-73f5c7607793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Upload
                            </value>
      <webElementGuid>dd3c7670-2905-4478-8598-e2527f1caccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preparelink_upload&quot;)</value>
      <webElementGuid>e73a0fb4-f0b0-46d7-9730-e615a17941cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='preparelink_upload']</value>
      <webElementGuid>62e08b3e-0d65-4b7d-a339-7fc4a78d76bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workshop'])[1]/following::button[1]</value>
      <webElementGuid>76119189-f016-4fdb-95d0-b8bda2b99318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imprint'])[1]/preceding::button[1]</value>
      <webElementGuid>4cab470b-f984-49e9-8a90-18bbb4f58fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ddde9276-f188-4a46-a0a0-85a0dedc3a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'preparelink_upload' and @type = 'button' and (text() = '
                                Upload
                            ' or . = '
                                Upload
                            ')]</value>
      <webElementGuid>80a99c3b-08f5-42ff-bee0-ed1ade6f6693</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
