<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_Doc</name>
   <tag></tag>
   <elementGuidId>bc8a9866-598e-4736-a7cf-740311b7abc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pica-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/table/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c8f81b0-14ef-4249-9b13-1870ecd03841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-name</value>
      <webElementGuid>bfa500e3-3883-4c80-86d4-853960f068eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mimas.powerfolder.net/open/MjJxQWk2clBMRUVVSFBWbk1pc0FC/FD_Test_08mars2025031340/Doc_num_3986.docx</value>
      <webElementGuid>b2b5579d-4f6c-419b-a2f9-cc07e7f36d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-serial</name>
      <type>Main</type>
      <value>{&quot;_flags&quot;:4,&quot;_oid&quot;:&quot;&quot;,&quot;_name&quot;:&quot;Doc_num_3986.docx&quot;,&quot;_intName&quot;:&quot;&quot;,&quot;_size&quot;:0,&quot;_archiveSize&quot;:0,&quot;_resUrl&quot;:&quot;https://mimas.powerfolder.net/download/MjJxQWk2clBMRUVVSFBWbk1pc0FC/FD_Test_08mars2025031340/Doc_num_3986.docx&quot;,&quot;_openUrl&quot;:&quot;https://mimas.powerfolder.net/open/MjJxQWk2clBMRUVVSFBWbk1pc0FC/FD_Test_08mars2025031340/Doc_num_3986.docx&quot;,&quot;_basePath&quot;:null,&quot;_path&quot;:&quot;FD_Test_08mars2025031340/Doc_num_3986.docx&quot;,&quot;_folderId&quot;:null,&quot;_accountsCount&quot;:0,&quot;_groupsCount&quot;:0,&quot;_versions&quot;:0,&quot;_ownerOid&quot;:0,&quot;_isBlocked&quot;:false,&quot;_modifiedDate&quot;:-1,&quot;_modifiedDateMS&quot;:-1,&quot;_modifiedOn&quot;:&quot;&quot;,&quot;_modifiedBy&quot;:null,&quot;_modifiedByAccount&quot;:null,&quot;_version&quot;:0,&quot;_publicUrl&quot;:&quot;&quot;,&quot;_isStorageExceeded&quot;:&quot;&quot;,&quot;_permission&quot;:null,&quot;_publicPermission&quot;:null,&quot;_folderIdEnc&quot;:&quot;MjJxQWk2clBMRUVVSFBWbk1pc0FC&quot;,&quot;_url&quot;:&quot;MjJxQWk2clBMRUVVSFBWbk1pc0FC/FD_Test_08mars2025031340/Doc_num_3986.docx&quot;}</value>
      <webElementGuid>c9f6b01e-deb4-4b79-8889-df4386bc99cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Doc_num_3986.docx</value>
      <webElementGuid>ec218744-ebdd-41b9-a4f0-c0e07ac5f434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_1973660074&quot;)/td[@class=&quot;pica-overflow&quot;]/a[@class=&quot;pica-name&quot;]</value>
      <webElementGuid>52d86763-5a52-487c-a257-af9d4d5ba378</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_1973660074']/td[2]/a</value>
      <webElementGuid>6066a566-a1b3-4fbb-9268-bc627850722d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Doc_num_3986.docx')]</value>
      <webElementGuid>73f2f863-553f-466b-b568-60fe8c8c5ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::a[1]</value>
      <webElementGuid>4958bc9e-3d6e-486b-b306-b6ba32a3f4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paste'])[1]/following::a[1]</value>
      <webElementGuid>b9718d82-58bb-45fe-9fa2-4d8d80b32129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imprint'])[1]/preceding::a[1]</value>
      <webElementGuid>08391b13-8a39-4469-a6c8-19fefaf69754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::a[2]</value>
      <webElementGuid>c938ba04-4d4d-460b-9b3d-8e1c8091cee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Doc_num_3986.docx']/parent::*</value>
      <webElementGuid>f741d597-df94-4c7e-87cd-192d19b869f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://mimas.powerfolder.net/open/MjJxQWk2clBMRUVVSFBWbk1pc0FC/FD_Test_08mars2025031340/Doc_num_3986.docx')]</value>
      <webElementGuid>6b6355a1-a11e-4854-ae9c-30de863c8231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>7205d460-c10e-4148-a87e-ed8f7d1040a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://mimas.powerfolder.net/open/MjJxQWk2clBMRUVVSFBWbk1pc0FC/FD_Test_08mars2025031340/Doc_num_3986.docx' and (text() = 'Doc_num_3986.docx' or . = 'Doc_num_3986.docx')]</value>
      <webElementGuid>d796b35d-c8bf-4938-86a4-742d1dad5e23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
