<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Yes</name>
   <tag></tag>
   <elementGuidId>d419f338-3b81-40fb-b8c8-c9a65a795c29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='button_yes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;button_yes&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>91f50701-804c-45ef-8eec-17c48a31720a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button_yes</value>
      <webElementGuid>4d965946-dbc5-4067-a4e0-fe7d75e0a42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>d2312380-9016-42fa-b120-a00c35107b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_confirmation_dialog&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer&quot;]/button[@class=&quot;btn btn-primary&quot;]/lang[1]</value>
      <webElementGuid>4504dd3b-19d6-4b08-981b-0c7c56003d49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='button_yes']</value>
      <webElementGuid>6a125def-4a57-4a52-ba1f-8ff868439d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_confirmation_dialog']/div/div/div[3]/button/lang</value>
      <webElementGuid>504ace66-6a97-4d6f-9bf2-cf4ebc6df36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you really want to restart tspfdd05?'])[1]/following::lang[1]</value>
      <webElementGuid>f288ce32-c9ea-4117-b7fe-519a4f3c89ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restart'])[3]/following::lang[1]</value>
      <webElementGuid>1bff7f37-7374-4901-8e22-b81a8119025f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::lang[1]</value>
      <webElementGuid>eeb1b3a7-7146-4528-94ec-7084041619e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imprint'])[1]/preceding::lang[2]</value>
      <webElementGuid>6e805d56-9142-4f59-920c-9b2796cca023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>7a0d1e58-34a8-4e66-8b29-3fd883239cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/button/lang</value>
      <webElementGuid>df36b565-6373-4f78-99a7-8bfd335d1a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'button_yes' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>200a3b74-94f4-4926-a6a2-204cf9880116</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
