<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_view_mode</name>
   <tag></tag>
   <elementGuidId>c152c88f-1af2-4b8c-a997-3b3e03e7f9db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[10]/div/ul/li[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pica-vmtable-toggle-grid > span.glyphicons.glyphicons-show-thumbnails.pica-glyph</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ae62868e-ba69-4c60-a940-d365b90f6866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-show-thumbnails pica-glyph</value>
      <webElementGuid>52cbf2f9-ce55-437b-91a5-4ea9f0cc7a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_servers&quot;)/thead[2]/tr[1]/th[@class=&quot;pica-icon-column&quot;]/div[@class=&quot;pica-vmtable-toggle pica-inline pica-table-selection-hide dropdown open&quot;]/ul[@class=&quot;pica-arrow-right dropdown-menu dropdown-menu-right&quot;]/li[3]/a[@class=&quot;pica-vmtable-toggle-grid&quot;]/span[@class=&quot;glyphicons glyphicons-show-thumbnails pica-glyph&quot;]</value>
      <webElementGuid>a7c03db9-b083-4f53-ac54-5b9516585f9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_servers']/thead[2]/tr/th[10]/div/ul/li[3]/a/span</value>
      <webElementGuid>dc294bcb-09fd-4c52-9054-0ac0df861e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[10]/div/ul/li[3]/a/span</value>
      <webElementGuid>ed7af091-c633-4f58-adda-186cafa89e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_servers']/thead[2]/tr/th[10]/div/ul/li/a/span</value>
      <webElementGuid>b76d8e03-6fc7-44bf-8813-ae897f4e9e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[10]/div/ul/li/a/span</value>
      <webElementGuid>7ed21d9b-06f4-49e7-92df-e30b508dc256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_servers']/thead[2]/tr/th[10]/div/a/span</value>
      <webElementGuid>d3badfc4-5c2b-43da-880e-b3a0ca1eaff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[10]/div/a/span</value>
      <webElementGuid>152fce70-baaa-45b3-a314-4536042eb01e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
