<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Last connect time_glyphicons glyphicon_720a57</name>
   <tag></tag>
   <elementGuidId>3c902d89-1662-41bd-889d-7259f8db8d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_servers']/thead[2]/tr/th[10]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.glyphicons.glyphicons-show-thumbnails-with-lines.pica-vmtable-toggle-list.pica-glyph</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ace568b0-8dad-4004-b9e1-678df6a05fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-show-thumbnails-with-lines pica-vmtable-toggle-list pica-glyph</value>
      <webElementGuid>78edbe89-b512-4eaf-bcbb-a8dc803d19eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_servers&quot;)/thead[2]/tr[1]/th[@class=&quot;pica-icon-column&quot;]/div[@class=&quot;pica-vmtable-toggle pica-inline pica-table-selection-hide dropdown&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;glyphicons glyphicons-show-thumbnails-with-lines pica-vmtable-toggle-list pica-glyph&quot;]</value>
      <webElementGuid>9af13d26-c9a2-4753-8c7f-e879a2ed7524</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_servers']/thead[2]/tr/th[10]/div/a/span</value>
      <webElementGuid>b1e09984-6c83-4901-8ed1-6706dd5e9832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[10]/div/a/span</value>
      <webElementGuid>bf609ecf-06c9-49c4-ba05-bd9b8dcc0e32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
