<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_tspfdd0520.4.86 (105.9 MB)15 (29.3 GB_2403d9</name>
   <tag></tag>
   <elementGuidId>c0c27178-01e7-405a-85d3-52be62314fd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_servers']/tbody</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table_servers > tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tbody</value>
      <webElementGuid>bbce56b9-2668-42aa-b9e4-7342183d395b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tspfdd0520.4.86% (105.9 MB)15% (29.3 GB)RestartDelete0143Now</value>
      <webElementGuid>baa79679-fd19-4a1b-b578-9f0aa3343e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_servers&quot;)/tbody[1]</value>
      <webElementGuid>2ffcd999-d33d-40f6-a2f2-15c642be6406</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_servers']/tbody</value>
      <webElementGuid>84fe425c-95d0-451d-bfd7-731f6752e03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grid'])[1]/following::tbody[1]</value>
      <webElementGuid>a938f5a2-e5d6-464e-beb8-62407f696709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List'])[1]/following::tbody[1]</value>
      <webElementGuid>4ac6586d-0e17-41dc-9909-5a57c06c9689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody</value>
      <webElementGuid>b67120b5-2d41-465a-9754-56dec93617ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tbody[(text() = 'tspfdd0520.4.86% (105.9 MB)15% (29.3 GB)RestartDelete0143Now' or . = 'tspfdd0520.4.86% (105.9 MB)15% (29.3 GB)RestartDelete0143Now')]</value>
      <webElementGuid>0c953721-19ba-4057-80e3-e9181f3ec2df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
