<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_tspfdd05</name>
   <tag></tag>
   <elementGuidId>db88d300-5d1f-4862-aba6-f7b9a6ecc77e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[(text() = 'tspfdd05' or . = 'tspfdd05')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.pica-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3381a5a5-681c-4666-a944-ba437629bd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-name</value>
      <webElementGuid>28dee80c-fcbc-4820-add1-b8efe71650eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tspfdd05</value>
      <webElementGuid>feac5b43-1205-4539-8b18-84a7916d3062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Object_839316137&quot;)/td[@class=&quot;pica-name&quot;]</value>
      <webElementGuid>f6c93071-0efe-45bf-85be-dd6b7bc4cda1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Object_839316137']/td[2]</value>
      <webElementGuid>7d2dd8de-666f-44ce-bdad-fb258f2b94ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grid'])[1]/following::td[2]</value>
      <webElementGuid>9bdccf35-aa6f-4ad3-9450-b3451cf80ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List'])[1]/following::td[2]</value>
      <webElementGuid>bebf73a3-b6c0-4765-a736-52dae5a43498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(29.3 GB)'])[1]/preceding::td[3]</value>
      <webElementGuid>7521b0fb-9e1d-4cff-b5be-de5e591af3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restart'])[2]/preceding::td[3]</value>
      <webElementGuid>094ab0f2-44f4-4f1d-b395-fad42099ad4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>e5cc40d5-8423-47db-849f-2e84c94feeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1d9a5ec1-523c-4590-bdf9-3842f496ba0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
