<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Active</name>
   <tag></tag>
   <elementGuidId>24a57328-40e1-47ab-9ff6-d2a5fe4d249b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[1]/div[2]/div[3]/div/div/div[2]/div[1]/div[4]/div[1]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf73da74-8ee3-4742-902b-6efec4aa3a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2051f00a-6f52-4b79-bd2b-65372ca842e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary active</value>
      <webElementGuid>0f38db06-5cc5-43a7-a104-8b11db1383ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>d4b556e7-6e1c-4cdb-b2d1-3b0c1ddf22a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Active
                                </value>
      <webElementGuid>08260c9f-d7a1-423b-a02d-887536a42441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_dialog&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;pica-nav-tab&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-xs-2 pica-block-on-small&quot;]/div[@class=&quot;pica-button-checkbox pica-space-right-small pull-left&quot;]/button[@class=&quot;btn btn-primary active&quot;]</value>
      <webElementGuid>f178dae9-34d2-4263-8a39-a8b499067a61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>93dd5e83-4b11-43ff-87f3-6383875d59a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_account_dialog']/div/div/div[2]/div/div[4]/div/div/button</value>
      <webElementGuid>9495f249-ebdf-4575-8121-b7b4c44ad795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[2]/following::button[1]</value>
      <webElementGuid>4314769b-1743-4983-9240-30f2be640d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organizations'])[3]/following::button[1]</value>
      <webElementGuid>b43ad1bd-820f-4e85-bd83-8c5a0caae42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation Date'])[1]/preceding::button[1]</value>
      <webElementGuid>418b3b6a-1e16-4fa5-991c-e7806ee9ba77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/button</value>
      <webElementGuid>f01b80a4-8ca3-4601-8cde-8ab98c3df6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                    Active
                                ' or . = '
                                    Active
                                ')]</value>
      <webElementGuid>9a169c9f-0d12-4fde-9003-2cfa29343332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
