<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Edit Account</name>
   <tag></tag>
   <elementGuidId>ba8d676f-56d6-4440-ba3a-beeec6f11e37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.pica-dialog-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[1]/div[2]/div[3]/div/div/div[2]/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>a6e23d04-0802-494a-9731-9a1ab91615af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-dialog-description</value>
      <webElementGuid>5ed1aa11-037f-43e2-bc62-09a033221816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Account</value>
      <webElementGuid>094a450d-9fd1-4d46-8bb7-34d12f5ca55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_dialog&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/h5[@class=&quot;pica-dialog-description&quot;]</value>
      <webElementGuid>81781b96-26c2-4791-9c71-f493696e2757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_account_dialog']/div/div/div[2]/h5</value>
      <webElementGuid>a659cc90-0529-402c-9727-3524112ddf88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/following::h5[1]</value>
      <webElementGuid>e0df7a97-b8e5-40be-b99c-b3c13e860e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::h5[1]</value>
      <webElementGuid>1a2613ab-301a-4607-8b50-13c06f9a9f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/preceding::h5[1]</value>
      <webElementGuid>d44978e2-454f-4193-9054-be4de3080179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avatar'])[1]/preceding::h5[1]</value>
      <webElementGuid>65268880-e575-4ffe-aef2-14ed24c7eb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit Account']/parent::*</value>
      <webElementGuid>31936a96-0b1b-44ac-96d9-1cf066a1eede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>97247c1e-868e-4969-b43e-5d0f0325c73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Edit Account' or . = 'Edit Account')]</value>
      <webElementGuid>fd42bff5-5634-4ef9-ae1e-ac10806289eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
