<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save_check</name>
   <tag></tag>
   <elementGuidId>e6a45903-cc22-48ba-99c4-fd6003c7ade4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pica-notification-box.alert.alert-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19fbfff4-06ac-4375-a80f-113679e268af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-notification-box alert alert-danger</value>
      <webElementGuid>bb666464-f0cd-4477-adb2-192c71884478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>a1aa742d-5b53-4a2b-80b5-df4533fe82a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please fill in all missing fields×</value>
      <webElementGuid>0458eb7b-0258-4842-894d-2bf0b2d6c471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification_290962662&quot;)/div[@class=&quot;pica-notification-box alert alert-danger&quot;]</value>
      <webElementGuid>fbf1d210-23ab-4ca4-b7b3-fe386bc61757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notification_290962662']/div</value>
      <webElementGuid>495a7ced-9241-4bf9-96c7-3c6a77fcebb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[3]</value>
      <webElementGuid>bd61269b-8f58-4745-abce-af3b9546fa59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>7e28a87e-4e9a-49d9-95f8-ae217a110d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Please fill in all missing fields×' or . = 'Please fill in all missing fields×')]</value>
      <webElementGuid>0c5e6ed9-fca9-45a3-85f3-8f20376c5681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
