<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>footer_imprint</name>
   <tag></tag>
   <elementGuidId>1fc6fee9-6c11-4771-8923-71b16a22e1df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;label_imprint&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='label_imprint']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>abbe41ca-8a1f-4103-a6d4-1fc8cca33263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label_imprint</value>
      <webElementGuid>95ed5a95-ac37-4fd2-982b-b6161c0534fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imprint</value>
      <webElementGuid>07cc92c7-8692-411e-ae7c-fcd29cae4fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_footer&quot;)/div[@class=&quot;pica-pipe-group&quot;]/a[2]/lang[1]</value>
      <webElementGuid>511c656c-b88c-431f-bdcf-ae56b798725c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='label_imprint']</value>
      <webElementGuid>fc3baabc-38b0-47a4-888e-cfd796315798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_footer']/div/a[2]/lang</value>
      <webElementGuid>8d7c193b-76ff-4fd4-be26-d975a415bac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/following::lang[1]</value>
      <webElementGuid>4dddd837-09c5-4fd9-b7db-b633fc9e2a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::lang[2]</value>
      <webElementGuid>2bea0ca9-acfb-4699-be17-47af5c133dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::lang[1]</value>
      <webElementGuid>991f3a7a-ac1f-4b9b-a06b-2e96effadd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Accessibility Problem'])[1]/preceding::lang[2]</value>
      <webElementGuid>bf057eb4-99ce-492c-80cd-e742d7ec9f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Imprint']/parent::*</value>
      <webElementGuid>a5cbfc4f-7de7-4b44-94a1-151da8f72200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[2]/lang</value>
      <webElementGuid>d137e79c-e60f-40ed-b7a7-578d99dbd11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'label_imprint' and (text() = 'Imprint' or . = 'Imprint')]</value>
      <webElementGuid>0a9ea6fa-04b6-4939-bf5d-53f08937e729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
