<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>license</name>
   <tag></tag>
   <elementGuidId>0b415337-27f5-474d-9f3f-1f346d249133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;label_licenses&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='label_licenses']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>974d9776-cc85-4e02-bf6d-04351e805234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label_licenses</value>
      <webElementGuid>769e9ba7-b453-4108-b203-0801719b0108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-plural</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>da902a7b-5828-4dd0-be91-c6546edd77b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>License</value>
      <webElementGuid>728698d2-6ee5-495c-932f-281328a512e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_content&quot;)/div[@class=&quot;pica-boxes&quot;]/div[@class=&quot;pica-box pica-block-on-small&quot;]/div[@class=&quot;pica-box-head clearfix&quot;]/h5[@class=&quot;pull-left&quot;]/a[1]/lang[1]</value>
      <webElementGuid>adbf250e-2740-484d-a257-e59931d95555</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='label_licenses']</value>
      <webElementGuid>8219edda-d60c-44a6-9d24-204150c75fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div[2]/div/div/h5/a/lang</value>
      <webElementGuid>63547215-8421-4a93-aed7-f09c31375c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage'])[3]/following::lang[1]</value>
      <webElementGuid>a744027e-362c-48c9-9746-f80f0cef6e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folders'])[2]/following::lang[2]</value>
      <webElementGuid>6bcba4ef-e3f5-4cbb-9c68-f55bef95bbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage'])[4]/preceding::lang[1]</value>
      <webElementGuid>8cb81d77-7902-42aa-b9e2-c96231da989a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Mail'])[1]/preceding::lang[2]</value>
      <webElementGuid>2b72e129-9b77-48ad-b449-7c9942f90bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='License']/parent::*</value>
      <webElementGuid>f7592453-6a34-4cbf-836e-869011a93b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5/a/lang</value>
      <webElementGuid>22b8d285-343e-47d9-84ef-1cbb5c67cabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'label_licenses' and (text() = 'License' or . = 'License')]</value>
      <webElementGuid>337b4981-e1c9-4b52-8531-a85c16b6f54f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
