<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>348ecf0b-e7da-4ed7-a9d1-73290800da07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2caaa02d-76d7-4cfe-9d60-dd039d91dc3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_username</value>
      <webElementGuid>a269f805-fe96-4a4b-aa28-6624b4b1fd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mfa</value>
      <webElementGuid>31075245-2271-421a-bffe-124f6fa39256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>520d0092-556e-48b9-b0e3-f65a25514d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>7a3835c5-4292-4b04-a4d8-f980a4dcfc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>0f507f84-a0d4-4435-b518-0490eee7dfd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>6033e670-ea80-4f79-8038-5bf077a02e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>35e60dd3-04d2-4aec-bec4-2982f1ff33d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_username&quot;)</value>
      <webElementGuid>2203dded-efac-401d-98c5-956e663db4f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_username']</value>
      <webElementGuid>85b6062a-1c7c-4170-b98b-f0f47e178472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div/input</value>
      <webElementGuid>cdd13f23-0882-4d9a-9f25-8d9ca05fe79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>da5d7a0b-0604-478e-9840-1cf706e47a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login_username' and @type = 'text' and @name = 'Username' and @placeholder = 'Email']</value>
      <webElementGuid>a339c29c-0012-4e3e-8f9e-2fa3c2f94900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
