<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Draw</name>
   <tag></tag>
   <elementGuidId>77fe9e7c-bb0c-40a0-a76c-17b29a81005f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#draw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='draw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fd3f021f-c317-4752-a212-b153f0340636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>25514bc9-cdcb-4e4e-a24f-fd753b5dd750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>draw</value>
      <webElementGuid>cea11038-0ade-4b63-95ec-72e3be2ee7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>draw</value>
      <webElementGuid>5c2ab325-ce74-42bf-b960-d38ccd10edc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Draw</value>
      <webElementGuid>1a4c9ced-b239-476f-a708-9db706d19914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hint</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1591908b-b8e2-4231-bb09-241651d1af06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hint-direction</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>77302805-2a8b-4fbe-b33c-0817e05d0bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hint-offset</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>5b74bdf2-3109-41f1-a16e-df5e30cd400e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hint-title</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>5f3ec3e5-75ff-47b4-b84a-2b1d7437e256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draw</value>
      <webElementGuid>931de8c1-c220-4c48-9339-77baa9b23392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;draw&quot;)</value>
      <webElementGuid>d796b8bb-4d19-452b-a27e-05b50cb8b89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Open - PowerFolder/iframe_concat(id(, , pica_embedded, , )ifra_b348c2</value>
      <webElementGuid>a73f2a19-aca9-4b4d-807b-0db02b60757e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='draw']</value>
      <webElementGuid>0e10031c-89cb-47fd-b8b4-8b917b5f311a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toolbar']/div/div/section/ul/li[4]/a</value>
      <webElementGuid>fd0af126-7ec9-4aa7-8273-d89380ac1d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Draw')]</value>
      <webElementGuid>531ef65f-e7ad-4aac-8ff3-4e30701ffb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert'])[1]/following::a[1]</value>
      <webElementGuid>c5a89de2-b8e6-4df3-b4b6-2bbe5772b7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>100dfe01-f4ca-4ec8-b2f0-55860fcde5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layout'])[1]/preceding::a[1]</value>
      <webElementGuid>d20c8205-d03c-4172-ac4d-30e292f97556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='References'])[1]/preceding::a[2]</value>
      <webElementGuid>9a2048be-fc97-4c72-bd1e-90c634ee544e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Draw']/parent::*</value>
      <webElementGuid>08a51071-7f4e-4d08-8e9e-0115114ad25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>ab9b858c-70ea-4bce-9e37-cd83d1d08a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'draw' and (text() = 'Draw' or . = 'Draw')]</value>
      <webElementGuid>6a2cd13f-3266-4fe6-aae6-697c626fd184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
