<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>c3ab744e-ffa7-4394-b329-3f3ed02837e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.normal.dlg-btn.primary.canfocused.over</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='window-view3933']/div[2]/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>413a2811-1eac-45d7-99ab-cb5041273fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn normal dlg-btn primary canfocused over</value>
      <webElementGuid>ce0a54a2-917b-4c8e-b749-750eddc0def7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>result</name>
      <type>Main</type>
      <value>ok</value>
      <webElementGuid>48e3ab75-d125-4c1d-8f2a-80283868930d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ratio</name>
      <type>Main</type>
      <value>ratio</value>
      <webElementGuid>90d9e8fe-1609-43a6-bdc7-d8c8230926d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ff662113-ebb2-4128-8346-c8971dcf8bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>4f46508e-7de4-42e9-a7b4-b8d564c72314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;window-view3933&quot;)/div[@class=&quot;body&quot;]/div[@class=&quot;footer center&quot;]/button[@class=&quot;btn normal dlg-btn primary canfocused over&quot;]</value>
      <webElementGuid>47c3e51d-eff0-42d1-9430-b68a763ce76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Open - PowerFolder/iframe_concat(id(, , pica_embedded, , )ifra_b348c2</value>
      <webElementGuid>e89b0211-26b0-4496-9f2e-2e590840aa57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='window-view3933']/div[2]/div[3]/button</value>
      <webElementGuid>ffcb4807-c8ca-4a67-8ba6-3221a02aba2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy, cut and paste actions'])[1]/following::button[1]</value>
      <webElementGuid>3fefb7e4-6a0f-4dd3-a24c-95ecafcfc21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>1b7c2113-f1b7-43e7-b969-c71470535d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/button</value>
      <webElementGuid>0b818b46-612c-4f60-a0fe-ad136b0c7bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>7f3871d7-7c97-4808-a7bd-622f8dd79df6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
