<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Wrap long headings_id_hor_ruler</name>
   <tag></tag>
   <elementGuidId>c87e3041-328a-40ef-afc1-c7d9e8bcb24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_hor_ruler</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='id_hor_ruler']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>17933475-ab3e-4749-b8f3-f0a3ed367172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_hor_ruler</value>
      <webElementGuid>e8b35268-5aca-43cc-a703-dd192ff5b755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block_elem</value>
      <webElementGuid>71129c98-03f6-4148-96b6-81fe0882d6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1779</value>
      <webElementGuid>a35924ec-9acc-4201-b15d-8ec68413f285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>fbe504ea-d010-4908-bec8-305a49e1997c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_hor_ruler&quot;)</value>
      <webElementGuid>4d4fe455-df35-4027-8fd2-426e456b81d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Open - PowerFolder/iframe_concat(id(, , pica_embedded, , )ifra_b348c2</value>
      <webElementGuid>ae4d49f5-307c-48b6-aefc-7f1f71d75af1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='id_hor_ruler']</value>
      <webElementGuid>d7a40e3c-6753-4efe-a0d9-c587bdbfc542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id_panel_top']/canvas</value>
      <webElementGuid>b6567ce3-e0a5-42f5-b577-1827235cbb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/canvas</value>
      <webElementGuid>e044fb30-4145-4919-814c-c329c8b6c2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'id_hor_ruler']</value>
      <webElementGuid>1375d566-3d36-4d78-ba21-0fa658ba2be2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
