<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Redo_pica_uploadform_valid_till</name>
   <tag></tag>
   <elementGuidId>92b808a8-628c-43b0-b649-7a337258ee00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pica_uploadform_valid_till</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pica_uploadform_valid_till']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45b18a4f-e95e-43a8-83ec-42bcb3e64033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f2cb03a-890a-46cd-9b88-064163c1aae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d6097bb4-8f32-4c18-a57f-6529fac51937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_valid_till</value>
      <webElementGuid>eb862136-3e74-43e9-9d0b-82b558ce420c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_uploadform_valid_till</value>
      <webElementGuid>acf9a753-59a8-4396-ba69-dfbf9872e81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Valid till</value>
      <webElementGuid>98c0acc8-dd9a-470b-8cdd-e2f59a94a2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_uploadform_valid_till&quot;)</value>
      <webElementGuid>6248028e-af3a-4bef-bbfb-253b953cacbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_uploadform_valid_till']</value>
      <webElementGuid>03cf95a3-24e7-412e-99d0-d05bd944d185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_uploadform_dialog']/div/div/div[2]/div[4]/input</value>
      <webElementGuid>9eabd087-7be8-4274-a4a8-779f103503de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/div[2]/div[4]/input</value>
      <webElementGuid>2fa8fff6-111e-45b2-ad76-ac5cd1136c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pica_uploadform_valid_till' and @placeholder = 'Valid till']</value>
      <webElementGuid>b1671b5f-de7f-4c83-bd9b-c8daf8972ea1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
