<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Set_Password</name>
   <tag></tag>
   <elementGuidId>ade7b850-4f6f-4e8f-87c2-5db908abf87a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pica_uploadform_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pica_uploadform_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>738c9077-d817-45cb-8bea-35a52e9d20a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_uploadform_password</value>
      <webElementGuid>697b1bbe-79dd-4215-adf2-42c0ad22ef0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0fdfe510-af2a-408e-a5cd-dcc05b64478e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d626bcda-344e-4eac-9d2c-931f8dbe31f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>placeholder_password_form</value>
      <webElementGuid>62790143-dbf3-4821-9d80-9dcdf0e82680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password For Upload Form</value>
      <webElementGuid>39216f41-8704-4b18-aa07-2e38ff9704ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_uploadform_password&quot;)</value>
      <webElementGuid>e0424f75-4ed6-453b-94fa-22735125fb99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pica_uploadform_password']</value>
      <webElementGuid>10a3e363-680b-42dc-87ac-1f4d3ae1ec36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_uploadform_dialog']/div/div/div[2]/div[7]/input</value>
      <webElementGuid>fbc95595-2f6b-4cf2-8c97-eb952a77c905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>98dafcaa-7c79-4e8d-8de7-2e0dbb9af639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pica_uploadform_password' and @type = 'password' and @placeholder = 'Password For Upload Form']</value>
      <webElementGuid>4852103c-5e16-4544-98af-2e4518a72921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
