<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClickOnRegisterNewAccount</name>
   <tag></tag>
   <elementGuidId>cb154d35-8508-47ae-b69a-11aca824b396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div/div/div[2]/div/div/div/form/p/a[1]/lang</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;action_sign_up&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>526bf19a-9fb2-4594-a3e9-01db83129c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action_sign_up</value>
      <webElementGuid>411a9d00-29b8-4665-a37b-b1ca953e9f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Créer un nouveau compte</value>
      <webElementGuid>af9dd3ca-3bfa-4dbe-b8dc-d9c960451b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_form&quot;)/p[@class=&quot;clearfix&quot;]/a[1]/lang[1]</value>
      <webElementGuid>328456ad-b5ec-4347-b4ae-3999a6c5182d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='action_sign_up']</value>
      <webElementGuid>4d6d39da-b911-4ce9-8dff-b5b4dcf8e747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/p/a/lang</value>
      <webElementGuid>17763cc0-9908-4cb1-8f4c-18e1ef4d314f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ou'])[1]/following::lang[1]</value>
      <webElementGuid>47f311ad-14eb-4585-9a92-2835c2625a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connexion'])[1]/following::lang[2]</value>
      <webElementGuid>cc87b559-070f-48a0-bdde-163ecc5603af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Récupérer le mot de passe'])[1]/preceding::lang[1]</value>
      <webElementGuid>d8096a14-fcd9-4a02-b8c8-c833bdb073ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rester connecté'])[1]/preceding::lang[2]</value>
      <webElementGuid>bfdb4560-c382-4f87-b05e-0313f3324153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Créer un nouveau compte']/parent::*</value>
      <webElementGuid>637b979b-7859-4f33-9af6-a8174d8d5345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/lang</value>
      <webElementGuid>fc4e9db5-af84-40e6-a4ce-6b6d75118fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'action_sign_up' and (text() = 'Créer un nouveau compte' or . = 'Créer un nouveau compte')]</value>
      <webElementGuid>bb048bc8-c7a8-41bd-84ec-b2122c88f4f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
