<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close links config button</name>
   <tag></tag>
   <elementGuidId>0f13e391-528a-4932-9515-b6e424272954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_share_dialog']//div[contains(@class,'modal-footer')]/button[@data-bs-dismiss='modal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pica_share_dialog .modal-footer button[data-bs-dismiss='modal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f13e391-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-secondary</value>
      <webElementGuid>0f13e391-0001-0001-0001-000000000002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>0f13e391-0001-0001-0001-000000000003</webElementGuid>
   </webElementProperties>
</WebElementEntity>
