<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clear_date</name>
   <tag></tag>
   <elementGuidId>6d0b5bc2-c83a-49f8-aec1-a2464661c3e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica_account_dialog']/div/div/div[2]/div/div[4]/div[3]/div/div/ul/li[2]/table/tbody/tr/td[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.glyphicon.glyphicon-trash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2a4a42f8-4017-447b-988b-1b4478c5cd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-trash</value>
      <webElementGuid>01d23e36-ac39-4263-a8bb-530b79f505fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_account_dialog&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;pica-nav-tab&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-xs-4 pica-block-on-small&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;bootstrap-datetimepicker-widget dropdown-menu usetwentyfour top&quot;]/ul[@class=&quot;list-unstyled&quot;]/li[@class=&quot;picker-switch accordion-toggle&quot;]/table[@class=&quot;table-condensed&quot;]/tbody[1]/tr[1]/td[2]/a[1]/span[@class=&quot;glyphicon glyphicon-trash&quot;]</value>
      <webElementGuid>33d5ba68-21d3-4f6a-8d9c-9c8cbb88e109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_account_dialog']/div/div/div[2]/div/div[4]/div[3]/div/div/ul/li[2]/table/tbody/tr/td[2]/a/span</value>
      <webElementGuid>640b4360-e328-4273-9162-4f4fe72faaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a/span</value>
      <webElementGuid>24203e47-3e71-40fd-b28a-a0eff5e8781b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
