<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Details_last_name_change</name>
   <tag></tag>
   <elementGuidId>fb4d1580-7605-4768-93d5-2d577191d5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_change_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[3]/table[2]/tbody/tr[4]/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fde77ae3-dffc-44fb-aa2e-84bcbfd247f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_change_last_name</value>
      <webElementGuid>b82d5ae4-833f-4f2b-aec2-01942299a882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>5e05e253-9af1-462a-8866-97a6cba14ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Change
                </value>
      <webElementGuid>c3e36518-fbeb-4a36-b9a0-38f77580d5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_change_last_name&quot;)</value>
      <webElementGuid>438f113b-0d32-4fae-9ed8-6a83d6263be6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='profile_change_last_name']</value>
      <webElementGuid>6b39bcc2-9026-45c4-9cbb-191dacd24fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/table[2]/tbody/tr[4]/td[3]/a</value>
      <webElementGuid>d82573b1-d1bb-4181-9e82-bdddb5c89dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nachname deap'])[1]/following::a[1]</value>
      <webElementGuid>17a640a6-3145-4b10-90ac-b5eb9d8d863e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::a[1]</value>
      <webElementGuid>b7fd08fc-543a-429e-a27c-215bf0324525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/preceding::a[1]</value>
      <webElementGuid>7ac1e22e-3322-4719-8ba6-231b95ad533e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/a</value>
      <webElementGuid>c7fd3aa7-dcc9-4a3c-b490-95e0bb543d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'profile_change_last_name' and (text() = '
                    Change
                ' or . = '
                    Change
                ')]</value>
      <webElementGuid>cbf1f7f9-71bb-45ff-b955-0ba0eab06690</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
