<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_last_name</name>
   <tag></tag>
   <elementGuidId>40d95a7e-a8d1-4d3d-9e44-5ed484b3303c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[2]/tbody/tr[4]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f138f41d-0e20-42bc-bb54-8da1d3814f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_last_name</value>
      <webElementGuid>c055af5c-2a6c-4d69-9d26-b4b00decd2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-static</value>
      <webElementGuid>1b78f524-a485-40a4-b9da-fc678f5e738f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nachname deap</value>
      <webElementGuid>3371f745-a3b7-4e26-a306-5141ccd59bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_last_name&quot;)</value>
      <webElementGuid>aede4cf1-5e22-4fe5-ad1e-6e1b907b784a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='profile_last_name']</value>
      <webElementGuid>3a832eed-4cdc-40f6-9c90-68d03e0d2d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/table[2]/tbody/tr[4]/td[2]</value>
      <webElementGuid>ebc0f5b3-96a7-45d0-b426-f2fb419b7f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::td[1]</value>
      <webElementGuid>e72d0c84-3008-426a-93f8-9e15e46bbc22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[7]/following::td[2]</value>
      <webElementGuid>aeeb78f9-7a7c-4d69-8107-d8ecc799bb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[8]/preceding::td[1]</value>
      <webElementGuid>c7787233-3767-48d8-ab19-9d13505b40c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/preceding::td[2]</value>
      <webElementGuid>eca972ad-abb8-44d4-8b9a-cf8e33ead61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='nachname deap']/parent::*</value>
      <webElementGuid>0ce6308e-1828-41d3-9eff-f0b4aa5a6ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[4]/td[2]</value>
      <webElementGuid>a3a8e1f5-0dd2-425d-a5ba-167f50b09e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'profile_last_name' and (text() = 'nachname deap' or . = 'nachname deap')]</value>
      <webElementGuid>f2c30bd4-080c-4480-bf50-bb195ea4acc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
