<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_download</name>
   <tag></tag>
   <elementGuidId>d9cfdb61-d335-4a21-ba39-0eb994802348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pica-table-selection-multi.files-ui-download > span.pica-glyph.glyphicons.glyphicons-download</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//thead[@id='files_select_header']/tr/th[3]/div[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c76569cf-799a-441d-80f1-e81bcdb46c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-glyph glyphicons glyphicons-download</value>
      <webElementGuid>ff12e51d-9003-4251-9764-f2d869052cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;files_select_header&quot;)/tr[1]/th[@class=&quot;text-right&quot;]/div[@class=&quot;pica-table-selection-context pica-inline hidden-xs text-right&quot;]/a[@class=&quot;pica-table-selection-multi files-ui-download&quot;]/span[@class=&quot;pica-glyph glyphicons glyphicons-download&quot;]</value>
      <webElementGuid>afcfd140-f911-49a5-888c-09c69039e442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//thead[@id='files_select_header']/tr/th[3]/div[2]/a/span</value>
      <webElementGuid>1ba26fc8-23c2-479c-86ff-484566b5c175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div[2]/a/span</value>
      <webElementGuid>84f53576-d6ac-4540-9ffc-0b5ae5405731</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
