<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lang_Password required</name>
   <tag></tag>
   <elementGuidId>bed52290-efdb-443a-9ad7-70454d2cfe30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pica_link_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;dialog_title_password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>1cea1a9e-c4f3-40fc-9844-68c759e97334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dialog_title_password</value>
      <webElementGuid>7196764a-d4ba-4c3b-9dad-2042bb41269d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password required</value>
      <webElementGuid>8e9e9c1a-895b-4f5d-9599-0b2134c07fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_password_dialog&quot;)/div[@class=&quot;pica-dialog-small modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/div[@class=&quot;modal-header&quot;]/h4[@class=&quot;pica-dialog-title modal-title&quot;]/lang[1]</value>
      <webElementGuid>b71940d6-b02b-4875-adee-8790f208d41f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
