<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Copy Link_left icon glyphicons glyphic_b5fc92</name>
   <tag></tag>
   <elementGuidId>49053317-f61e-4591-9d8f-2eb22fdd8fb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='filelink_upload']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.left.icon.glyphicons.glyphicons-cloud-upload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f5af8c77-45e6-44fb-8f84-8b1c9081880c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>left icon glyphicons glyphicons-cloud-upload</value>
      <webElementGuid>ab2affd8-405d-422b-9c6b-b72af772a32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filelink_upload&quot;)/span[@class=&quot;left icon glyphicons glyphicons-cloud-upload&quot;]</value>
      <webElementGuid>4149bc11-a841-4465-8d6c-b919bff1f84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>adf50f71-9f28-405a-8274-c75cde6546b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>left icon glyphicons glyphicons-cloud-upload</value>
      <webElementGuid>5977cab3-0e94-4f98-b4d3-18a86ff33249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filelink_upload&quot;)/span[@class=&quot;left icon glyphicons glyphicons-cloud-upload&quot;]</value>
      <webElementGuid>944f6043-d606-4ed7-a963-6a79f3428cf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='filelink_upload']/span</value>
      <webElementGuid>9134070c-9fb0-42f4-87ea-97c6858f871d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Link'])[1]/following::span[1]</value>
      <webElementGuid>f56631a2-8480-41f3-a432-7a3d624498d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::span[4]</value>
      <webElementGuid>fc06f48a-3c6b-42dc-b628-3ad301447aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/preceding::span[2]</value>
      <webElementGuid>64abfb18-03ad-43e2-919d-6d4fea5a3c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::span[3]</value>
      <webElementGuid>c7f8f9ab-0544-4f22-ac91-ab75da99bb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/span</value>
      <webElementGuid>b1e0e49f-3621-409e-ac17-4e9eef407336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
