<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account_rescan_filesystem</name>
   <tag></tag>
   <elementGuidId>b4d95fd0-967a-43a4-ad7c-5596b5593cc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pica_settings_rescan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pica_settings_rescan</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4d95fd0-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pica_settings_rescan</value>
      <webElementGuid>b4d95fd0-0001-0001-0001-000000000002</webElementGuid>
   </webElementProperties>
</WebElementEntity>
