<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_on_sub</name>
   <tag></tag>
   <elementGuidId>a20bf696-ccd3-4312-94fd-ae7d0d0b98f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pica-crumb > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/div[1]/div[1]/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>67ece984-0277-44e7-ad3a-16774a4317ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FD_Test_08mars2025013357</value>
      <webElementGuid>09cd0b44-258a-4c38-8103-fc73ef28a619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_action_search&quot;)/a[@class=&quot;pica-crumb&quot;]/span[1]</value>
      <webElementGuid>61b3f9ef-08fd-439d-8a50-a3c988fed45b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_action_search']/a[2]/span</value>
      <webElementGuid>c9152d06-2f54-4f8e-970f-144c5573e968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[1]</value>
      <webElementGuid>9cf9d111-9d5b-4ee2-8d7d-ae56c2b77be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::span[1]</value>
      <webElementGuid>dd573ae3-aa80-41f3-87d6-e05844394fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unlimited'])[1]/preceding::span[2]</value>
      <webElementGuid>378f1c0a-f446-419c-8fbe-c5e020000d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/preceding::span[6]</value>
      <webElementGuid>9c42e4b3-ddc9-403f-a4a3-f3cb96aaacad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FD_Test_08mars2025013357']/parent::*</value>
      <webElementGuid>485912c2-2fa3-48b0-8111-ff6ea23325b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>90bf0c67-14f9-4ab2-8739-b997b77d37fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'FD_Test_08mars2025013357' or . = 'FD_Test_08mars2025013357')]</value>
      <webElementGuid>9b6993ab-7324-4b65-8aee-5ec29a8385f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
