<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create Doc</name>
   <tag></tag>
   <elementGuidId>94d51e96-7c98-4f9d-9234-491494b73028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pica-files-create-dropdown']//li[contains(@class,'files-ui-create-doc')]/a[@data-label='document']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pica-files-create-dropdown li.files-ui-create-doc > a[data-label='document']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94d51e96-0001-0001-0001-000000000001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>document</value>
      <webElementGuid>94d51e96-0001-0001-0001-000000000002</webElementGuid>
   </webElementProperties>
</WebElementEntity>
