<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Accounts_Manage</name>
   <tag></tag>
   <elementGuidId>bb90d037-3980-4b31-bf84-71e2354d8a6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;action_manage&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='action_manage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>98f1bd1e-ddf4-411c-a802-fd7e44e77fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action_manage</value>
      <webElementGuid>3d8e2329-e9bf-47e9-8069-d22c38b0a615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage</value>
      <webElementGuid>6e565430-3192-421c-8f11-d032b2e4683d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_content&quot;)/div[@class=&quot;pica-boxes&quot;]/div[@class=&quot;pica-box pica-block-on-small&quot;]/div[@class=&quot;pica-box-head clearfix&quot;]/a[@class=&quot;btn btn-success pull-right&quot;]/lang[1]</value>
      <webElementGuid>976db8ca-3f8e-4a98-b4c1-2cdc59768f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='action_manage']</value>
      <webElementGuid>c27c2796-5866-496c-b596-132a849fde6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div/div/div/a/lang</value>
      <webElementGuid>8355ae03-ea6b-4b9b-98f3-9e7750f5da21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[2]/following::lang[1]</value>
      <webElementGuid>d4a3527c-9eba-472f-b809-0691265dbe09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Storage'])[2]/preceding::lang[1]</value>
      <webElementGuid>2f91bff4-f3a9-4649-91fb-8a2cd5209956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage'])[2]/preceding::lang[2]</value>
      <webElementGuid>f60e6ae9-f3ba-4ba9-a2d2-ee1748504e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage']/parent::*</value>
      <webElementGuid>04245505-1a6a-4907-b20c-28a244831443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/lang</value>
      <webElementGuid>103a9b15-c2f2-404c-a2e9-830e1b9bd082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'action_manage' and (text() = 'Manage' or . = 'Manage')]</value>
      <webElementGuid>628b691e-9998-4d0d-9453-6a9ed322b1ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
