<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Folders_Manage</name>
   <tag></tag>
   <elementGuidId>ac772200-2499-45a4-a01c-d73dd264930f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//lang[@name='action_manage'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>7f3ef958-96eb-42aa-8279-f8cd2ac3136b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action_manage</value>
      <webElementGuid>e8d35c5f-d88f-425e-b49d-16ea15e2db2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage</value>
      <webElementGuid>d412bc48-9f68-478d-a8ff-9add55a86f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_content&quot;)/div[@class=&quot;pica-boxes&quot;]/div[@class=&quot;pica-box pica-block-on-small&quot;]/div[@class=&quot;pica-box-head clearfix&quot;]/a[@class=&quot;btn btn-success pull-right&quot;]/lang[1]</value>
      <webElementGuid>e7a59d1d-759e-411a-aee2-3d2fadec9b7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//lang[@name='action_manage'])[3]</value>
      <webElementGuid>d1fa1016-696d-48df-875d-155d649704e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_content']/div/div[3]/div/a/lang</value>
      <webElementGuid>76ef2996-25b9-4c55-a816-3f05498cb81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folders'])[2]/following::lang[1]</value>
      <webElementGuid>3695e1ca-a31c-4bdd-91d9-573eaebb6e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage'])[2]/following::lang[2]</value>
      <webElementGuid>5a00534d-7333-4425-949c-bb8532b900ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License'])[1]/preceding::lang[1]</value>
      <webElementGuid>fe898848-9582-49ed-a88b-a44e6d46483d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage'])[4]/preceding::lang[2]</value>
      <webElementGuid>c1709fbe-9268-421f-beb8-9c9dce93697e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/lang</value>
      <webElementGuid>8cbf417e-1719-4018-86ff-28ac0e7b731c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'action_manage' and (text() = 'Manage' or . = 'Manage')]</value>
      <webElementGuid>acb3c799-9c33-45e2-941b-59e64ac2fc0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
