<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create presentation</name>
   <tag></tag>
   <elementGuidId>b6810b50-d547-4473-acce-268576e78ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//thead[3]/tr/th/div/ul/li[7]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pica-glyph.glyphicons.glyphicons-pictures</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>25d8c12d-194f-4eaa-b30d-c45f92a781d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pica-glyph glyphicons glyphicons-pictures</value>
      <webElementGuid>5bfff711-9db6-4804-b668-8ae0c4e8667a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica-files-create-dropdown&quot;)/ul[@class=&quot;pica-arrow-left dropdown-menu&quot;]/li[@class=&quot;files-visible-only-other files-ui-create-doc&quot;]/a[1]/span[@class=&quot;pica-glyph glyphicons glyphicons-pictures&quot;]</value>
      <webElementGuid>66fc631e-9bd0-4cb7-9917-60206ee721e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica-files-create-dropdown']/ul/li[7]/a/span</value>
      <webElementGuid>fa62d077-fbd2-4636-a325-44bf398f7233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//thead[3]/tr/th/div/ul/li[7]/a/span</value>
      <webElementGuid>3d172555-bada-4250-9cfe-f7db47c4593e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
