<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FolderName1_Path</name>
   <tag></tag>
   <elementGuidId>6e6a59dc-5320-4ca5-841a-adb30efe7225</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id='files_files_table']/tbody/tr[@draggable='false'])[1]//a[contains(@class,'pica-name')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8dfcc8f4-1e75-46cc-9c00-f00b680b399c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ordner_15_üü</value>
      <webElementGuid>6b8b8a49-3ab8-4db9-8d14-e56ab723fb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pica_action_search&quot;)/a[@class=&quot;pica-crumb&quot;]/span[1]</value>
      <webElementGuid>841af570-b7b4-4644-89d7-b4b86079e15f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pica_action_search']/a[3]/span</value>
      <webElementGuid>5bbc03d9-0f2c-45bb-8829-b6cd47c89752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='folder_8380'])[1]/following::span[1]</value>
      <webElementGuid>75db7e9e-05dc-4ebc-8e1b-aa4c977cb94b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[2]</value>
      <webElementGuid>aa48a90b-54b6-40f9-bb3b-63bcbf5d1399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ordner_44_äü'])[1]/preceding::span[1]</value>
      <webElementGuid>a3e709b4-638a-4b6a-a760-3b31a859e97f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/preceding::span[6]</value>
      <webElementGuid>4e3c6a23-6dc1-4965-a9b3-0e49892e25c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ordner_15_üü']/parent::*</value>
      <webElementGuid>c38862e6-b46c-45cd-bbfb-d70a2084d13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span</value>
      <webElementGuid>8556fc62-c160-4452-be33-d2b536ad34f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ordner_15_üü' or . = 'Ordner_15_üü')]</value>
      <webElementGuid>026467cf-bc8d-4542-a025-c18087e23b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='folder_5836'])[1]/following::span[1]</value>
      <webElementGuid>eef14fbe-a209-4e46-b7c5-047565c4e90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ordner_01_üö'])[1]/preceding::span[1]</value>
      <webElementGuid>fe7920b1-3a9d-4c84-b75a-2c059ce7e764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ordner_06_üö']/parent::*</value>
      <webElementGuid>33ff7525-f1c4-4541-809b-94545ffb3902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ordner_06_üö' or . = 'Ordner_06_üö')]</value>
      <webElementGuid>7b33c021-c795-46c5-b9e8-98eb02a4a6ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
