<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Accessibility Problem</name>
   <tag></tag>
   <elementGuidId>b98a609f-7624-4398-8dbf-6135ae30c25a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lang[@name='label_report_accessibility_problem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lang[name=&quot;label_report_accessibility_problem&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>5916bce7-c979-466c-a5e1-274447176702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label_report_accessibility_problem</value>
      <webElementGuid>e8a07ce0-24ed-4c5f-a3cf-f5fe6c1261d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Signaler un problème d’accessibilité</value>
      <webElementGuid>c3a9bf17-25f6-4ae5-bb1d-274f35954d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;wallpaper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-8 col-md-6 col-lg-6 pica-relative&quot;]/div[@class=&quot;pica-dialog&quot;]/div[1]/div[1]/div[@class=&quot;pica-pipe-group pica-space-top text-center&quot;]/a[9]/lang[1]</value>
      <webElementGuid>fabcbda6-d816-4cda-8931-ff822a262ef8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lang[@name='label_report_accessibility_problem']</value>
      <webElementGuid>ec68d2b0-e8fb-49a3-855d-1407df2b64e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propulsé par PowerFolder'])[1]/following::lang[1]</value>
      <webElementGuid>272102aa-34b1-4813-a625-45b9b0776e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Politique de confidentialité'])[1]/following::lang[2]</value>
      <webElementGuid>5e376867-16bd-4db3-bd07-483a40adc4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Signaler un problème d’accessibilité']/parent::*</value>
      <webElementGuid>9afa8a84-864c-454a-9bda-c86d9507ce89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[9]/lang</value>
      <webElementGuid>d62610a7-04cc-4871-a5c1-8d015b2d6d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lang[@name = 'label_report_accessibility_problem' and (text() = 'Signaler un problème d’accessibilité' or . = 'Signaler un problème d’accessibilité')]</value>
      <webElementGuid>11bb43c8-6f94-4808-84ce-3e1386cf2b71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
